### ISSUE TITLE
RevertSam does not accept /dev/stdin and should have a better error message

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#1008]
Here's the cryptic error message when we try and run `RevertSam` with `I=/dev/stdin`.  Full command line: 

```
RevertSam INPUT=/dev/stdin OUTPUT=/dev/stdout SORT_ORDER=queryname RESTORE_ORIGINAL_QUALITIES=false REMOVE_DUPLICATE_INFORMATION=false REMOVE_ALIGNMENT_INFORMATION=false ATTRIBUTE_TO_CLEAR=[] SANITIZE=true
```

Stack trace:
```
Exception in thread "main" htsjdk.samtools.SAMException: Cannot determine candidate qualities: no qualities found.
	at htsjdk.samtools.util.QualityEncodingDetector.generateCandidateQualities(QualityEncodingDetector.java:228)
	at htsjdk.samtools.util.QualityEncodingDetector.generateBestGuess(QualityEncodingDetector.java:382)
	at htsjdk.samtools.util.QualityEncodingDetector.detect(QualityEncodingDetector.java:335)
	at picard.sam.RevertSam.createReadGroupFormatMap(RevertSam.java:534)
	at picard.sam.RevertSam.doWork(RevertSam.java:271)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:96)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:106)
```

**Comment by grozhnev** [comment]
As it is clear to me, you got the exception because of SANITIZE=true.
What is the purpose of using this parameter?
In the documentation [RevertSam](http://broadinstitute.github.io/picard/command-line-overview.html#RevertSam) it is said that 

> 

SANITIZE (Boolean) | WARNING: This option is  potentially destructive. If enabled will discard reads in order to  produce a consistent output BAM. Reads discarded include (but are not  limited to) paired reads with missing mates, duplicated records, records  with mismatches in length of bases and qualities. This option can only  be enabled if the output sort order is queryname and will always cause  sorting to occur.  Default value: false. This option can be set to  'null' to clear the default value. Possible values: {true, false}
-- | --

**Comment by nh13** [comment]
No where does it state in the options description about requiring the input not to be stdin. Yes, I want to use that option, as I have a BAM that was merged improperly and needs to be fixed up, as I don’t have access to the upstream data.

**Comment by grozhnev** [comment]
As it is clear to me, you got the exception because of SANITIZE=true.
What is the purpose of using this parameter?
In the documentation [RevertSam](http://broadinstitute.github.io/picard/command-line-overview.html#RevertSam) it is said that

> 

SANITIZE (Boolean) | WARNING: This option is  potentially destructive. If enabled will discard reads in order to  produce a consistent output BAM. Reads discarded include (but are not  limited to) paired reads with missing mates, duplicated records, records  with mismatches in length of bases and qualities. This option can only  be enabled if the output sort order is queryname and will always cause  sorting to occur.  Default value: false. This option can be set to  'null' to clear the default value. Possible values: {true, false}
-- | --

So, if it is not necessary, it is better not to use it.

**Comment by yfarjoun** [comment]
Huh?

**Comment by sooheelee** [comment]
Would it be possible to update another error message as well?

```
htsjdk.samtools.util.RuntimeIOException: java.io.IOException: File too large
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:247)
```

Should tell users to try setting `TMP_DIR`.

This is a request from a forum user at https://gatkforums.broadinstitute.org/gatk/discussion/11607/revertsam-exception-file-too-large#latest.

**Comment by sooheelee** [comment]
A researcher has reported on the forum that the streaming error depends on the parameter `SANITIZE=true` at https://gatkforums.broadinstitute.org/gatk/discussion/comment/49098#Comment_49098 and also thinks it odd that if the end point of a stream is ReverSam that this should then error the tool.

**Comment by deyanyosifov** [comment]
This error has appeared again in picard 3.0.0  RevertSam does not accept input from /dev/stdin and gives an error. I have picard MarkDuplicates and picard RevertSam steps in my pipeline that are connected through a pipe. It worked normally with picard 2.26.8 but gives an error after I updated to picard 3.0.0:
```
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: Read error; BinaryCodec in readmode; streamed file (filename not available)
	at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:423)
	at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:394)
	at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)
	at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:282)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:880)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:854)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:848)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:816)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:591)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:570)
	at picard.sam.RevertSam.doWork(RevertSam.java:314)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:289)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:104)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:114)
Caused by: java.io.IOException: Illegal seek
	at java.base/sun.nio.ch.FileDispatcherImpl.seek0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.seek(FileDispatcherImpl.java:78)
	at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:344)
	at htsjdk.samtools.seekablestream.SeekablePathStream.position(SeekablePathStream.java:68)
	at htsjdk.samtools.seekablestream.SeekablePathStream.eof(SeekablePathStream.java:58)
	at htsjdk.samtools.seekablestream.SeekableStream.available(SeekableStream.java:106)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBytes(BlockCompressedInputStream.java:583)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBytes(BlockCompressedInputStream.java:562)
	at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:510)
	at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
	at htsjdk.samtools.util.BlockCompressedInputStream.
readBlock(BlockCompressedInputStream.java:458)
	at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)
	at java.base/java.io.DataInputStream.read(DataInputStream.java:151)
	at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:421)
```
If I save the output of MarkDuplicates to a file and then give it as input to RevertSam, it works. The piped command (O=/dev/stdout | I=/dev/stdin) works if the output of MarkDuplicates from version 3.0.0 is piped to RevertSam from version 2.28.6. So, I assume that the problem is in RevertSam 3.0.0, specifically. Could you patch the program because it is more convenient and faster to use a piped command instead of having to create an intermediate file?

**Comment by jganbat-fn** [comment]
Yeah I can confirm we are seeing the similar thing with Piped input as well.
I set VERBOSITY to DEBUG and got a slightly better error message
```
Illegal argument value: Positional arguments were provided ',I{/dev/stdin{O{/dev/stdout{ATTRIBUTE_TO_CLEAR=null{REMOVE_DUPLICATE_INFORMATION=true{REMOVE_ALIGNMENT_INFORMATION=false{SORT_ORDER=coordinate{RESTORE_HARDCLIPS=false}' but no positional argument is defined for this tool.
[main_samview] fail to read the header from "-".
```
