### ISSUE TITLE
FixMateInformation throws an exception when no arguments are given

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#1009]
It should instead print the help message.  Here's what I get:

```
java -jar build/libs/picard.jar FixMateInformation
16:11:21.670 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/nhomer/git/picard/build/libs/picard.jar!/com/intel/gkl/native/libgkl_compression.dylib
[Mon Dec 04 16:11:21 MST 2017] FixMateInformation    ASSUME_SORTED=false ADD_MATE_CIGAR=true IGNORE_MISSING_MATES=true VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Dec 04 16:11:21 MST 2017] Executing as nhomer@Nils on Mac OS X 10.12.2 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_66-b17; Deflater: Intel; Inflater: Intel; Picard version: 2.10.0-81-gbfc2d39-SNAPSHOT
[Mon Dec 04 16:11:21 MST 2017] picard.sam.FixMateInformation done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=257425408
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: Must specify either an explicit OUTPUT file or a single INPUT file to be overridden.
	at picard.sam.FixMateInformation.doWork(FixMateInformation.java:134)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)
```

**Comment by nh13** [comment]
@yfarjoun I am guessing this is barclay issue?

**Comment by cmnbroad** [comment]
Yes, bug in the old parser. If you add "-Dpicard.useLegacyParser=false" to the command line it does the right thing.

**Comment by kbergin** [comment]
@cmnbroad Can this ticket be closed given the issue exists in Barclay's backlog?

**Comment by cmnbroad** [comment]
This bug exists only in the legacy parser, but it should remain open until we resolve how to move forward with https://github.com/broadinstitute/picard/issues/1120.
