### ISSUE TITLE
GenotypeConcordance error when output_vcf

### ISSUE THREAD

**Issue by laurabuggiotti** [broadinstitute/picard#1083]
### Affected tool
_GenotypeConcordance_

### Affected version
- Latest public release version 2.17.3

### Description 
_I have a joint.vcf file of 40 samples (NGS) and i want to evaluate my callset by comparing it to a truth callset, which in this case is genotyping file of the same samples. When using the tool to output the three genotypes concordance tables it works fine, but when i add `OUTPUT_VCF=true`  it starts producing the vcf file but shortly after stops. Please find below the log info_

#### Steps to reproduce
```
13:37:35.569 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/users/lbuggiotti/picard_Jan2018/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Jan 17 13:37:35 GMT 2018] GenotypeConcordance TRUTH_VCF=Gen_40_snp150_refAllele_swcol_final_sort_noHom_bis_final.vcf CALL_VCF=all40_jointcalls_99.9-recalibrated.vcf OUTPUT=A1_gc_concordance_tris OUTPUT_VCF=true TRUTH_SAMPLE=A1 CALL_SAMPLE=A1 INTERVALS=[snp150.interval_list] MISSING_SITES_HOM_REF=true    INTERSECT_INTERVALS=true MIN_GQ=0 MIN_DP=0 OUTPUT_ALL_ROWS=false USE_VCF_INDEX=false IGNORE_FILTER_STATUS=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Jan 17 13:37:35 GMT 2018] Executing as lbuggiotti@node08.prv.rvchpc1.cluster on Linux 2.6.32-431.5.1.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_151-b12; Deflater: Intel; Inflater: Intel; Picard version: 2.17.3-SNAPSHOT
INFO    2018-01-17 13:37:35     GenotypeConcordance     Starting to load intervals list(s).
INFO    2018-01-17 13:37:35     GenotypeConcordance     Finished loading up intervals list(s).
INFO    2018-01-17 13:37:36     GenotypeConcordance     Starting iteration over variants.
[Wed Jan 17 13:37:38 GMT 2018] picard.vcf.GenotypeConcordance done. Elapsed time: 0.05 minutes.
Runtime.totalMemory()=3670540288
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 14376
        at htsjdk.samtools.BinningIndexBuilder.processFeature(BinningIndexBuilder.java:89)
        at htsjdk.tribble.index.tabix.TabixIndexCreator.finalizeFeature(TabixIndexCreator.java:106)
        at htsjdk.tribble.index.tabix.TabixIndexCreator.addFeature(TabixIndexCreator.java:92)
        at htsjdk.variant.variantcontext.writer.IndexingVariantContextWriter.add(IndexingVariantContextWriter.java:172)
        at htsjdk.variant.variantcontext.writer.VCFWriter.add(VCFWriter.java:221)
        at picard.vcf.GenotypeConcordance.writeVcfTuple(GenotypeConcordance.java:527)
        at picard.vcf.GenotypeConcordance.lambda$doWork$0(GenotypeConcordance.java:396)
        at java.util.Optional.ifPresent(Optional.java:159)
        at picard.vcf.GenotypeConcordance.doWork(GenotypeConcordance.java:396)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:269)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)
```

#### Expected behavior
_It should produce a vcf file with the concordance state (CONC_STATE) tag in the INFO field_

#### Actual behavior
_It starts to produce the vcf file but then stops and when checking the log i get the above error message. However, if I use the tool without outputting vcf (OUTPUT_VCF=false) file it works fine_

**Comment by laurabuggiotti** [comment]
Just wanted to inform that now it produces vcf files when OUTPUT_VCF=true. It was probably due to a malformed truth vcf file.

**Comment by yfarjoun** [comment]
thanks for circling back on this.
