### ISSUE TITLE
RevertSam breaks on non-paired input

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#1115]
### Affected tool(s)
RevertSam

### Description 
Seems to break on non-paired data. 

Exception in thread “main” java.lang.IllegalStateException: Inappropriate call if not paired read
    at htsjdk.samtools.SAMRecord.requireReadPaired(SAMRecord.java:890)
    at htsjdk.samtools.SAMRecord.getFirstOfPairFlag(SAMRecord.java:948)
    at picard.sam.RevertSam.sanitize(RevertSam.java:432)
    at picard.sam.RevertSam.doWork(RevertSam.java:326)
    at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:269)
    at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
    at edu.mit.broad.picard.cmdline.PicardPrivateCommandLine.main(PicardPrivateCommandLine.java:24)

I suspect that a `continue` in line picard/sam/RevertSam.java:431 will resolve the issue, but a test  should be written.

**Comment by denklewer** [comment]
does it already fixed here:
https://github.com/broadinstitute/picard/pull/1133 ?

**Comment by jleinenbach** [comment]
Yes, I ran into this issue and this commit fixed it for me.

**Comment by kbergin** [comment]
Fixed in #1133
