### ISSUE TITLE
picard viewsam <PG> <ID:> issue when bwa <CL:> contains the -R <@RG-string>

### ISSUE THREAD

**Issue by splaisan** [broadinstitute/picard#1139]
When we run BWA, we add the RG fiels by using the -R parameter as shown below. This is done in order to record the bwa parameters used for the run which can prove quite valuable.

The problem doing so is that the -R RG-string passed in the PG row of the BWA sam contains 2 apparent conflicting ID fields, one from the PG record itself **ID:bwa** and one from the RG string in the PG CL-field **ID:id**

`@PG	ID:bwa	PN:bwa	VN:0.7.15-r1140	CL:/opt/genepattern/patches/BWA/bwa-0.7.15/bwa mem -t 4 -A 1 -k 19 -r 1.5 -W 0 -w 100 -B 4 -O 6 -E 1 -L 5 -R @RG	ID:id	SM:sample	PL:ILLUMINA `

The only option I found to keep this running is to set picard stringency to **LENIENT**. It works but leaves more freedom for other issues to remain undetected.

Is there a way to adapt our -R <argument> in BWA so that the resulting string will not make picard mad? (quoting did not work in my hands).

Otherwise, could you ignore the CL field content in the picard validation code?

Below a simple example with picard viewsam and the header of the faulty input.

Thanks in advance,
Stephane

`
java -jar /opt/genepattern/patches/picard_2.10.10/picard.jar ViewSam INPUT=testgatk.sam RECORDS_ONLY=true  ALIGNMENT_STATUS=All PF_STATUS=All
12:10:58.556 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/genepattern/patches/picard_2.10.10/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Mar 21 12:10:58 CET 2018] ViewSam INPUT=testgatk.sam ALIGNMENT_STATUS=All PF_STATUS=All RECORDS_ONLY=true    HEADER_ONLY=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Mar 21 12:10:58 CET 2018] Executing as guy@biobase.bits on Linux 3.10.0-693.2.2.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_161-b14; Deflater: Intel; Inflater: Intel; Picard version: 2.10.10-SNAPSHOT
[Wed Mar 21 12:10:58 CET 2018] picard.sam.ViewSam done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=251658240
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMFormatException: Error parsing SAM header. Problem parsing @PG key:value pair ID:id clashes with ID:bwa. Line:
@PG     ID:bwa  PN:bwa  VN:0.7.15-r1140 CL:/opt/genepattern/patches/BWA/bwa-0.7.15/bwa mem -t 4 -A 1 -k 19 -r 1.5 -W 0 -w 100 -B 4 -O 6 -E 1 -L 5 -R @RG        ID:id        SM:sample       PL:ILLUMINA /opt/genepattern/users/.cache/uploads/cache/193.191.128.4/pub/bwa_index/Homo_sapiens.UCSC.hg38/Homo_sapiens.UCSC.hg38 /opt/genepattern/users/gbottu/uploads/shuffled_10pc_PE_NA18507_GAIIx_100_chr21_2_1.fq /opt/genepattern/users/gbottu/uploads/shuffled_10pc_PE_NA18507_GAIIx_100_chr21_2_2.fq; ; Line number 457
        at htsjdk.samtools.SAMTextHeaderCodec.reportErrorParsingLine(SAMTextHeaderCodec.java:265)
        at htsjdk.samtools.SAMTextHeaderCodec.access$200(SAMTextHeaderCodec.java:43)
        at htsjdk.samtools.SAMTextHeaderCodec$ParsedHeaderLine.<init>(SAMTextHeaderCodec.java:320)
        at htsjdk.samtools.SAMTextHeaderCodec.decode(SAMTextHeaderCodec.java:95)
        at htsjdk.samtools.SAMTextReader.readHeader(SAMTextReader.java:216)
        at htsjdk.samtools.SAMTextReader.<init>(SAMTextReader.java:63)
        at htsjdk.samtools.SAMTextReader.<init>(SAMTextReader.java:73)
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:404)
        at picard.sam.ViewSam.writeSamText(ViewSam.java:115)
        at picard.sam.ViewSam.doWork(ViewSam.java:95)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:96)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:106)
`

`
@SQ	SN:chr1	LN:248956422
...cut...
@SQ	SN:chrUn_KI270742v1	LN:186739
@SQ	SN:chrUn_GL000216v2	LN:176608
@SQ	SN:chrUn_GL000218v1	LN:161147
@SQ	SN:chrX	LN:156040895
@SQ	SN:chrY	LN:57227415
@SQ	SN:chrY_KI270740v1_random	LN:37240
@RG	ID:id	SM:sample	PL:ILLUMINA
@PG	ID:bwa	PN:bwa	VN:0.7.15-r1140	CL:/opt/genepattern/patches/BWA/bwa-0.7.15/bwa mem -t 4 -A 1 -k 19 -r 1.5 -W 0 -w 100 -B 4 -O 6 -E 1 -L 5 -R @RG	ID:id	SM:sample	PL:ILLUMINA /opt/genepattern/users/.cache/uploads/cache/193.191.128.4/pub/bwa_index/Homo_sapiens.UCSC.hg38/Homo_sapiens.UCSC.hg38 /opt/genepattern/users/gbottu/uploads/shuffled_10pc_PE_NA18507_GAIIx_100_chr21_2_1.fq /opt/genepattern/users/gbottu/uploads/shuffled_10pc_PE_NA18507_GAIIx_100_chr21_2_2.fq
EAS56_0199:2:35:1370:20818	83	chr21	17906925	60	100M	=	17906707	-318	CTGTAAAATGCCAAAAAAAAAAACAATCTAGAAAACATCCAAATTATTTTACTGTGAAATTTTGTTAAAATGAATATATTGCTGTAATCACATACCCTTA	#####CECB5BEEEGGGGEGGGEGEGEGDFDGFFEBGGFFGGGEGGFGDGGGCEG?GGGEGGFEDFGGGGGGGGFGGFEGGEGEGGGGGGFFF?FEFGGF	NM:i:0	MD:Z:100	AS:i:100	XS:i:20	RG:Z:id
EAS56_0199:2:35:1370:20818	163	chr21	17906707	60	100M	=	17906925	318	CAGCGAGACTCTGTCTCAAAAAAAAAAAATTTTTTTTTTATACTTCAATATCTTTATTGACATAAATGGATATTGTATAACGTCTGTTCTAGATGCAATC	GBGGAGGDGGDDFGGGGGGDEFGGGGGFFADADFFGCF>CAC=EBGGE=G=:AEEABFFFBEEGDDAEEE:DDAECCAEEAB:CBDC,5?:??<?=BB=@	NM:i:0	MD:Z:100	AS:i:100	XS:i:30	RG:Z:id
`

**Comment by splaisan** [comment]
I thing I found the 'bug' !

The CL:<string> contains tabs which were required for bwa to produce a valid @RG record but are making problem in the @PG line as they are interpreted as field separators while they are part of the CL:<string>.

Would it be possible to automatically replace any 'tab' present within CL:<strings> by space so that they do not get interpreted in as FS anymore?

**Comment by yfarjoun** [comment]
At what point should picard change the tabs to spaces, in your view? it seems to be BWA that is introducing these tabs...no?

I think that you should change your input to BWA so that it doesn't contain tabs. Perhaps using a simple `sed` command.

**Comment by splaisan** [comment]
Hi Yossi
You are right in that bwa is producing the string (as instructed). The aim is to generate a valid SAM data as required by Picard in the first place. To do so the bwa command with extra -R <full RG line here> in order to add this line in the SAM header as a @RG record. This implies that bwa NEEDs to use tabs to delimitate the fields.

Now comes the problem, bwa also records its full command in a @PG line and hence the tabs in the -R <text> included in that command.

I therefore cannot change bwa's behaviour without making an invalid @RG record but I will indeed ask the bwa developperS to remove tabs in the CL:<text> as they are best placed to do it.

Best
Stephane

**Comment by drtamermansour** [comment]
[https://github.com/samtools/htsjdk/issues/677](url)

**Comment by splaisan** [comment]
Thanks for this workaround. I would howecer prefer when tab replacement would be done internally to ease this for less experienxed users and comply to both samtooks and picard standards.
Best
