### ISSUE TITLE
MarkDuplicate crash

### ISSUE THREAD

**Issue by rizkg** [broadinstitute/picard#1148]
### Affected tool(s)
MarkDuplicate

### Affected version(s)
- [x ] Latest public release version [2.18.1]
- [ ] Latest development/master branch as of [date of test?]

### Description 
This seem to be a common error, already reported several years ago here https://www.biostars.org/p/60263/  and here #72
But since this still crashes and it is not clear to me how to solve this, I am reporting it again. The input bam file comes from bwa mem, then converted to bam and sorted with samtools, so it should be valid.

```
-bash-4.1$ java -jar -Djava.io.tmpdir=./tmp ~grizk/bin/picard.2.18.1.jar MarkDuplicates I=$aln_sorted_BAM O=$aln_sorted_dedup_BAM M=$dedupMetrics ASSUME_SORTED=true
16:41:32.707 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/symbiose/grizk/bin/picard.2.18.1.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Mar 30 16:41:32 CEST 2018] MarkDuplicates INPUT=[/WORKS/grizk/vc/raw_ch17.aln.sorted.bam] OUTPUT=/WORKS/grizk/vc/raw_ch17.aln.sorted.dedup.bam METRICS_FILE=/WORKS/grizk/vc/raw_ch17.dedupMetrics.txt ASSUME_SORTED=true    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag CLEAR_DT=true ADD_PG_TAG_TO_READS=true REMOVE_DUPLICATES=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Fri Mar 30 16:41:32 CEST 2018] Executing as grizk@cl1n028.genouest.org on Linux 2.6.32-431.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_102-b14; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.1-SNAPSHOT
INFO	2018-03-30 16:41:32	MarkDuplicates	Start of doWork freeMemory: 2038352320; totalMemory: 2058354688; maxMemory: 28631367680
INFO	2018-03-30 16:41:32	MarkDuplicates	Reading input file and constructing read end information.
INFO	2018-03-30 16:41:32	MarkDuplicates	Will retain up to 103736839 data points before spilling to disk.
WARNING	2018-03-30 16:41:34	AbstractOpticalDuplicateFinderCommandLineProgram	A field field parsed out of a read name was expected to contain an integer and did not. Read name: ERR174324.81165065. Cause: String 'ERR174324.81165065' did not start with a parsable number.

[Fri Mar 30 16:41:38 CEST 2018] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0,10 minutes.
Runtime.totalMemory()=2058354688
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Value was put into PairInfoMap more than once.  16: null:ERR174326.21638423
	at htsjdk.samtools.CoordinateSortedPairInfoMap.ensureSequenceLoaded(CoordinateSortedPairInfoMap.java:133)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.remove(CoordinateSortedPairInfoMap.java:86)
	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.remove(DiskBasedReadEndsForMarkDuplicatesMap.java:61)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:528)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:232)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)

```

#### Steps to reproduce
Command line 
`   java -jar -Djava.io.tmpdir=./tmp ~grizk/bin/picard.2.18.1.jar MarkDuplicates I=$aln_sorted_BAM O=$aln_sorted_dedup_BAM M=$dedupMetrics ASSUME_SORTED=true`

#### Expected behavior
It should not crash.

#### Actual behavior
It crashes

----

**Comment by yfarjoun** [comment]
Your read names (`ERR174324.81165065`) are not conformant to the expected "READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values>" , so optical duplicates cannot be identified. You can either:
1. fix your read names so that they are conformant, or
2. run with `READ_NAME_REGEX=null` to disable optical duplicate finding.

**Comment by rizkg** [comment]
Thanks, but unfortunately running with `READ_NAME_REGEX=null` does not solve the problem :
```
-bash-4.1$ java -jar -Djava.io.tmpdir=./tmp ~grizk/bin/picard.2.18.1.jar MarkDuplicates I=$aln_sorted_BAM O=$aln_sorted_dedup_BAM M=$dedupMetrics ASSUME_SORTED=true READ_NAME_REGEX=null
17:33:15.558 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/symbiose/grizk/bin/picard.2.18.1.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Mar 30 17:33:15 CEST 2018] MarkDuplicates INPUT=[/WORKS/grizk/vc/raw_ch17.aln.sorted.bam] OUTPUT=/WORKS/grizk/vc/raw_ch17.aln.sorted.dedup.bam METRICS_FILE=/WORKS/grizk/vc/raw_ch17.dedupMetrics.txt ASSUME_SORTED=true READ_NAME_REGEX=null    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag CLEAR_DT=true ADD_PG_TAG_TO_READS=true REMOVE_DUPLICATES=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Fri Mar 30 17:33:15 CEST 2018] Executing as grizk@cl1n028.genouest.org on Linux 2.6.32-431.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_102-b14; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.1-SNAPSHOT
INFO	2018-03-30 17:33:15	MarkDuplicates	Start of doWork freeMemory: 2038352328; totalMemory: 2058354688; maxMemory: 28631367680
INFO	2018-03-30 17:33:15	MarkDuplicates	Reading input file and constructing read end information.
INFO	2018-03-30 17:33:15	MarkDuplicates	Will retain up to 103736839 data points before spilling to disk.
[Fri Mar 30 17:33:22 CEST 2018] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0,12 minutes.
Runtime.totalMemory()=2058354688
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Value was put into PairInfoMap more than once.  16: null:ERR174326.21638423
	at htsjdk.samtools.CoordinateSortedPairInfoMap.ensureSequenceLoaded(CoordinateSortedPairInfoMap.java:133)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.remove(CoordinateSortedPairInfoMap.java:86)
	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.remove(DiskBasedReadEndsForMarkDuplicatesMap.java:61)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:528)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:232)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)
```

**Comment by rizkg** [comment]
Maybe there is some other issue in my read file, but I do not know what the requirement of MarkDuplicates are, if any.

**Comment by yfarjoun** [comment]
could you check that your file is "Valid"  (according to ValidateSamFile)? 

I suspect you might have the same read-name more than once in there...

also, could you grep for `ERR174326.21638423` in your bam file 

`samtools view <FILE> | grep "ERR174326.21638423"`

...and post the result here if it's not too big?

**Comment by rizkg** [comment]
Thank you very much for your help, I did have the same read name several times in my bam file.

As a suggestion, it would be nice to have a warning somewhere in the documentation that MarkDuplicates will crash if several reads have the same name in the bam. 
Or a more explicit message for the java exception than "Value was put into PairInfoMap more than once".

**Comment by yfarjoun** [comment]
great!

it's a bit difficult as that message is comming from htsjdk...but you are right that the message is rather cryptic.

**Comment by ASinghal988** [comment]
as-VirtualBox:~/RNAP$ java -jar MarkDuplicates.jar INPUT=hcc_tumor_cord.sam O=hccmarked_duplicates.bam M=hccmarked_dup_matrics.txt
[Tue Jul 10 13:14:41 PDT 2018] picard.sam.MarkDuplicates INPUT=[hcc_tumor_cord.sam] OUTPUT=hccmarked_duplicates.bam METRICS_FILE=hccmarked_dup_matrics.txt    PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates REMOVE_DUPLICATES=false ASSUME_SORTED=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Tue Jul 10 13:14:41 PDT 2018] Executing as as@as-VirtualBox on Linux 4.15.0-23-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11; Picard version: 1.119(d44cdb51745f5e8075c826430a39d8a61f1dd832_1408991805) JdkDeflater
INFO	2018-07-10 13:14:41	MarkDuplicates	Start of doWork freeMemory: 144048608; totalMemory: 146079744; maxMemory: 2317156352
INFO	2018-07-10 13:14:41	MarkDuplicates	Reading input file and constructing read end information.
INFO	2018-07-10 13:14:41	MarkDuplicates	Will retain up to 9195064 data points before spilling to disk.
[Tue Jul 10 13:14:46 PDT 2018] picard.sam.MarkDuplicates done. Elapsed time: 0.08 minutes.
Runtime.totalMemory()=1010741248
To get help, see http://picard.sourceforge.net/index.shtml#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Cannot add sequence that already exists in SAMSequenceDictionary: chr1-100154611-100154621-100154847-100154851-100178486-100178513
	at htsjdk.samtools.SAMSequenceDictionary.setSequences(SAMSequenceDictionary.java:68)
	at htsjdk.samtools.SAMSequenceDictionary.<init>(SAMSequenceDictionary.java:45)
	at htsjdk.samtools.SAMTextHeaderCodec.decode(SAMTextHeaderCodec.java:113)
	at htsjdk.samtools.SAMTextReader.readHeader(SAMTextReader.java:195)
	at htsjdk.samtools.SAMTextReader.<init>(SAMTextReader.java:62)
	at htsjdk.samtools.SAMTextReader.<init>(SAMTextReader.java:71)
	at htsjdk.samtools.SAMFileReader.init(SAMFileReader.java:703)
	at htsjdk.samtools.SAMFileReader.<init>(SAMFileReader.java:201)
	at htsjdk.samtools.SAMFileReader.<init>(SAMFileReader.java:156)
	at picard.sam.MarkDuplicates.openInputs(MarkDuplicates.java:365)
	at picard.sam.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:415)
	at picard.sam.MarkDuplicates.doWork(MarkDuplicates.java:177)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:183)
	at picard.sam.MarkDuplicates.main(MarkDuplicates.java:161)
can somebody help i am keep getting this error

**Comment by ASinghal988** [comment]
as-VirtualBox:~/RNAP$ java -jar MarkDuplicates.jar INPUT=hcc_tumor_cord.sam O=hccmarked_duplicates.bam M=hccmarked_dup_matrics.txt
[Tue Jul 10 13:14:41 PDT 2018] picard.sam.MarkDuplicates INPUT=[hcc_tumor_cord.sam] OUTPUT=hccmarked_duplicates.bam METRICS_FILE=hccmarked_dup_matrics.txt    PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates REMOVE_DUPLICATES=false ASSUME_SORTED=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Tue Jul 10 13:14:41 PDT 2018] Executing as as@as-VirtualBox on Linux 4.15.0-23-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11; Picard version: 1.119(d44cdb51745f5e8075c826430a39d8a61f1dd832_1408991805) JdkDeflater
INFO	2018-07-10 13:14:41	MarkDuplicates	Start of doWork freeMemory: 144048608; totalMemory: 146079744; maxMemory: 2317156352
INFO	2018-07-10 13:14:41	MarkDuplicates	Reading input file and constructing read end information.
INFO	2018-07-10 13:14:41	MarkDuplicates	Will retain up to 9195064 data points before spilling to disk.
[Tue Jul 10 13:14:46 PDT 2018] picard.sam.MarkDuplicates done. Elapsed time: 0.08 minutes.
Runtime.totalMemory()=1010741248
To get help, see http://picard.sourceforge.net/index.shtml#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Cannot add sequence that already exists in SAMSequenceDictionary: chr1-100154611-100154621-100154847-100154851-100178486-100178513
	at htsjdk.samtools.SAMSequenceDictionary.setSequences(SAMSequenceDictionary.java:68)
	at htsjdk.samtools.SAMSequenceDictionary.<init>(SAMSequenceDictionary.java:45)
	at htsjdk.samtools.SAMTextHeaderCodec.decode(SAMTextHeaderCodec.java:113)
	at htsjdk.samtools.SAMTextReader.readHeader(SAMTextReader.java:195)
	at htsjdk.samtools.SAMTextReader.<init>(SAMTextReader.java:62)
	at htsjdk.samtools.SAMTextReader.<init>(SAMTextReader.java:71)
	at htsjdk.samtools.SAMFileReader.init(SAMFileReader.java:703)
	at htsjdk.samtools.SAMFileReader.<init>(SAMFileReader.java:201)
	at htsjdk.samtools.SAMFileReader.<init>(SAMFileReader.java:156)
	at picard.sam.MarkDuplicates.openInputs(MarkDuplicates.java:365)
	at picard.sam.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:415)
	at picard.sam.MarkDuplicates.doWork(MarkDuplicates.java:177)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:183)
	at picard.sam.MarkDuplicates.main(MarkDuplicates.java:161)

**Comment by yfarjoun** [comment]
@ASinghal988 please do not hijack this issue. If you have a user issue (which you seem to be having) please seek support on the GATK forum. https://gatkforums.broadinstitute.org/gatk/categories/gatk-support-forum

**Comment by chzh1418** [comment]
> great!
> 
> it's a bit difficult as that message is comming from htsjdk...but you are right that the message is rather cryptic.

Hi, I also have the same read name several times in my bam file. How should I solve this problem?
Thanks,
Chi
