### ISSUE TITLE
not having a .dict file next to the .fasta reference causes java.lang.NullPointerException

### ISSUE THREAD

**Issue by bw2** [broadinstitute/picard#1157]
### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
LiftoverVCF

### Affected version(s)
- [ x ] Latest public release version [version?]
- [ x ] Latest development/master branch as of [date of test?] today

how do you get picard to print it's version?  Tried java -jar picard.jar --version, -h etc.

### Description 
Pointing to .fa file that doesn't have a .dict next to it causes

Exception in thread "main" java.lang.NullPointerException
	at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:271)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at edu.mit.broad.picard.cmdline.PicardPrivateCommandLine.main(PicardPrivateCommandLine.java:24)

If I add the .dict file, the exception goes away and the command runs as expected.

#### Steps to reproduce
```
mv hg38.fa.dict hg38.fa.dict.aside
java -Xmx50G -jar /seq/software/picard/current/bin/picard-private.jar LiftoverVcf R=hg38.fa C=hg19ToHg38.over.chain.removed_chr_prefix.gz I=temp.vcf.gz O=./temp.vcf.gz.liftover.b38.vcf.gz REJECT=./temp.vcf.gz.liftover.rejected.vcf.gz TMP_DIR=./tmp WARN_ON_MISSING_CONTIG=true WRITE_ORIGINAL_POSITION=true
```
Then, all that's needed to make the error go away: 
```
mv hg38.fa.dict.aside hg38.fa.dict
```

#### Actual behavior
```
Exception in thread "main" java.lang.NullPointerException
	at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:271)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at edu.mit.broad.picard.cmdline.PicardPrivateCommandLine.main(PicardPrivateCommandLine.java:24)
```

**Comment by kachulis** [comment]
@yfarjoun sure, will do

**Comment by lbergelson** [comment]
@yfarjoun This isn't a new issue from the recent fasta changes is it?

**Comment by lbergelson** [comment]
Never mind, it says right in the doc that the tool requires a dict.

**Comment by magicDGS** [comment]
This can be fixed by throwing an user error if dictionary is not present...
