### ISSUE TITLE
Error in creating a dict file

### ISSUE THREAD

**Issue by Addicted-to-coding** [broadinstitute/picard#1185]
Hi, when I try to create a .dict file using the command java -jar ../current/picard.jar CreateSequenceDictionary REFERENCE=~/reference.genome/chr19_new.fa OUTPUT=testdata/picard/fingerprint/reference.dict
I get the error
[Wed Jun 20 15:56:37 PDT 2018] picard.sam.CreateSequenceDictionary done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=506462208
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: /u/local/apps/picard-tools/2.13.2/testdata/picard/fingerprint/reference.dict already exists.  Delete this file and try again, or specify a different output file.
	at picard.sam.CreateSequenceDictionary.doWork(CreateSequenceDictionary.java:167)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)

**Comment by chandrans** [comment]
I will answer on the forum.

**Comment by nh13** [comment]
"Delete this file and try again, or specify a different output file."

**Comment by Addicted-to-coding** [comment]
I understand, but when I specify a different output file say a.dict, i get
the error
Runtime.totalMemory()=11534336
To get help, see
http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: File
/u/local/apps/picard-tools/2.13.2/a.dict not found at
picard.sam.CreateSequenceDictionary.doWork(CreateSequenceDictionary.java:186)at
picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)

Varuni Sarwal
Undergraduate researcher at Zarlab , http://zarlab.cs.ucla.edu/
Department of Computer Science
University of California, Los Angeles
Indian Institute of Technology
New Delhi
