### ISSUE TITLE
Special characters in the filenamename get converted to ASCII encoding, causing java.io.FileNotFoundException

### ISSUE THREAD

**Issue by nik9jovanovic** [broadinstitute/picard#1219]
### Affected tool(s)
_CollectVariantCallingMetrics INPUT=mini#1.vcf OUTPUT=a.txt DBSNP=mini.dbsnp.vcf_

### Affected version(s)
- [x] Latest public release version [2.18.11]

### Description 
_When the input VCF contains a # in the name of the file, the FIleNotFoundException will be thrown, and in the stack trace the # character is converted to it's URL encoding of %23. The same was tested with CollectAlignmentSummaryMetrics with no issues._

_Stack trace:
23:11:56.180 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Sat Aug 25 23:11:56 UTC 2018] CollectVariantCallingMetrics INPUT=mini#1.vcf OUTPUT=a.txt DBSNP=mini.dbsnp.vcf    GVCF_INPUT=false THREAD_COUNT=1 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Sat Aug 25 23:11:56 UTC 2018] Executing as root@c864d10dfdf8 on Linux 4.9.93-linuxkit-aufs amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_161-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.11-SNAPSHOT
INFO	2018-08-25 23:11:56	CollectVariantCallingMetrics	Loading dbSNP file ...
INFO	2018-08-25 23:11:56	CollectVariantCallingMetrics	Starting iteration of variants.
ERROR	2018-08-25 23:11:56	MultiThreadedChunkBased	Unexpected exception encountered in child thread.
htsjdk.tribble.TribbleException: Could not create an iterator from a feature reader.
	at htsjdk.variant.vcf.VCFFileReader.query(VCFFileReader.java:280)
	at picard.vcf.processor.VariantIteratorProducer$Threadsafe.iteratorForSegment(VariantIteratorProducer.java:187)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at picard.util.Iterators.lambda$atomicIteratorOf$0(Iterators.java:19)
	at picard.vcf.processor.VariantAccumulatorExecutor$MultiThreadedChunkBased$Worker.run(VariantAccumulatorExecutor.java:140)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /data/mini%231.vcf (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at htsjdk.samtools.seekablestream.SeekableFileStream.<init>(SeekableFileStream.java:47)
	at htsjdk.samtools.seekablestream.SeekableStreamFactory$DefaultSeekableStreamFactory.getStreamFor(SeekableStreamFactory.java:99)
	at htsjdk.tribble.TribbleIndexedFeatureReader.getSeekableStream(TribbleIndexedFeatureReader.java:189)
	at htsjdk.tribble.TribbleIndexedFeatureReader.access$000(TribbleIndexedFeatureReader.java:57)
	at htsjdk.tribble.TribbleIndexedFeatureReader$QueryIterator.<init>(TribbleIndexedFeatureReader.java:423)
	at htsjdk.tribble.TribbleIndexedFeatureReader.query(TribbleIndexedFeatureReader.java:297)
	at htsjdk.variant.vcf.VCFFileReader.query(VCFFileReader.java:278)
	... 10 more
[Sat Aug 25 23:11:56 UTC 2018] picard.vcf.CollectVariantCallingMetrics done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=197656576
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.vcf.processor.VariantAccumulatorExecutor$MultiThreadedChunkBased$MultiException: Children threads encountered exceptions:
Could not create an iterator from a feature reader.
	at picard.vcf.processor.VariantAccumulatorExecutor$MultiThreadedChunkBased.awaitCompletion(VariantAccumulatorExecutor.java:109)
	at picard.vcf.processor.VariantProcessor.process(VariantProcessor.java:94)
	at picard.vcf.CollectVariantCallingMetrics.doWork(CollectVariantCallingMetrics.java:124)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:277)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)_

#### Steps to reproduce
_Just rename the test mini.vcf file to mini#1.vcf and the accompanying index to mini#1.vcf.idx._

#### Expected behavior
_Reading the specified file instead of a different filename._

#### Actual behavior
_Execution tries to read mini%231.vcf instead of mini#1.vcf._

----

**Comment by nik9jovanovic** [comment]
This is probably related to the toUri function being used on the path in htsjdk's VCFFileReader class.
