### ISSUE TITLE
PR#1204 throws when a command line option value contains =

### ISSUE THREAD

**Issue by tbl3rd** [broadinstitute/picard#1225]
### Affected tool(s)
_CommandLineProgram_ when using the legacy Picard command line syntax

### Affected version(s)
- [x] Latest public release version [version?]
- [x] Latest development/master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

This affects users of the Picard command line parser.
Any argument of the form _KEY=VALUE_with_=_in_it_ will cause the syntax deprecation warning to throw

RuntimeException: Argument syntax conversion failed. Too many "=" separated tokens to translate: KEY=VALUE_with_=_in_it

#### Expected behavior
_CommandLineProgram_ should accept legacy option syntax with = in the value part.

#### Actual behavior
_CommandLineParser_ throws as described above.

**Comment by lbergelson** [comment]
Huh, it works fine for me:

```
build/install/picard/bin/picard SamToFastq INPUT=testdata/picard/sam/al=igned.sam FASTQ=out=.bam  SECOND_END_FASTQ=ou=t.sec=ond.end.bam VALIDATION_STRINGENCY=LENIENT
INFO	2018-09-11 18:00:55	SamToFastq

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    SamToFastq -INPUT testdata/picard/sam/al=igned.sam -FASTQ out=.bam -SECOND_END_FASTQ ou=t.sec=ond.end.bam -VALIDATION_STRINGENCY LENIENT
**********


18:00:56.151 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/louisb/Workspace/picard/build/install/picard/lib/gkl-0.8.5.jar!/com/intel/gkl/native/libgkl_compression.dylib
[Tue Sep 11 18:00:56 EDT 2018] SamToFastq INPUT=testdata/picard/sam/al=igned.sam FASTQ=out=.bam SECOND_END_FASTQ=ou=t.sec=ond.end.bam VALIDATION_STRINGENCY=LENIENT    OUTPUT_PER_RG=false COMPRESS_OUTPUTS_PER_RG=false RG_TAG=PU RE_REVERSE=true INTERLEAVE=false INCLUDE_NON_PF_READS=false CLIPPING_MIN_LENGTH=0 READ1_TRIM=0 READ2_TRIM=0 INCLUDE_NON_PRIMARY_ALIGNMENTS=false VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Sep 11 18:00:56 EDT 2018] Executing as louisb@WMD2A-31E on Mac OS X 10.13.6 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_172-b11; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.13-1-g03f373c-SNAPSHOT
[Tue Sep 11 18:00:56 EDT 2018] picard.sam.SamToFastq done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=257425408
```

**Comment by pshapiro4broad** [comment]
FWIW this is the failing case we saw in our test
```
SGE command issued: java -Dsamjdk.buffer_size=131072 -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx128m -jar /seq/locutus/meta/nightly/run/2018-09-10/picard/bin/picard-private.jar DownloadGenotypes TMP_DIR=/seq/pscratch1/e94fb30682e01716b5fdd59d884600e3708f929a_got\
c-jenkins-slave01.broadinstitute.org_devopsci/H5VLJCCXY/1 CREATE_INDEX=true SAMPLE_ALIAS=CDH329 REFERENCE_SEQUENCE=/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta HAPLOTYPE_MAP=/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembl\
y38.haplotype_database.txt GAP_HOST_AND_PORT=gapws.broadinstitute.org:8080 GAP_WS_PATH=/ws/project_management/get_genotypes BSP_HOST_AND_PORT=bsp.broadinstitute.org:8080 BSP_WS_PATH=/ws/bsp/sample/getexportedsamplesbyaliquot?export_destination=GAP GAP_SAMPLE_PARAME\
TER=sample_lsids CREDENTIALS_VAULT_PATH=secret/dsde/gotc/prod/gap_bsp/login OUTPUT=/seq/locutus/meta/nightly/run/2018-09-10/data/non-hapmap/RP-1370/Homo_sapiens_assembly38/CDH329.vcf SAMPLE_LSID=broadinstitute.org:bsp.prod.sample:GN2ZB
Exception in thread "main" java.lang.RuntimeException: Argument syntax conversion failed. Too many "=" separated tokens to translate: BSP_WS_PATH=/ws/bsp/sample/getexportedsamplesbyaliquot?export_destination=GAP
    at picard.cmdline.CommandLineSyntaxTranslater.lambda$translatePicardStyleToPosixStyle$1(CommandLineSyntaxTranslater.java:40)
    at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at picard.cmdline.CommandLineSyntaxTranslater.translatePicardStyleToPosixStyle(CommandLineSyntaxTranslater.java:44)
    at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
    at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
    at edu.mit.broad.picard.cmdline.PicardPrivateCommandLine.main(PicardPrivateCommandLine.java:24)
```

**Comment by pshapiro4broad** [comment]
@lbergelson When I run your command I get the same error as in our case, maybe you're not running the latest picard?

**Comment by lbergelson** [comment]
I think @tbl3rd put in a fix before I actually did my test and I ran with his fix without realizing it.  It looks like https://github.com/broadinstitute/picard/pull/1226 should have closed this issue.

**Comment by tbl3rd** [comment]
Thanks @lbergelson.

**Comment by lbergelson** [comment]
Sorry for the confusion!
