### ISSUE TITLE
Error: Inappropriate call if not paired read when giving reference genome

### ISSUE THREAD

**Issue by npklein** [broadinstitute/picard#1279]
### Affected tool(s)
CollectMultipleMetrics

### Affected version(s)
- 2.10.0
- 2.18.26

### Description 
When running CollectMultipleMetrics on Single-end aligned reads I get the error `Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read` (full command + stacktrace at bottom), but I do not get this error when I do not include a reference genome (`R=GRCh38.p5.genome.fa`). 

If I run it through SAMtools and then do picard it does work. e.g. with `samtools view -h example_before.bam | samtools view -hb > example_after.bam`, `example_before.bam` before does give the error, `example_after.bam` does not, with for the the command being the same.

Additionally, I ran CollectRnaSeqMetrics on the same BAM file and included the same reference file, and there it does work.

#### Steps to reproduce
I can't get it reproducible. When I make a smaller file through samtools I don't get the error anymore (see description), and can not upload the complete file.

#### Expected behavior
CollectMultipleMetrics runs without an error.

#### Actual behavior
CollectMultipleMetrics throws the error `Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read`.

#### Full stacktrace
```
java -jar /apps/software/picard/2.18.26-Java-1.8.0_74/picard.jar CollectMultipleMetrics \
>     I=example.bam \
>     O=example.multiplemetrics \
>     R=/apps/data//ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_24/GRCh38.p5.genome.fa \
>     PROGRAM=CollectAlignmentSummaryMetrics
INFO	2019-02-12 10:29:19	CollectMultipleMetrics

10:29:21.575 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/apps/software/picard/2.18.26-Java-1.8.0_74/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue Feb 12 10:29:21 CET 2019] CollectMultipleMetrics INPUT=example.bam OUTPUT=example.multiplemetrics PROGRAM=[CollectAlignmentSummaryMetrics, CollectBaseDistributionByCycle, CollectInsertSizeMetrics, MeanQualityByCycle, QualityScoreDistribution] REFERENCE_SEQUENCE=/apps/data/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_24/GRCh38.p5.genome.fa    ASSUME_SORTED=true STOP_AFTER=0 METRIC_ACCUMULATION_LEVEL=[ALL_READS] INCLUDE_UNPAIRED=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Feb 12 10:29:21 CET 2019] Executing as umcg-ndeklein@boxy on Linux 2.6.32-696.10.2.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_74-b02; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.26-SNAPSHOT
[Tue Feb 12 10:29:21 CET 2019] picard.analysis.CollectMultipleMetrics done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2058354688
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read
        at htsjdk.samtools.SAMRecord.requireReadPaired(SAMRecord.java:887)
        at htsjdk.samtools.SAMRecord.getProperPairFlag(SAMRecord.java:895)
        at picard.analysis.AlignmentSummaryMetricsCollector$GroupAlignmentSummaryMetricsPerUnitMetricCollector$IndividualAlignmentSummaryMetricsCollector.collectReadData(AlignmentSummaryMetricsCollector.java:243)
        at picard.analysis.AlignmentSummaryMetricsCollector$GroupAlignmentSummaryMetricsPerUnitMetricCollector$IndividualAlignmentSummaryMetricsCollector.addRecord(AlignmentSummaryMetricsCollector.java:186)
        at picard.analysis.AlignmentSummaryMetricsCollector$GroupAlignmentSummaryMetricsPerUnitMetricCollector.acceptRecord(AlignmentSummaryMetricsCollector.java:119)
        at picard.analysis.AlignmentSummaryMetricsCollector$GroupAlignmentSummaryMetricsPerUnitMetricCollector.acceptRecord(AlignmentSummaryMetricsCollector.java:87)
        at picard.metrics.MultiLevelCollector$AllReadsDistributor.acceptRecord(MultiLevelCollector.java:192)
        at picard.metrics.MultiLevelCollector.acceptRecord(MultiLevelCollector.java:315)
        at picard.analysis.AlignmentSummaryMetricsCollector.acceptRecord(AlignmentSummaryMetricsCollector.java:83)
        at picard.analysis.CollectAlignmentSummaryMetrics.acceptRead(CollectAlignmentSummaryMetrics.java:147)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:138)
        at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:424)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)

```

#### But works when not including reference genome
```
java -jar /apps/software/picard/2.18.26-Java-1.8.0_74/picard.jar CollectMultipleMetrics \
>     I=example.bam \
>     O=example.multiplemetrics \
>     PROGRAM=CollectAlignmentSummaryMetrics
INFO	2019-02-12 10:29:45	CollectMultipleMetrics
10:29:45.500 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/apps/software/picard/2.18.26-Java-1.8.0_74/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue Feb 12 10:29:45 CET 2019] CollectMultipleMetrics INPUT=example.bam OUTPUT=example.multiplemetrics PROGRAM=[CollectAlignmentSummaryMetrics, CollectBaseDistributionByCycle, CollectInsertSizeMetrics, MeanQualityByCycle, QualityScoreDistribution]    ASSUME_SORTED=true STOP_AFTER=0 METRIC_ACCUMULATION_LEVEL=[ALL_READS] INCLUDE_UNPAIRED=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Feb 12 10:29:45 CET 2019] Executing as umcg-ndeklein@boxy on Linux 2.6.32-696.10.2.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_74-b02; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.26-SNAPSHOT
INFO	2019-02-12 10:29:45	RExecutor	Executing R script via command: Rscript /tmp/umcg-ndeklein/script5019838287937484690.R /groups/umcg-biogen/tmp03/tmp/example.multiplemetrics.base_distribution_by_cycle_metrics /groups/umcg-biogen/tmp03/tmp/example.multiplemetrics.base_distribution_by_cycle.pdf example.bam
INFO	2019-02-12 10:29:46	ProcessExecutor	null device
INFO	2019-02-12 10:29:46	ProcessExecutor	          1
WARNING	2019-02-12 10:29:46	CollectInsertSizeMetrics	All data categories were discarded because they contained < 0.05 of the total aligned paired data.
WARNING	2019-02-12 10:29:46	CollectInsertSizeMetrics	Total mapped pairs in all categories: 0.0
INFO	2019-02-12 10:29:46	RExecutor	Executing R script via command: Rscript /tmp/umcg-ndeklein/script2498918897501120896.R /groups/umcg-biogen/tmp03/tmp/example.multiplemetrics.quality_by_cycle_metrics /groups/umcg-biogen/tmp03/tmp/example.multiplemetrics.quality_by_cycle.pdf example.bam
INFO	2019-02-12 10:29:46	ProcessExecutor	null device
INFO	2019-02-12 10:29:46	ProcessExecutor	          1
INFO	2019-02-12 10:29:46	RExecutor	Executing R script via command: Rscript /tmp/umcg-ndeklein/script6107761226702409011.R /groups/umcg-biogen/tmp03/tmp/example.multiplemetrics.quality_distribution_metrics /groups/umcg-biogen/tmp03/tmp/example.multiplemetrics.quality_distribution.pdf example.bam
INFO	2019-02-12 10:29:47	ProcessExecutor	null device
INFO	2019-02-12 10:29:47	ProcessExecutor	          1
[Tue Feb 12 10:29:47 CET 2019] picard.analysis.CollectMultipleMetrics done. Elapsed time: 0.04 minutes.
Runtime.totalMemory()=2058354688
```

**Comment by npklein** [comment]
Sorry, I thought I was testing with 2.18.26 but was still runningn on 2.10.0, in 2.18.26 I don't have the error.
