### ISSUE TITLE
Liftover gVCFs with indels

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#1280]
I think that LiftoverVcf isn't working with a gVCF and indel allele in a reference block when trying to left-align indels.

Changing this line to catch if `a.length == 0`  gets me farther (back to this issue https://github.com/broadinstitute/picard/issues/1258):
https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/util/LiftoverUtils.java#L370

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
    at picard.util.LiftoverUtils.lambda$leftAlignVariant$3(LiftoverUtils.java:370)
    at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:907)
    at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
    at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at picard.util.LiftoverUtils.leftAlignVariant(LiftoverUtils.java:370)
    at picard.util.LiftoverUtils.reverseComplementVariantContext(LiftoverUtils.java:172)
    at picard.util.LiftoverUtils.liftVariant(LiftoverUtils.java:81)
    at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:396)
    at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
    at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
    at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

**Comment by yfarjoun** [comment]
a.length() should never be zero...hmmm.

**Comment by tfenne** [comment]
How long is a symbolic allele (e.g. `<NON_REF>`)?

**Comment by yfarjoun** [comment]
zero. 

I think that a VC with symbolic alleles should not be left-aligned...so a simple fix would be adding a check at the top of the left-align function and returning the input VC if it contains any symbolic alleles.

**Comment by AlbertoMaillo** [comment]
Hi to all,

I am doing "lift over" from hg19 vcf to hg38 vcf. I use the chain file, obtained from: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain
I have the same error and I have used the last version of picard(2.20.1). Someone could solve the problem?

***Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at picard.util.LiftoverUtils.lambda$leftAlignVariant$3(LiftoverUtils.java:370)****

Thanks!

**Comment by nh13** [comment]
@yfarjoun here's a single variant test case.

```bash
	picard -Xmx8g LiftoverVcf \
		RECOVER_SWAPPED_REF_ALT=true \
		MAX_RECORDS_IN_RAM=50000 \
		I=test.g.vcf.gz \
		C=hg38ToHg19.chain.gz \
		O=output.g.vcf.gz \
		REJECT=rejects.g.vcf.gz \
		R=/path/to/hg19.fasta
```
* hg19.fastsa` (omitted)
* [hg38ToHg19.chain.gz](https://github.com/broadinstitute/picard/files/4220641/hg38ToHg19.chain.gz)
* [test.g.vcf.gz](https://github.com/broadinstitute/picard/files/4220630/test.g.vcf.gz)

Log for ` Picard version: 2.21.4-SNAPSHOT`:
```bash
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at picard.util.LiftoverUtils.lambda$leftAlignVariant$4(LiftoverUtils.java:379)
	at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:907)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at picard.util.LiftoverUtils.leftAlignVariant(LiftoverUtils.java:379)
	at picard.util.LiftoverUtils.reverseComplementVariantContext(LiftoverUtils.java:178)
	at picard.util.LiftoverUtils.liftVariant(LiftoverUtils.java:76)
	at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:426)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

Log for `Picard version: 2.21.8-1-gc5cd747-SNAPSHOT`:
```bash
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at picard.util.LiftoverUtils.lambda$leftAlignVariant$4(LiftoverUtils.java:379)
	at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:907)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at picard.util.LiftoverUtils.leftAlignVariant(LiftoverUtils.java:379)
	at picard.util.LiftoverUtils.reverseComplementVariantContext(LiftoverUtils.java:178)
	at picard.util.LiftoverUtils.liftVariant(LiftoverUtils.java:76)
	at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:426)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

**Comment by yfarjoun** [comment]
thanks for the test case @nh13 

makes it much easier to debug!

**Comment by nh13** [comment]
@yfarjoun I was testing the Broad high-coverage PCR free 1KG sample GVCFs, in case you wanted to run it on those.  You may have access ;)

**Comment by nh13** [comment]
@yfarjoun you fixed the simple test case (https://github.com/broadinstitute/picard/pull/1469#issuecomment-587804812)

I am running on all the gVCFs I mentioned above to see if I can find additional exceptions.

**Comment by yfarjoun** [comment]
thanks @nh13
