### ISSUE TITLE
CollectRnaSeqMetrics doesnt load genes with UCSC refFlat/ custom refFlat maxes out RAM

### ISSUE THREAD

**Issue by j-berg** [broadinstitute/picard#1301]
When I use CollectRnaSeqMetrics, I download the refFlat for hg38 from UCSC (http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/.refFlat.txt.gz). When I use this file in the module, it shows the following output (notice that it states ```loaded 0 genes```).

```
15:56:53.769 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/uufs/chpc.utah.edu/common/home/u0690617/anaconda3/share/picard-2.18.27-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Mar 20 15:56:53 MDT 2019] CollectRnaSeqMetrics REF_FLAT=../references/human_reference/transcripts_refFlat.txt STRAND_SPECIFICITY=NONE MINIMUM_LENGTH=18 INPUT=test_sort.bam OUTPUT=test_metrics    RRNA_FRAGMENT_PERCENTAGE=0.8 METRIC_ACCUMULATION_LEVEL=[ALL_READS] ASSUME_SORTED=true STOP_AFTER=0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Mar 20 15:56:53 MDT 2019] Executing as u0690617@kingspeak1 on Linux 3.10.0-957.1.3.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_92-b15; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.27-SNAPSHOT
INFO	2019-03-20 15:56:54	CollectRnaSeqMetrics	Loaded 0 genes.
INFO	2019-03-20 15:56:58	SinglePassSamProgram	Processed     1,000,000 records.  Elapsed time: 00:00:04s.  Time for last 1,000,000:    4s.  Last read position: 12:89,603,825
INFO	2019-03-20 15:57:00	SinglePassSamProgram	Processed     2,000,000 records.  Elapsed time: 00:00:06s.  Time for last 1,000,000:    2s.  Last read position: 19:12,800,970
INFO	2019-03-20 15:57:03	SinglePassSamProgram	Processed     3,000,000 records.  Elapsed time: 00:00:08s.  Time for last 1,000,000:    2s.  Last read position: 5:32,061,055
INFO	2019-03-20 15:57:05	SinglePassSamProgram	Processed     4,000,000 records.  Elapsed time: 00:00:11s.  Time for last 1,000,000:    2s.  Last read position: MT:909
INFO	2019-03-20 15:57:07	SinglePassSamProgram	Processed     5,000,000 records.  Elapsed time: 00:00:13s.  Time for last 1,000,000:    2s.  Last read position: MT:3,141
[Wed Mar 20 15:57:09 MDT 2019] picard.analysis.CollectRnaSeqMetrics done. Elapsed time: 0.26 minutes.
Runtime.totalMemory()=604504064
```

When I look at the output, the file is essentially empty

```
## htsjdk.samtools.metrics.StringHeader
# CollectRnaSeqMetrics REF_FLAT=../references/human_reference/transcripts_refFlat.txt STRAND_SPECIFICITY=NONE MINIMUM_LENGTH=18 INPUT=test_sort.bam OUTPUT=test_metrics    RRNA_FRAGMENT_PERCENTAGE=0.8 METRIC_ACCUMULATION_LEVEL=[ALL_READS] ASSUME_SORTED=true STOP_AFTER=0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
## htsjdk.samtools.metrics.StringHeader
# Started on: Wed Mar 20 15:56:53 MDT 2019

## METRICS CLASS	picard.analysis.RnaSeqMetrics
PF_BASES	PF_ALIGNED_BASES	RIBOSOMAL_BASES	CODING_BASES	UTR_BASES	INTRONIC_BASES	INTERGENIC_BASES	IGNORED_READS	CORRECT_STRAND_READS	INCORRECT_STRAND_READS	NUM_R1_TRANSCRIPT_STRAND_READS	NUM_R2_TRANSCRIPT_STRAND_READS	NUM_UNEXPLAINED_READS	PCT_R1_TRANSCRIPT_STRAND_READS	PCT_R2_TRANSCRIPT_STRAND_READS	PCT_RIBOSOMAL_BASES	PCT_CODING_BASES	PCT_UTR_BASES	PCT_INTRONIC_BASES	PCT_INTERGENIC_BASES	PCT_MRNA_BASES	PCT_USABLE_BASES	PCT_CORRECT_STRAND_READS	MEDIAN_CV_COVERAGE	MEDIAN_5PRIME_BIAS	MEDIAN_3PRIME_BIAS	MEDIAN_5PRIME_TO_3PRIME_BIAS	SAMPLE	LIBRARY	READ_GROUP
159018665	156270825		0	0	0	156270825	0	0	0	0	0	0	0	0		0	0	0	1	0

```

I have also tried creating my own refFlat file using UCSC's gtfToGenePred with a GTF from Ensembl -- when I do this, it appears to load the genes, but it then gives me the following where the genes are loaded (```Loaded 202345 genes.```) but then I get a ```Exception in thread "main" java.lang.OutOfMemoryError: Java heap space``` error.

```
14:47:23.020 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/uufs/chpc.utah.edu/common/home/u0690617/anaconda3/share/picard-2.18.27-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Mar 20 14:47:23 MDT 2019] CollectRnaSeqMetrics REF_FLAT=../references/human_reference/transcripts_refFlat.txt STRAND_SPECIFICITY=NONE MINIMUM_LENGTH=18 INPUT=./test_remove.bam OUTPUT=./test_metrics    RRNA_FRAGMENT_PERCENTAGE=0.8 METRIC_ACCUMULATION_LEVEL=[ALL_READS] ASSUME_SORTED=true STOP_AFTER=0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Mar 20 14:47:23 MDT 2019] Executing as u0690617@kingspeak1 on Linux 3.10.0-957.1.3.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_92-b15; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.27-SNAPSHOT
INFO	2019-03-20 14:47:25	CollectRnaSeqMetrics	Loaded 202345 genes.
INFO	2019-03-20 14:47:35	SinglePassSamProgram	Processed     1,000,000 records.  Elapsed time: 00:00:09s.  Time for last 1,000,000:    9s.  Last read position: 2:43,231,309
[Wed Mar 20 14:47:46 MDT 2019] picard.analysis.CollectRnaSeqMetrics done. Elapsed time: 0.39 minutes.
Runtime.totalMemory()=954728448
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at picard.analysis.directed.RnaSeqMetricsCollector$PerUnitRnaSeqMetricsCollector.acceptRecord(RnaSeqMetricsCollector.java:196)
	at picard.analysis.directed.RnaSeqMetricsCollector$PerUnitRnaSeqMetricsCollector.acceptRecord(RnaSeqMetricsCollector.java:98)
	at picard.metrics.MultiLevelCollector$AllReadsDistributor.acceptRecord(MultiLevelCollector.java:192)
	at picard.metrics.MultiLevelCollector.acceptRecord(MultiLevelCollector.java:315)
	at picard.analysis.CollectRnaSeqMetrics.acceptRead(CollectRnaSeqMetrics.java:183)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:145)
	at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:84)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

I have played around with the ```MAX_RECORDS_IN_RAM``` a bunch and nothing appears to solve this issue. I have also used coordinate sorted SAM and BAM files with the same result. This issue seems to be dependent on the refFlat file size and not BAM/SAM file size (all are under 1 Gb in size) as I do not run into this issue when I use a Chr19-only refFlat file that I created with the UCSC tool.

----

### Affected tool(s)
Picard,CollectRnaSeqMetricsq

### Affected version(s)
- 2.18.27 (installed via bioconda)

### Description 
See description above

#### Steps to reproduce
See above code blocks

#### Expected behavior
Expect the software to load in genes and be able to handle a relatively small BAM file. Expect output metagene stats per sample.

#### Actual behavior
See above code blocks

**Comment by yfarjoun** [comment]
have you tried giving it more memory?
