### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: net/sf/samtools/SAMFileReader

### ISSUE THREAD

**Issue by mictadlo** [broadinstitute/picard#1310]
Hi, 
I tried to run [SGSGeneLoss](http://www.appliedbioinformatics.com.au/index.php/SGSGeneLoss) but I got `Exception in thread "main" java.lang.NoClassDefFoundError: net/sf/samtools/SAMFileReader`

```
/work/waterhouse_team/apps> wget -c http://appliedbioinformatics.com.au/download/SGSGeneLoss.v0.1.tar.gz
/work/waterhouse_team/apps> tar xvfz SGSGeneLoss.v0.1.tar.gz
/work/waterhouse_team/apps/SGSGeneLossv0.1> wget -c https://github.com/broadinstitute/picard/releases/download/2.19.0/picard.jar
/work/waterhouse_team/apps/SGSGeneLossv0.1> export CLASSPATH=/work/waterhouse_team/apps/SGSGeneLossv0.1/SGSGeneLoss.v0.1.jar:/work/waterhouse_team/apps/SGSGeneLossv0.1/picard.jar
/work/waterhouse_team/apps/SGSGeneLossv0.1> java -jar SGSGeneLoss.v0.1.jar help
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: net/sf/samtools/SAMFileReader
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: net.sf.samtools.SAMFileReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```
What did I miss?

Thank you in advance

Michal

**Comment by yfarjoun** [comment]
SAMFileReader was part of htsjdk but was @deprecated for a long time and deleted in 2016 in this PR: https://github.com/samtools/htsjdk/pull/699 .

It's replacement is htsjdk.samtools.SamReader.
