### ISSUE TITLE
CollectMultipleMetrics performs Percent-encoding of paths, breaks with Cromwell packed CWL workflows

### ISSUE THREAD

**Issue by jeremiahsavage** [broadinstitute/picard#1327]
## Bug Report

CollectMultipleMetrics performs Percent-encoding of input paths. When running this tool as a step of a packed CWL workflow with Cromwell, this causes a `No such file or directory` error.

The input file
```
/cromwell-executions/transform_pack.cwl#main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/inputs/-733038737/dbsnp_144.hg38.vcf.gz
```
becomes
```
file:///cromwell-executions/transform_pack.cwl%23main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/inputs/-733038737/dbsnp_144.hg38.vcf.gz
```
and can note be found.
### Affected tool(s)
CollectMultipleMetrics

### Affected version(s)
2.20.0

#### Expected behavior
The tool should collect metrics without error.

#### Actual behavior
```
[2019-05-08 21:34:48,10] [error] WorkflowManagerActor Workflow 0cd8a732-b482-4b8e-ba6e-34d244620ded failed (during ExecutingWorkflowState): Job main.picard_collectmultiplemetrics:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /mnt/scratch/fail/cromwell-executions/transform_pack.cwl#main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/execution/stderr.
 Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell-executions/transform_pack.cwl#main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/tmp.86c0d6fd
INFO	2019-05-08 21:33:07	CollectMultipleMetrics	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    CollectMultipleMetrics -METRIC_ACCUMULATION_LEVEL ALL_READS -PROGRAM CollectAlignmentSummaryMetrics -METRIC_ACCUMULATION_LEVEL LIBRARY -PROGRAM CollectBaseDistributionByCycle -METRIC_ACCUMULATION_LEVEL SAMPLE -PROGRAM CollectGcBiasMetrics -METRIC_ACCUMULATION_LEVEL READ_GROUP -PROGRAM CollectInsertSizeMetrics -PROGRAM CollectQualityYieldMetrics -PROGRAM CollectSequencingArtifactMetrics -PROGRAM MeanQualityByCycle -PROGRAM QualityScoreDistribution -OUTPUT A68634_2_lanes_dupsFlagged_gdc_realn -DB_SNP /cromwell-executions/transform_pack.cwl#main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/inputs/-733038737/dbsnp_144.hg38.vcf.gz -INPUT /cromwell-executions/transform_pack.cwl#main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/inputs/2058768463/A68634_2_lanes_dupsFlagged_gdc_realn.bam -REFERENCE_SEQUENCE /cromwell-executions/transform_pack.cwl#main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/inputs/-733038737/GRCh38.d1.vd1.fa -TMP_DIR . -VALIDATION_STRINGENCY STRICT
**********


21:33:08.413 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/bin/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed May 08 21:33:08 UTC 2019] CollectMultipleMetrics INPUT=/cromwell-executions/transform_pack.cwl#main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/inputs/2058768463/A68634_2_lanes_dupsFlagged_gdc_realn.bam OUTPUT=A68634_2_lanes_dupsFlagged_gdc_realn METRIC_ACCUMULATION_LEVEL=[ALL_READS, SAMPLE, READ_GROUP, LIBRARY] PROGRAM=[CollectAlignmentSummaryMetrics, CollectBaseDistributionByCycle, CollectInsertSizeMetrics, MeanQualityByCycle, QualityScoreDistribution, CollectGcBiasMetrics, CollectQualityYieldMetrics, CollectSequencingArtifactMetrics] DB_SNP=/cromwell-executions/transform_pack.cwl#main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/inputs/-733038737/dbsnp_144.hg38.vcf.gz TMP_DIR=[.] VALIDATION_STRINGENCY=STRICT REFERENCE_SEQUENCE=/cromwell-executions/transform_pack.cwl#main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/inputs/-733038737/GRCh38.d1.vd1.fa    ASSUME_SORTED=true STOP_AFTER=0 INCLUDE_UNPAIRED=false VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed May 08 21:33:08 UTC 2019] Executing as root@7e61144abe5d on Linux 4.15.0-48-generic amd64; OpenJDK 64-Bit Server VM 11.0.2+9-Ubuntu-3ubuntu118.04.3; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.0-SNAPSHOT
WARNING	2019-05-08 21:33:08	CollectMultipleMetrics	The CollectBaseDistributionByCycle program does not support a metric accumulation level, but METRIC_ACCUMULATION_LEVEL was overridden in the command line. CollectBaseDistributionByCycle will be run against the entire input.
WARNING	2019-05-08 21:33:08	CollectMultipleMetrics	The MeanQualityByCycle program does not support a metric accumulation level, but METRIC_ACCUMULATION_LEVEL was overridden in the command line. MeanQualityByCycle will be run against the entire input.
WARNING	2019-05-08 21:33:08	CollectMultipleMetrics	The QualityScoreDistribution program does not support a metric accumulation level, but METRIC_ACCUMULATION_LEVEL was overridden in the command line. QualityScoreDistribution will be run against the entire input.
WARNING	2019-05-08 21:33:08	CollectMultipleMetrics	The CollectQualityYieldMetrics program does not support a metric accumulation level, but METRIC_ACCUMULATION_LEVEL was overridden in the command line. CollectQualityYieldMetrics will be run against the entire input.
WARNING	2019-05-08 21:33:08	CollectMultipleMetrics	The CollectSequencingArtifactMetrics program does not support a metric accumulation level, but METRIC_ACCUMULATION_LEVEL was overridden in the command line. CollectSequencingArtifactMetrics will be run against the entire input.
WARNING: BAM index file /cromwell-executions/transform_pack.cwl#main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/inputs/2058768463/A68634_2_lanes_dupsFlagged_gdc_realn.bai is older than BAM /cromwell-executions/transform_pack.cwl#main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/inputs/2058768463/A68634_2_lanes_dupsFlagged_gdc_realn.bam
[Wed May 08 21:34:36 UTC 2019] picard.analysis.CollectMultipleMetrics done. Elapsed time: 1.47 minutes.
Runtime.totalMemory()=2147483648
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to create BasicFeatureReader using feature file , for input source: file:///cromwell-executions/transform_pack.cwl%23main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/inputs/-733038737/dbsnp_144.hg38.vcf.gz
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:123)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:80)
	at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:140)
	at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:92)
	at picard.util.DbSnpBitSetUtil.loadVcf(DbSnpBitSetUtil.java:143)
	at picard.util.DbSnpBitSetUtil.<init>(DbSnpBitSetUtil.java:99)
	at picard.analysis.artifacts.CollectSequencingArtifactMetrics.setup(CollectSequencingArtifactMetrics.java:213)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:129)
	at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:563)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
Caused by: java.io.FileNotFoundException: /cromwell-executions/transform_pack.cwl%23main/0cd8a732-b482-4b8e-ba6e-34d244620ded/call-picard_collectmultiplemetrics/inputs/-733038737/dbsnp_144.hg38.vcf.gz (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at htsjdk.samtools.seekablestream.SeekableFileStream.<init>(SeekableFileStream.java:47)
	at htsjdk.samtools.seekablestream.SeekableStreamFactory$DefaultSeekableStreamFactory.getStreamFor(SeekableStreamFactory.java:99)
	at htsjdk.tribble.readers.TabixReader.<init>(TabixReader.java:129)
	at htsjdk.tribble.TabixFeatureReader.<init>(TabixFeatureReader.java:80)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:116)
	... 11 more

[2019-05-08 21:34:48,10] [info] WorkflowManagerActor WorkflowActor-0cd8a732-b482-4b8e-ba6e-34d244620ded is in a terminal state: WorkflowFailedState
```

**Comment by cmnbroad** [comment]
This is likely to be an issue with all Picard tools when used with input paths that contain embedded characters that require URL encoding, such as "#" or " ". GATK (and htsjdk-next) use a PathSpecifier class that handles these issues, as well as URI/URL inputs. We should consider starting to migrate Picard to a simplified variant of that class along with `java.io.Path`, and eliminating references to `java.io.File`.
