### ISSUE TITLE
Bug report: FilterSamReads - Second record is not marked as second of pair

### ISSUE THREAD

**Issue by guillermomarco** [broadinstitute/picard#1334]
### Affected tool(s)
FilterSamReads

### Affected version(s)
Got error on both 2.20.0 & 2.20.1

### Description 
I'm trying to filter a bwa mem aligment bam.

```
java -Xms1g -Xmx4g -jar /share/apps/local/picard-tools/picard-tools-2.20.1/picard.jar FilterSamReads FILTER=includeAligned I=bwa_mem_SM000000_gmarco_1_L007_rawdata_001_qn.bam O=bwa_mem_SM000000_gmarco_1_L007_rawdata_001_qn_aligned.bam
INFO	2019-05-22 08:47:21	FilterSamReads	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    FilterSamReads -FILTER includeAligned -I bwa_mem_SM000000_gmarco_1_L007_rawdata_001_qn.bam -O bwa_mem_SM000000_gmarco_1_L007_rawdata_001_qn_aligned.bam
**********


08:47:21.579 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/apps/local/picard-tools/picard-tools-2.20.1/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed May 22 08:47:21 CEST 2019] FilterSamReads INPUT=bwa_mem_SM000000_gmarco_1_L007_rawdata_001_qn.bam FILTER=includeAligned OUTPUT=bwa_mem_SM000000_gmarco_1_L007_rawdata_001_qn_aligned.bam    WRITE_READS_FILES=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed May 22 08:47:21 CEST 2019] Executing as gmarco@fn.sgnet.local on Linux 3.10.0-693.5.2.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_66-b17; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.1-SNAPSHOT
INFO	2019-05-22 08:47:21	FilterSamReads	Filtering [presorted=true] bwa_mem_SM000000_gmarco_1_L007_rawdata_001_qn.bam -> OUTPUT=bwa_mem_SM000000_gmarco_1_L007_rawdata_001_qn_aligned.bam [sortorder=queryname]
ERROR	2019-05-22 08:47:22	FilterSamReads	Failed to filter bwa_mem_SM000000_gmarco_1_L007_rawdata_001_qn.bam
htsjdk.samtools.SAMException: Second record is not marked as second of pair: HWI-ST470R:307:C2EY7ACXX:7:1107:17152:22019 1/2 33b aligned to chr10:31970049-31970081.
	at htsjdk.samtools.SamPairUtil.assertMate(SamPairUtil.java:134)
	at htsjdk.samtools.filter.FilteringSamIterator.getNextRecord(FilteringSamIterator.java:140)
	at htsjdk.samtools.filter.FilteringSamIterator.next(FilteringSamIterator.java:108)
	at picard.sam.FilterSamReads.filterReads(FilterSamReads.java:255)
	at picard.sam.FilterSamReads.doWork(FilterSamReads.java:345)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
[Wed May 22 08:47:22 CEST 2019] picard.sam.FilterSamReads done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=1029177344
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
```

#### Steps to reproduce
`java -Xms1g -Xmx4g -jar /share/apps/local/picard-tools/picard-tools-2.20.1/picard.jar FilterSamReads FILTER=includeAligned I=bwa_mem_SM000000_gmarco_1_L007_rawdata_001_qn.bam O=bwa_mem_SM000000_gmarco_1_L007_rawdata_001_qn_aligned.bam`

#### Expected behavior
This should filter the BAM file.

#### Actual behavior
I don't understand the error. Picard is assuming that "Second record is not marked as second of pair", however I don't understand Picard behavior.

There's 3 reads from bwa mem output with the ID mentioned in the log.

```
HWI-ST470R:307:C2EY7ACXX:7:1107:17152:22019	83	chr4	99088802	60	32S68M	=	99088652	-218	GGGGGGCGCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCTTGCAATGGCTCCAACCGGAAGGGCGGTGCTCGAGCTGTGGTGCGTGCTGCTAAGTTGT	5)&)&&&&)&&905>9DDDB<59B<9009>DDDDDDDDDBDDDDEDEEDFFFFHHEJJJJJIJJJIIJJJJJJJJJJJJJJJJJJJJHHHHHFFFFFCCC	SA:Z:chr10,31970049,-,7S33M60S,0,0;	MC:Z:100M	MD:Z:57C10	NM:i:1	AS:i:63	XS:i:21
HWI-ST470R:307:C2EY7ACXX:7:1107:17152:22019	339	chr10	31970049	0	7H33M60H	chr4	99088652	0	GCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG	&)&&905>9DDDB<59B<9009>DDDDDDDDDB	SA:Z:chr4,99088802,-,32S68M,60,1;	MC:Z:100M	MD:Z:33	NM:i:0	AS:i:33	XS:i:32
HWI-ST470R:307:C2EY7ACXX:7:1107:17152:22019	163	chr4	99088652	60	100M	=	99088802	218	CCCTTGGACTCAGGGCCCTCCGCTCAACGGGCCCTACCTCGTTCGCCATGTTCACGGATTCTGGTCGGCGCGGGGGGCTGACATCCGGGGTGGGCCGCGC	CCCFFFFFHHHHHJJJJJJJJIJJJJJJJJIJJJIJJIIIJJIJJJHHHFFFFFFDDDDDDDCD@CDDDDDDDDBDDDBBDDCDDDDDDD09BDDBDBDB	MC:Z:32S68M	MD:Z:100	NM:i:0	AS:i:100	XS:i:0
```

I tried filtering the bam with samtools (filter Q<20) and then processing it with Picard without success (only two reads remain after filtering the read with MAPQ==0). I'm reporting the error with the original bam obtained from BWA so there's not a single filter or post-processing applied to it. I guess Picard is assuming that the second read should be marked as secondary, however I think this is not always true for BWA mem alignment output. I don't know if this is intended, a bug or a bwa mem bug.

I've uploaded my BAM input file here: https://we.tl/t-YlfBXlXwqs

----

----

**Comment by yfarjoun** [comment]
hmmm. I think that you've indeed stumbled on a bug in the logic. The problem is that the code assumes that read1 and read2 are consecutive in the file (meaning that the file is queryname sorted) but in the presence of secondary/supplementary reads even that wouldn't help....I think that the aligned filter should be re-written and it shouldn't even be that hard....

If you are willing to fix it, I can advise you how, otherwise I'll see when I get time to get around to doing it. 

Thanks for the report!

**Comment by guillermomarco** [comment]
Input BAM is queryname sorted but doesn't matter. As you say it makes a wrong assumption on the order of the reads (assuming read1 goes always first in queryname order). I would like to contribute but my Java skills are not that strong!
