### ISSUE TITLE
Feature update/request: gradle version upgrade/documentation update for installation

### ISSUE THREAD

**Issue by mmelendrez** [broadinstitute/picard#1379]
My system: Ubuntu 18.04.2 LTS, 16G Memory, 64-bit

I was wondering if updating the tools to be compatible with later java distributions is on the docket. Wanting to use Picard tools, I ran through the steps:
```
melanie@llandru:~/Software$ git clone https://github.com/broadinstitute/picard.git
Cloning into 'picard'...
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 132793 (delta 16), reused 37 (delta 11), pack-reused 132726
Receiving objects: 100% (132793/132793), 165.71 MiB | 3.47 MiB/s, done.
Resolving deltas: 100% (105829/105829), done.
melanie@llandru:~/Software$ cd picard/
melanie@llandru:~/Software/picard$ ./gradlew 
build.gradle          Dockerfile            etc/                  .gitignore            LICENSE.txt           settings.gradle       .travis.yml
build_push_docker.sh  .dockerignore         .git/                 gradle/               .pullapprove.yml      src/                  
build.xml             docs/                 .github/              gradlew               README.md             testdata/             
melanie@llandru:~/Software/picard$ ./gradlew shadowJar
Downloading https://services.gradle.org/distributions/gradle-3.1-all.zip
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/melanie/.gradle/wrapper/dists/gradle-3.1-all/ejgglywf033yp6s4x8ahmgm74/gradle-3.1-all.zip to /home/melanie/.gradle/wrapper/dists/gradle-3.1-all/ejgglywf033yp6s4x8ahmgm74
Set executable permissions for: /home/melanie/.gradle/wrapper/dists/gradle-3.1-all/ejgglywf033yp6s4x8ahmgm74/gradle-3.1/bin/gradle

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.4'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
melanie@llandru:~/Software/picard$ java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
melanie@llandru:~/Software/picard$ ./gradlew shadowJar --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.4'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '11.0.4'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:68)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:78)
        at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:29)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:174)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```
```
melanie@llandru:~/Software/picard$ vi gradle/wrapper/gradle-wrapper.properties

#Mon Aug 14 16:27:51 EDT 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-3.1-all.zip
```
Your distrubtion is v3.1?

According to this post from StackOverflow - I'm guessing v3.1 won't support later java versions.
[https://stackoverflow.com/questions/54358107/gradle-could-not-determine-java-version-from-11-0-2](url)

So unless I downgrade my java, it seems I may not be able to use picard tools? Unless you have a work around?

Thanks!

**Comment by lbergelson** [comment]
Picard isn't tested on java 11 at the moment so it's not clear if it would work correctly on java 11 even if the gradle build worked.  You could download the [pre-built picard](https://github.com/broadinstitute/picard/releases/download/2.20.5/picard.jar) (see the [releases page](https://github.com/broadinstitute/picard/releases) for more versions) and try it out instead of trying to build with 11.  

We'd like to both the gradle version and support java 11 but don't have a definite timeline for either.

**Comment by lbergelson** [comment]
It may be useful to take a look at the utility [jEnv](https://www.jenv.be/) which makes it much easier to manage multiple java installations if you have software that requires different versions.

**Comment by hlenghi** [comment]
sudo apt-get install openjdk-8-jdk
sudo update-alternatives --config java

and you select openjdk-8-jdk as default java version. Then in the picard root directory

./gradlew shadowJar

**Comment by lbergelson** [comment]
@hlenghi I have an open PR (https://github.com/broadinstitute/picard/pull/1410) which allows picard to build on java 11.  Unfortunately I haven't figured out how to build a java 8/11 compatible jar yet, so if you build with java 11 it won't work on 8 and we can't yet publish a cross compatible jar. 

All the tests pass, so it looks like it should be good, but consider it *beta* and PLEASE report any issues you run into.

**Comment by hlenghi** [comment]
i was saying how to build master branch if your default java version is 11. You do not need any extra tool.
