### ISSUE TITLE
Picard reordersam err "invalid stored block lengths"

### ISSUE THREAD

**Issue by wyzhangMPI** [broadinstitute/picard#1388]
Hi,
   I am tryinig to run Picard Reordersam tools to reorder bam files, before running GATK variant calling afterwards. However, I always got the same error for several bam files.

The command I used to run Picard Reordersam:
> java -Xmx50g -d64 -jar /Path/PICARD ReorderSam I=/Path/Input.bam O=/Path/Output.bam R=/Path/Reference.fa

The error I got was:
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
INFO    2019-08-15 10:51:07     ReorderSam      Writing reads...
INFO    2019-08-15 10:51:08     ReorderSam        Processing 1
INFO    2019-08-15 11:05:41     ReorderSam      Wrote 66303648 reads
INFO    2019-08-15 11:05:41     ReorderSam        Processing 2
INFO    2019-08-15 11:19:31     ReorderSam      Wrote 60910579 reads
INFO    2019-08-15 11:19:31     ReorderSam        Processing 3
INFO    2019-08-15 11:31:11     ReorderSam      Wrote 51335057 reads
INFO    2019-08-15 11:31:11     ReorderSam        Processing 4
INFO    2019-08-15 11:42:47     ReorderSam      Wrote 51798837 reads
INFO    2019-08-15 11:42:47     ReorderSam        Processing 5
[Thu Aug 15 11:45:45 CEST 2019] picard.sam.ReorderSam done. Elapsed time: 54.64 minutes.
Runtime.totalMemory()=1488453632
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.util.zip.DataFormatException: invalid stored block lengths
        at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:128)
        at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:63)
        at htsjdk.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:407)
        at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:390)
        at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:132)
        at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:261)
        at java.io.DataInputStream.read(DataInputStream.java:149)
        at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:404)
        at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)
        at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:366)
        at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:199)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:682)
        at htsjdk.samtools.BAMFileReader$BAMFileIndexIterator.getNextRecord(BAMFileReader.java:802)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:656)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:650)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:620)
        at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.advance(BAMFileReader.java:853)
        at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:843)
        at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:809)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:569)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:543)
        at picard.sam.ReorderSam.writeReads(ReorderSam.java:170)
        at picard.sam.ReorderSam.doWork(ReorderSam.java:125)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:208)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
Caused by: java.util.zip.DataFormatException: invalid stored block lengths
        at java.util.zip.Inflater.inflateBytes(Native Method)
        at java.util.zip.Inflater.inflate(Inflater.java:259)
        at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:112)
        ... 25 more__**

It is not likely the issue came from the wrong reference genome, as nothing wrong happened for other bam files. Also, I tried to increase the JAVA memory size, but it also did not work.

Any idea on what is going wrong there? Any suggestion would be helpful.
Thanks!

**Comment by yfarjoun** [comment]
did you read the docs for the tool?

"Not to be confused with SortSam which sorts a SAM or BAM file with a valid
sequence dictionary, ReorderSam reorders reads in a SAM/BAM file to match
the contig ordering in a provided reference file, as determined by exact
name matching of contigs. Reads mapped to contigs absent in the new
reference are dropped. Runs substantially faster if the input is an indexed
BAM file. Example java -jar picard.jar ReorderSam \ INPUT=sample.bam \
OUTPUT=reordered.bam \ REFERENCE=reference_with_different_order.fasta
"

**Comment by wyzhangMPI** [comment]
Yes, that is exactly the purpose to run reordersam.

Need to update that the original code:
  > java -Xmx50g -d64 -jar /Path/PICARD ReorderSam I=/Path/Input.bam 
O=/Path/Output.bam R=/Path/Reference_NewOrder.fa

The new reference file was reordered, in a different way with the 
original reference sequence for the read alignment.

I suspect there was something wrong with the Java memory, but am not 
sure.

Best,
Wenyu

------ Original Message ------

**Comment by yfarjoun** [comment]
No problem.

It looks from the error message that the gzip blocks are corrupt. Can you
convert this to a SAM file using ViewSam or samtools?

**Comment by wyzhangMPI** [comment]
I re-generated the bam file before Reordersam process, and now it seems 
to work.

Thanks!

------ Original Message ------
