### ISSUE TITLE
Unit tests fail due to changes in HashMap iteration order

### ISSUE THREAD

**Issue by mattsooknah** [broadinstitute/picard#139]
Java 8 includes some possible changes to HashSet/Map iteration order:
http://docs.oracle.com/javase/8/docs/technotes/guides/collections/changes8.html

Some unit tests that compare files will break because of this. For example, the write order of read group header params may change:

```
   [testng] FAILED: testNonBarcoded
   [testng] htsjdk.samtools.SAMException: Files /var/folders/c_/gb26gz6s6rngcxblwp1sb31h0000gp/T/nonBarcoded.5177585563167724806.sam and testdata/picard/illumina/25T8B25T/sams/nonBarcoded.sam differ.
   [testng]     at htsjdk.samtools.util.IOUtil.assertFilesEqual(IOUtil.java:404)
   [testng]     at picard.illumina.IlluminaBasecallsToSamTest.testNonBarcoded(IlluminaBasecallsToSamTest.java:80)
   [testng] ... Removed 21 stack frames
   [testng] FAILED: testMultiplexedWithAlternateBarcodeName
   [testng] htsjdk.samtools.SAMException: Files /var/folders/c_/gb26gz6s6rngcxblwp1sb31h0000gp/T/singleBarcodeAltName.4683165887051716028.dir/AAAAAAAA.sam and testdata/picard/illumina/25T8B25T/sams/AAAAAAAA.sam differ.
   [testng]     at htsjdk.samtools.util.IOUtil.assertFilesEqual(IOUtil.java:404)
   [testng]     at picard.illumina.IlluminaBasecallsToSamTest.runStandardTest(IlluminaBasecallsToSamTest.java:165)
   [testng]     at picard.illumina.IlluminaBasecallsToSamTest.testMultiplexedWithAlternateBarcodeName(IlluminaBasecallsToSamTest.java:91)
   [testng] ... Removed 21 stack frames
   [testng] FAILED: testDualBarcodes
   [testng] htsjdk.samtools.SAMException: Files /var/folders/c_/gb26gz6s6rngcxblwp1sb31h0000gp/T/dualBarcode.2258278280539031805.dir/AACTTGAC.sam and testdata/picard/illumina/25T8B8B25T/sams/AACTTGAC.sam differ.
   [testng]     at htsjdk.samtools.util.IOUtil.assertFilesEqual(IOUtil.java:404)
   [testng]     at picard.illumina.IlluminaBasecallsToSamTest.runStandardTest(IlluminaBasecallsToSamTest.java:165)
   [testng]     at picard.illumina.IlluminaBasecallsToSamTest.testDualBarcodes(IlluminaBasecallsToSamTest.java:96)
   [testng] ... Removed 21 stack frames
   [testng] FAILED: testMultiplexed
   [testng] htsjdk.samtools.SAMException: Files /var/folders/c_/gb26gz6s6rngcxblwp1sb31h0000gp/T/multiplexedBarcode.3415989947968785924.dir/AAAAAAAA.sam and testdata/picard/illumina/25T8B25T/sams/AAAAAAAA.sam differ.
   [testng]     at htsjdk.samtools.util.IOUtil.assertFilesEqual(IOUtil.java:404)
   [testng]     at picard.illumina.IlluminaBasecallsToSamTest.runStandardTest(IlluminaBasecallsToSamTest.java:165)
   [testng]     at picard.illumina.IlluminaBasecallsToSamTest.testMultiplexed(IlluminaBasecallsToSamTest.java:85)
   [testng] ... Removed 21 stack frames
```

**Comment by nh13** [comment]
@mattsooknah is this fixed?

**Comment by mattsooknah** [comment]
Not yet.

**Comment by vdauwera** [comment]
Sounds like something the consultants could help with. Let me know if you want support on this.

**Comment by nh13** [comment]
@vdauwera yes please.

**Comment by vdauwera** [comment]
Waiting to hear back from @akiezun re: whether the Hellbenderites willhandle this as part of their current sprint. Otherwise I will get secons on it.

**Comment by akiezun** [comment]
@vdauwera My understanding was that the picard folks were on it. If I'm mistaken, decide what you want to do and let me know.

**Comment by vdauwera** [comment]
@akiezun I'm not aware that anyone was planning to move on this on this, so I'm happy to prioritize it to the secons if it helps.

**Comment by yfarjoun** [comment]
has been resolved.
