### ISSUE TITLE
UmiAwareMarkDuplicatesWithMateCigar Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by hustal** [broadinstitute/picard#1396]
### Affected tool(s)
Picard version: 2.20.7-SNAPSHOT

### Description 

I experienced with the same error already reported in here,

https://gatkforums.broadinstitute.org/gatk/discussion/12862/umiawaremarkduplicateswithmatecigar-java-lang-nullpointerexception-error

I also prepared BAM file with UMI as mentioned above link.

I am not sure where is the problem, is it something wrong with the bam file or ?

Looking forward to have the solution/answer.

Thanks.

**Comment by yfarjoun** [comment]
@fleharty is there progress on this issue? I saw that you responded on the forum.

**Comment by fleharty** [comment]
@hustal I looked for the bam but was unable to find it, could you tell me what the name is of the bam you put on the ftp server?

**Comment by hustal** [comment]
@fleharty I am not the same person but have faced same error. Here I attached a snapshot of my BAM file. Please let me know if you have any more question or need any more information.

![BAM-file snapshot](https://user-images.githubusercontent.com/18271809/64762185-f4e6d280-d53d-11e9-987c-5238601b02df.png)

Thanks.

**Comment by hustal** [comment]
@fleharty I have uploaded my test bam file (**hustal_test.bam**) into your given FTP server.  Here is the exact **command** I used,

java -jar ~/My_Tools/picard.jar UmiAwareMarkDuplicatesWithMateCigar I=test.bam O=mark_dups_w_mate_cig.bam M=mark_dups_w_mate_cig_metrics.txt UMI_METRICS=output_umi_metrics.txt

**### And the Error I got,**

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    UmiAwareMarkDuplicatesWithMateCigar -I test.bam -O mark_dups_w_mate_cig.bam -M mark_dups_w_mate_cig_metrics.txt -UMI_METRICS output_umi_metrics.txt
**********


09:23:31.750 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/husain.talukdar/My_Tools/picard.jar!/com/intel/gkl/native/libgkl_compression.dylib
[Fri Sep 13 09:23:31 CEST 2019] UmiAwareMarkDuplicatesWithMateCigar UMI_METRICS_FILE=output_umi_metrics.txt INPUT=[test.bam] OUTPUT=mark_dups_w_mate_cig.bam METRICS_FILE=mark_dups_w_mate_cig_metrics.txt    MAX_EDIT_DISTANCE_TO_JOIN=1 UMI_TAG_NAME=RX ALLOW_MISSING_UMIS=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag CLEAR_DT=true DUPLEX_UMI=false ADD_PG_TAG_TO_READS=true REMOVE_DUPLICATES=false ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=UmiAwareMarkDuplicatesWithMateCigar READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Fri Sep 13 09:23:31 CEST 2019] Executing as husain.talukdar@husaintmbp on Mac OS X 10.14.6 x86_64; Java HotSpot(TM) 64-Bit Server VM 12.0.2+10; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.7-SNAPSHOT
[Fri Sep 13 09:23:32 CEST 2019] picard.sam.markduplicates.UmiAwareMarkDuplicatesWithMateCigar done. Elapsed time: 0,01 minutes.
Runtime.totalMemory()=554696704
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NullPointerException
	at picard.sam.markduplicates.UmiAwareDuplicateSetIterator.process(UmiAwareDuplicateSetIterator.java:140)
	at picard.sam.markduplicates.UmiAwareDuplicateSetIterator.next(UmiAwareDuplicateSetIterator.java:119)
	at picard.sam.markduplicates.UmiAwareDuplicateSetIterator.next(UmiAwareDuplicateSetIterator.java:53)
	at picard.sam.markduplicates.SimpleMarkDuplicatesWithMateCigar.doWork(SimpleMarkDuplicatesWithMateCigar.java:126)
	at picard.sam.markduplicates.UmiAwareMarkDuplicatesWithMateCigar.doWork(UmiAwareMarkDuplicatesWithMateCigar.java:138)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)



Thank you very much.

**Comment by fleharty** [comment]
@hustal 
The bam you have provided does not meet the bam specifications.  It is missing the read group tag.
You can fix your bam by adding the RG tags in the header of your bam file, then the tool should work.

At this stage, there doesn't appear to be a bug in UmiAwareMarkDuplicatesWMC.

**Comment by fleharty** [comment]
@hustal I'm going to keep this ticket open to put in a more obvious error message so that it will fail more gracefully on bams without readgroups.

**Comment by hustal** [comment]
@fleharty Great job, now it's working. Thank you very much. Just wondering, is it possible to add an extra check for this (right structure of BAM) with proper error message. This will be helpful for people like me who just started to work with BAM files.
