### ISSUE TITLE
java.lang.IllegalArgumentException: The requested position is not covered by this StartEdgingRecordAndOffset object

### ISSUE THREAD

**Issue by flexray** [broadinstitute/picard#1402]
### Affected tool(s)
Picard CollectRawWgsMetrics

### Affected version(s)
2.20.8/bioconda - tested
2.20.7/bioconda - tested
2.20.6/bioconda - tested
2.20.5/bioconda - tested

### Description 
CollectWgsMetrics crashes on input that has worked for previous versions, last working is 2.20.4 from bioconda.

#### Steps to reproduce
```
picard -Xms4000m \
  CollectRawWgsMetrics \
  INPUT=example.bam
  VALIDATION_STRINGENCY=SILENT \
  REFERENCE_SEQUENCE=Homo_sapiens_assembly38.fasta \
  INCLUDE_BQ_HISTOGRAM=true \
  INTERVALS=wgs_coverage_regions.hg38.interval_list \
  OUTPUT=example.raw_wgs_metrics \
  USE_FAST_ALGORITHM=true \
  READ_LENGTH=250
```

#### Expected behavior
Standard processing instead of crash.
```
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell_root/tmp.4661a980
INFO    2019-09-21 16:09:40     CollectRawWgsMetrics

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    CollectRawWgsMetrics -INPUT example.bam -VALIDATION_STRINGENCY SILENT -REFERENCE_SEQUENCE Homo_sapiens_assembly38.fasta -INCLUDE_BQ_HISTOGRAM true -INTERVALS wgs_coverage_regions.hg38.interval_list -OUTPUT example.raw_wgs_metrics -USE_FAST_ALGORITHM true -READ_LENGTH 250
**********


16:09:41.148 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/picard-2.20.4-1/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Sat Sep 21 16:09:41 GMT 2019] CollectRawWgsMetrics INPUT=example.bam OUTPUT=example.raw_wgs_metrics INCLUDE_BQ_HISTOGRAM=true INTERVALS=wgs_coverage_regions.hg38.interval_list USE_FAST_ALGORITHM=true READ_LENGTH=250 VALIDATION_STRINGENCY=SILENT REFERENCE_SEQUENCE=Homo_sapiens_assembly38.fasta    MINIMUM_MAPPING_QUALITY=0 MINIMUM_BASE_QUALITY=3 COVERAGE_CAP=100000 LOCUS_ACCUMULATION_CAP=200000 STOP_AFTER=-1 COUNT_UNPAIRED=false SAMPLE_SIZE=10000 ALLELE_FRACTION=[0.001, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.3, 0.5] VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Sat Sep 21 16:09:41 GMT 2019] Executing as root@fa3d66ca7e5c on Linux 4.15.0-1037-gcp amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.4-SNAPSHOT
INFO    2019-09-21 16:09:53     CollectWgsMetrics       Processed    10,000,000 loci.  Elapsed time: 00:00:12s.  Time for last 10,000,000:    9s.  Last read position: chr1:10,203,509
INFO    2019-09-21 16:10:02     CollectWgsMetrics       Processed    20,000,000 loci.  Elapsed time: 00:00:21s.  Time for last 10,000,000:    9s.  Last read position: chr1:20,303,509
INFO    2019-09-21 16:10:11     CollectWgsMetrics       Processed    30,000,000 loci.  Elapsed time: 00:00:29s.  Time for last 10,000,000:    8s.  Last read position: chr1:30,305,111
etc...
```

#### Actual behavior
```
18:48:46.330 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/picard-2.20.7-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Sep 20 18:48:46 GMT 2019] CollectRawWgsMetrics INPUT=example.bam
[Fri Sep 20 18:48:46 GMT 2019] Executing as root@98e13b9f4ef1 on Linux 4.19.44+ amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.7-SNAPSHOT
[Fri Sep 20 18:49:00 GMT 2019] picard.analysis.CollectRawWgsMetrics done. Elapsed time: 0.24 minutes.
Runtime.totalMemory()=4054515712
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: The requested position is not covered by this StartEdgingRecordAndOffset object.
        at htsjdk.samtools.util.AbstractRecordAndOffset.validateOffset(AbstractRecordAndOffset.java:146)
        at htsjdk.samtools.util.EdgingRecordAndOffset$StartEdgingRecordAndOffset.getBaseQuality(EdgingRecordAndOffset.java:112)
        at picard.analysis.FastWgsMetricsCollector.excludeByQuality(FastWgsMetricsCollector.java:189)
        at picard.analysis.FastWgsMetricsCollector.processRecord(FastWgsMetricsCollector.java:144)
        at picard.analysis.FastWgsMetricsCollector.addInfo(FastWgsMetricsCollector.java:105)
        at picard.analysis.WgsMetricsProcessorImpl.processFile(WgsMetricsProcessorImpl.java:93)
        at picard.analysis.CollectWgsMetrics.doWork(CollectWgsMetrics.java:231)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

**Comment by yfarjoun** [comment]
Thanks for the report!

Is this only for the fast algorithm? Or both?

**Comment by flexray** [comment]
Good point! Works good on 2.20.8 with fast algorithm disabled... Are there any differences in quality? I could expect speed differences... 
```
17:27:03.049 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/picard-2.20.8-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Sat Sep 21 17:27:03 GMT 2019] CollectRawWgsMetrics INPUT=example.bam OUTPUT=example.raw_wgs_metrics INCLUDE_BQ_HISTOGRAM=true INTERVALS=wgs_coverage_regions.hg38.interval_list USE_FAST_ALGORITHM=false READ_LENGTH=250 VALIDATION_STRINGENCY=SILENT REFERENCE_SEQUENCE=Homo_sapiens_assembly38.fasta    MINIMUM_MAPPING_QUALITY=0 MINIMUM_BASE_QUALITY=3 COVERAGE_CAP=100000 LOCUS_ACCUMULATION_CAP=200000 STOP_AFTER=-1 COUNT_UNPAIRED=false SAMPLE_SIZE=10000 ALLELE_FRACTION=[0.001, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.3, 0.5] VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Sat Sep 21 17:27:03 GMT 2019] Executing as root@76b8de300821 on Linux 4.15.0-1037-gcp amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.8-SNAPSHOT
INFO    2019-09-21 17:27:19     CollectWgsMetrics       Processed    10,000,000 loci.  Elapsed time: 00:00:16s.  Time for last 10,000,000:   13s.  Last read position: chr1:10,203,509
INFO    2019-09-21 17:27:33     CollectWgsMetrics       Processed    20,000,000 loci.  Elapsed time: 00:00:30s.  Time for last 10,000,000:   13s.  Last read position: chr1:20,303,509
```

**Comment by yfarjoun** [comment]
Thanks for checking!

There should be only speed differences, the implementation of the locus
traversal is completely different, but the results should be the same
except for edge cases involving extremely long reads or extremely high
depths.
