### ISSUE TITLE
RenameSampleInVcf: complex breakends rearrangements not supported

### ISSUE THREAD

**Issue by cagaser** [broadinstitute/picard#1406]
### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
_Tool name(s), special parameters?_
picard RenameSampleInVcf

### Affected version(s)
- [ ] Latest public release version [version?]
- [ ] Latest development/master branch as of [date of test?]

Picard version: 2.21.1-SNAPSHOT (Conda)
Tested: 7-Oct-'19

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._
```
(picard) cagaser@camouflageshark:/exports/project-x/analysis/16_germline_dna_biowdl/samples/smpl_x/delly$ picard RenameSampleInVcf INPUT=smpl_x.delly.vcf OUTPUT="smpl_x.delly.renamed.test.vcf" NEW_SAMPLE_NAME="Test"                                                              
INFO    2019-10-07 10:47:40     RenameSampleInVcf

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    RenameSampleInVcf -INPUT smpl_x.delly.vcf -OUTPUT smpl_x.delly.renamed.test.vcf -NEW_SAMPLE_NAME Test
**********


10:47:41.569 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/exports/sascstudent/cedrick/conda/envs/picard/share/picard-2.21.1-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Mon Oct 07 10:47:41 CEST 2019] RenameSampleInVcf INPUT=smpl_x.delly.vcf OUTPUT=smpl_x.delly.renamed.test.vcf NEW_SAMPLE_NAME=Test    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Oct 07 10:47:41 CEST 2019] Executing as cagaser@camouflageshark on Linux 4.4.0-148-generic amd64; OpenJDK 64-Bit Server VM 11.0.1+13-LTS; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.21.1-SNAPSHOT
[Mon Oct 07 10:47:42 CEST 2019] picard.vcf.RenameSampleInVcf done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=536870912
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 29855: VCF support for complex rearrangements with breakends has not yet been implemented, for input source: file:///exports/project-x/analysis/16_germline_dna_biowdl/samples/smpl_x/delly/smpl_x.delly.vcf
        at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:887)
        at htsjdk.variant.vcf.AbstractVCFCodec.checkAllele(AbstractVCFCodec.java:678)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseAlleles(AbstractVCFCodec.java:640)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:443)
        at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:384)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:328)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:48)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:70)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:37)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.readNextRecord(TribbleIndexedFeatureReader.java:373)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:354)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:315)
        at picard.vcf.RenameSampleInVcf.doWork(RenameSampleInVcf.java:133)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)


```

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem and provide a minimal test case._

```
picard RenameSampleInVcf INPUT=delly.original.vcf OUTPUT="delly.renamed.test.vcf" NEW_SAMPLE_NAME="Test" 
```

#### Expected behavior
_Tell us what should happen_

The sample name changed
``` 
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Test 
```
Contains the same number of variants
``` 
grep -v "#" delly.original.vcf  | wc -l   30570
grep -v "#" delly.renamed.test.vcf | wc -l   30570
```

#### Actual behavior
_Tell us what happens instead_

I get the error as mentioned above 

The sample name changed 
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Test
```
But the number of variants changed
``` 
grep -v "#" delly.original.vcf  | wc -l   30570
grep -v "#" delly.renamed.test.vcf | wc -l   29318
```
This is the culprit
```
chrUn_KI270518v1        2388    BND00029616     ]       ][chr20:28830156[       .       PASS
``` 
----

### Tool(s) involved
_Tool name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) involved
_Tool name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by yfarjoun** [comment]
This is an htsjdk issue, which needs to be fixed.
