### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by shimingtan** [broadinstitute/picard#1407]
Hello there,

I am trying to run the following commands:

` java -jar -Xmx1g /gpfs1/scratch/shiming/tools/Picard/picard.jar MarkDuplicates M=1B131118A.marked_dup_metrics.txt REMOVE_DUPLICATES=true I=1B131118A.sorted.bam  O=1B131118A.bwa.dedupe.bam`

But I came out with the following error:

`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at htsjdk.samtools.util.BinaryCodec.readString(BinaryCodec.java:473)
	at htsjdk.samtools.BAMFileReader.readHeader(BAMFileReader.java:701)
	at htsjdk.samtools.BAMFileReader.<init>(BAMFileReader.java:298)
	at htsjdk.samtools.BAMFileReader.<init>(BAMFileReader.java:176)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:396)
	at picard.sam.markduplicates.util.AbstractMarkDuplicatesCommandLineProgram.openInputs(AbstractMarkDuplicatesCommandLineProgram.java:220)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:533)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)`

Will appreciate if anyone can help! Thank you.

**Comment by yfarjoun** [comment]
Need more memory. -Xmx1g might not be enough for your purposes.
Alternatively you can try to lower MAX_RECORDS_IN_RAM, but could have other
harmful effects (like running out of file handles)

**Comment by shimingtan** [comment]
Dear @yfarjoun ,

When I try to increase the memory to -Xmx100g, I am still getting an error message.

`(samtools) [shiming@ca-0004 sorted-bam]$ java -jar -Xmx100g /gpfs1/scratch/shiming/tools/Picard/picard.jar MarkDuplicates M=1B131118A.marked_dup_metrics.txt REMOVE_DUPLICATES=true I=1B131118A.sorted.bam  O=1B131118A.bwa.dedupe.bam
INFO	2019-10-11 11:31:47	MarkDuplicates	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    MarkDuplicates -M 1B131118A.marked_dup_metrics.txt -REMOVE_DUPLICATES true -I 1B131118A.sorted.bam -O 1B131118A.bwa.dedupe.bam
**********


11:31:48.213 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gpfs1/scratch/shiming/tools/Picard/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Oct 11 11:31:48 SGT 2019] MarkDuplicates INPUT=[1B131118A.sorted.bam] OUTPUT=1B131118A.bwa.dedupe.bam METRICS_FILE=1B131118A.marked_dup_metrics.txt REMOVE_DUPLICATES=true    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag CLEAR_DT=true DUPLEX_UMI=false ADD_PG_TAG_TO_READS=true ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Fri Oct 11 11:31:48 SGT 2019] Executing as shiming@ca-0004 on Linux 3.10.0-862.2.3.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_171-b10; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.21.1-SNAPSHOT
INFO	2019-10-11 11:31:48	MarkDuplicates	Start of doWork freeMemory: 2036274304; totalMemory: 2058354688; maxMemory: 95444008960
INFO	2019-10-11 11:31:48	MarkDuplicates	Reading input file and constructing read end information.
INFO	2019-10-11 11:31:48	MarkDuplicates	Will retain up to 345811626 data points before spilling to disk.
[Fri Oct 11 11:31:51 SGT 2019] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.06 minutes.
Runtime.totalMemory()=9580838912
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
	at java.lang.StringCoding.encode(StringCoding.java:344)
	at java.lang.StringCoding.encode(StringCoding.java:387)
	at java.lang.String.getBytes(String.java:958)
	at htsjdk.samtools.util.BufferedLineReader.fromString(BufferedLineReader.java:57)
	at htsjdk.samtools.BAMFileReader.readHeader(BAMFileReader.java:704)
	at htsjdk.samtools.BAMFileReader.<init>(BAMFileReader.java:298)
	at htsjdk.samtools.BAMFileReader.<init>(BAMFileReader.java:176)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:396)
	at picard.sam.markduplicates.util.AbstractMarkDuplicatesCommandLineProgram.openInputs(AbstractMarkDuplicatesCommandLineProgram.java:220)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:533)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)`

Appreciate any input from you! :)

**Comment by yfarjoun** [comment]
"Exception in thread "main" java.lang.OutOfMemoryError: Requested array
size exceeds VM limit"

Which, I think, means that you are asking more memory than the VM you are
running the job on has.

**Comment by shimingtan** [comment]
Dear Yossi,

How do I determine the optimla value of “-Xmx” to use so that I am not asking for more memory than the VM?

Appreciate your input!

Thanks!
Shi Ming

**Comment by yfarjoun** [comment]
At this point, I think you'll get better answer from the GATK forum https://gatkforums.broadinstitute.org/gatk/categories/gatk-support-forum
