### ISSUE TITLE
GenotypeConcordance v4.1.4.1 IndexOutOfBoundsException

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/picard#1439]
User report:

Ran with the most recent version of gatk4.1.4.1.

**COMMAND: gatk GenotypeConcordance -R /data/BIOINFORMATICS/REFERENCES/GATK_TEST/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta -O R4j_COMPARE_TO_KNOWN_SNPS/NA12878_HPrep_Rep2_8plex_MAD050_Cap003_S23_GenotypeConcordance.txt  -CV R4c_FILTER_SNP/NA12878_HPrep_Rep2_8plex_MAD050_Cap003_S23_HaplotypeCaller.SNP_filtered.vcf  -TV /data/BIOINFORMATICS/RESOURCES/somatic-hg38_af-only-gnomad.hg38.vcf.gz --INTERVALS R3n_BED_TO_INTERVAL_LIST/NA12878_HPrep_Rep2_8plex_MAD050_Cap003_S23_bait.interval_list**

==========================================

Using GATK jar /data1/BIOINFORMATICS/SOFTWARE/ANACONDA_JN/MINI-CONDA/envs/gatk4/share/gatk4-4.1.4.1-0/gatk-package-4.1.4.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /data1/BIOINFORMATICS/SOFTWARE/ANACONDA_JN/MINI-CONDA/envs/gatk4/share/gatk4-4.1.4.1-0/gatk-package-4.1.4.1-local.jar GenotypeConcordance -R /data/BIOINFORMATICS/REFERENCES/GATK_TEST/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta -O R4j_COMPARE_TO_KNOWN_SNPS/NA12878_HPrep_Rep2_8plex_MAD050_Cap003_S23_GenotypeConcordance.txt -CV R4c_FILTER_SNP/NA12878_HPrep_Rep2_8plex_MAD050_Cap003_S23_HaplotypeCaller.SNP_filtered.vcf -TV /data/BIOINFORMATICS/RESOURCES/somatic-hg38_af-only-gnomad.hg38.vcf.gz --INTERVALS R3n_BED_TO_INTERVAL_LIST/NA12878_HPrep_Rep2_8plex_MAD050_Cap003_S23_bait.interval_list
15:03:16.900 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/data1/BIOINFORMATICS/SOFTWARE/ANACONDA_JN/MINI-CONDA/envs/gatk4/share/gatk4-4.1.4.1-0/gatk-package-4.1.4.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Dec 06 15:03:16 EST 2019] GenotypeConcordance  --TRUTH_VCF /data/BIOINFORMATICS/RESOURCES/somatic-hg38_af-only-gnomad.hg38.vcf.gz --CALL_VCF R4c_FILTER_SNP/NA12878_HPrep_Rep2_8plex_MAD050_Cap003_S23_HaplotypeCaller.SNP_filtered.vcf --OUTPUT R4j_COMPARE_TO_KNOWN_SNPS/NA12878_HPrep_Rep2_8plex_MAD050_Cap003_S23_GenotypeConcordance.txt --INTERVALS R3n_BED_TO_INTERVAL_LIST/NA12878_HPrep_Rep2_8plex_MAD050_Cap003_S23_bait.interval_list --REFERENCE_SEQUENCE /data/BIOINFORMATICS/REFERENCES/GATK_TEST/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta  --OUTPUT_VCF false --INTERSECT_INTERVALS true --MIN_GQ 0 --MIN_DP 0 --OUTPUT_ALL_ROWS false --USE_VCF_INDEX false --MISSING_SITES_HOM_REF false --IGNORE_FILTER_STATUS false --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
Dec 06, 2019 3:03:17 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
[Fri Dec 06 15:03:17 EST 2019] Executing as nowackj1@ridus004.ind.roche.com on Linux 3.10.0-1062.1.2.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.1.4.1
INFO    2019-12-06 15:03:17     GenotypeConcordance     Starting to load intervals list(s).
INFO    2019-12-06 15:03:18     GenotypeConcordance     Finished loading up intervals list(s).
[Fri Dec 06 15:03:18 EST 2019] picard.vcf.GenotypeConcordance done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=2300575744
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at picard.vcf.GenotypeConcordance.doWork(GenotypeConcordance.java:325)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/61869#Comment_61869

**Comment by JonN17** [comment]
Any update on this bug?  How do you get GenotypeConcordance  with GATK4?
