### ISSUE TITLE
CollectQualityYieldMetrics has problems on RNASeq BAM file from tophat(bowtie1)

### ISSUE THREAD

**Issue by sicotte** [broadinstitute/picard#144]
I have 12 RNASeq bam files. On 11 of those, the program CollectQualityYieldMetrics aborts (without printing stats) .. after it seemingly has finished processing the reads on the last chromosome)

Runtime.totalMemory()=1665204224
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 78218867, Read name R0251321:126:H7NGRADXX:2:1101:1537:1996, Mapped mate should have mate reference name
        at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:439)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:643)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:628)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:598)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:515)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:489)
        at picard.analysis.CollectQualityYieldMetrics.doWork(CollectQualityYieldMetrics.java:94)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:89)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:99)

**Comment by vdauwera** [comment]
Hi @sicotte,

Sorry for the much delayed response; we had a resource shortage and were unable to provide as much support as we like to the user community. I realize this probably comes too late to help you with the particular problem you encountered, but just in case this can be of use to you or others, here is the solution.

This validation error suggests that your file is malformed. In this particular case, it looks like something that would be fixed by FixMateInformation, which you can read more about here: http://broadinstitute.github.io/picard/command-line-overview.html#FixMateInformation
