### ISSUE TITLE
#Error:Heap-Memory Issues

### ISSUE THREAD

**Issue by Rohit-Satyam** [broadinstitute/picard#1474]
## Picard version: 2.21.9-SNAPSHOT
> To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: Exception writing ReadEnds to file.
        at picard.sam.markduplicates.util.ReadEndsForMarkDuplicatesCodec.encode(ReadEndsForMarkDuplicatesCodec.java:74)
        at picard.sam.markduplicates.util.ReadEndsForMarkDuplicatesCodec.encode(ReadEndsForMarkDuplicatesCodec.java:32)
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:254)
        at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:182)
        at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:553)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
        Suppressed: java.io.IOException: No space left on device
                at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
                at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)
                at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
                at sun.nio.ch.IOUtil.write(IOUtil.java:65)
                at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211)
                at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
                at java.nio.channels.Channels.writeFully(Channels.java:101)
                at java.nio.channels.Channels.access$000(Channels.java:61)
                at java.nio.channels.Channels$1.write(Channels.java:174)
                at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
                at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
                at org.xerial.snappy.SnappyOutputStream.dumpOutput(SnappyOutputStream.java:360)
                at org.xerial.snappy.SnappyOutputStream.compressInput(SnappyOutputStream.java:374)
                at org.xerial.snappy.SnappyOutputStream.flush(SnappyOutputStream.java:334)
                at org.xerial.snappy.SnappyOutputStream.close(SnappyOutputStream.java:397)
                at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:259)
                ... 6 more
Caused by: java.io.IOException: No space left on device
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211)
        at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
        at java.nio.channels.Channels.writeFully(Channels.java:101)
        at java.nio.channels.Channels.access$000(Channels.java:61)
        at java.nio.channels.Channels$1.write(Channels.java:174)
                                                                      
I keep on getting memory issues with MarkDuplicates. I have had the worst experience using this tool. I tried almost every step. I was running this job on smp on X86_64 Intel_EM  with 1023.8G RAM and 127.9G swap memory. I don't understand how much more memory does picard require?

I also explicitly defined Xmx100G and 70G  memory as described [here](https://gatkforums.broadinstitute.org/gatk/discussion/12698/gatk-markduplicates-java-lang-outofmemoryerror-despite-high-memory-provided) but didn't get any success. I have checked my .bam files using ValidateSamFiles and they are error-free.

With the speed point of view, it's horribly slow. If, I run multiple jobs parallely to mitigate time required in each sample, I throw memory issues. 

`MarkDuplicates -I /path/12GVIId_S2_L001.sorted.bam -I /path/12GVIId_S2_L002.sorted.bam -I /path/12GVIId_S2_L003.sorted.bam -I /path/12GVIId_S2_L004.sorted.bam -O /path/12GVIId_S2_dedup.bam -M /path/12GVIId_S2_metrics.txt -TAGGING_POLICY All -ASSUME_SORTED true`

**Comment by Axolotl233** [comment]
Hi, is this question have been solved or have any process? i m in the same plight

**Comment by scseekers** [comment]
Hi @Axolotl233. Yes, it was mostly a hardware issue rather than the issue with the tool. When I switched to DGX server, the picard worked fine. It appears that MarkDuplicates don't like to be assigned threads and works well if running on a single core. So don't try to parallelize it if you are doing so (maybe using BSUB)

**Comment by Axolotl233** [comment]
Hi, @scseekers. thank you for your advice, now i will try to run Picard with out Slurm and hope it can work well~
