### ISSUE TITLE
Error due to `interval.list` instead of `interval_list` suffix

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/picard#1479]
User is facing this error because Picard is misreading 

Link: https://gatk.broadinstitute.org/hc/en-us/community/posts/360056676692-HS-PENALTY-20X-is-1-on-one-version-of-GATK-crashes-on-newest-version-

--

When running GATK 4.0.0.0 this works fine but I get a HS\_PENALTY\_20X of -1

It errors out on GATK v4.1.4.1

I assume a -1 for HS\_PENALTY\_20X is incorrect?

 

**# CONFIRMING FILES EXIST**

# =================================

3.8G /data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/R3f\_MARK\_DUPLICATES\_FALSE/19065WBC\_fixmate\_novosort\_dupsrmFalse.bam  
54M /data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/R3d\_INTERVALS/19065WBC\_R1.bait.interval.list  
45M /data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/R3d\_INTERVALS/19065WBC\_R1.target.interval.list

**# GATK VERSION**

# =================================  
The Genome Analysis Toolkit (GATK) v4.1.4.1  
HTSJDK Version: 2.21.0  
Picard Version: 2.21.2  
Using GATK jar /data1/BIOINFORMATICS/SOFTWARE/ANACONDA\_JN/MINI-CONDA/envs/gatk-newest/share/gatk4-4.1.4.1-1/gatk-package-4.1.4.1-local.jar  
Running:  
java -Dsamjdk.use\_async\_io\_read\_samtools=false -Dsamjdk.use\_async\_io\_write\_samtools=true -Dsamjdk.use\_async\_io\_write\_tribble=false -Dsamjdk.compression\_level=2 -jar /data1/BIOINFORMATICS/SOFTWARE/ANACONDA\_JN/MINI-CONDA/envs/gatk-newest/share/gatk4-4.1.4.1-1/gatk-package-4.1.4.1-local.jar --version

 

**# GATK COMMAND**  
# gatk CollectHsMetrics --INPUT /data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/R3f\_MARK\_DUPLICATES\_FALSE/19065WBC\_fixmate\_novosort\_dupsrmFalse.bam --OUTPUT TEMP\_NEW/19065WBC\_fixmate\_novosort\_dupsrm.bam\_hs\_metrics.txt --BAIT\_INTERVALS /data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/R3d\_INTERVALS/19065WBC\_R1.bait.interval.list --TARGET\_INTERVALS /data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/R3d\_INTERVALS/19065WBC\_R1.target.interval.list  
# =================================  
22:29:20.348 INFO NativeLibraryLoader - Loading libgkl\_compression.so from jar:file:/data1/BIOINFORMATICS/SOFTWARE/ANACONDA\_JN/MINI-CONDA/envs/gatk-newest/share/gatk4-4.1.4.1-1/gatk-package-4.1.4.1-local.jar!/com/intel/gkl/native/libgkl\_compression.so  
[Mon Feb 03 22:29:20 EST 2020] CollectHsMetrics --BAIT\_INTERVALS /data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/R3d\_INTERVALS/19065WBC\_R1.bait.interval.list --TARGET\_INTERVALS /data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/R3d\_INTERVALS/19065WBC\_R1.target.interval.list --INPUT /data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/R3f\_MARK\_DUPLICATES\_FALSE/19065WBC\_fixmate\_novosort\_dupsrmFalse.bam --OUTPUT TEMP\_NEW/19065WBC\_fixmate\_novosort\_dupsrm.bam\_hs\_metrics.txt --METRIC\_ACCUMULATION\_LEVEL ALL\_READS --NEAR\_DISTANCE 250 --MINIMUM\_MAPPING\_QUALITY 20 --MINIMUM\_BASE\_QUALITY 20 --CLIP\_OVERLAPPING\_READS true --INCLUDE\_INDELS false --COVERAGE\_CAP 200 --SAMPLE\_SIZE 10000 --ALLELE\_FRACTION 0.001 --ALLELE\_FRACTION 0.005 --ALLELE\_FRACTION 0.01 --ALLELE\_FRACTION 0.02 --ALLELE\_FRACTION 0.05 --ALLELE\_FRACTION 0.1 --ALLELE\_FRACTION 0.2 --ALLELE\_FRACTION 0.3 --ALLELE\_FRACTION 0.5 --VERBOSITY INFO --QUIET false --VALIDATION\_STRINGENCY STRICT --COMPRESSION\_LEVEL 2 --MAX\_RECORDS\_IN\_RAM 500000 --CREATE\_INDEX false --CREATE\_MD5\_FILE false --GA4GH\_CLIENT\_SECRETS client\_secrets.json --help false --version false --showHidden false --USE\_JDK\_DEFLATER false --USE\_JDK\_INFLATER false  
Feb 03, 2020 10:29:20 PM shaded.cloud\_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine  
INFO: Failed to detect whether we are running on Google Compute Engine.  
[Mon Feb 03 22:29:20 EST 2020] Executing as nowackj1@ridus004.ind.roche.com on Linux 3.10.0-1062.1.2.el7.x86\_64 amd64; OpenJDK 64-Bit Server VM 1.8.0\_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.1.4.1  
[Mon Feb 03 22:29:20 EST 2020] picard.analysis.directed.CollectHsMetrics done. Elapsed time: 0.01 minutes.  
Runtime.totalMemory()=2972712960  
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp  
htsjdk.samtools.SAMException: Cannot read non-existent file: file:///data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/@HD%09VN:1.4%09SO:unsorted  
at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:498)  
at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:485)  
at picard.analysis.directed.CollectTargetedMetrics.doWork(CollectTargetedMetrics.java:115)  
at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)  
at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)  
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)  
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)  
at org.broadinstitute.hellbender.Main.main(Main.java:292)  
Using GATK jar /data1/BIOINFORMATICS/SOFTWARE/ANACONDA\_JN/MINI-CONDA/envs/gatk-newest/share/gatk4-4.1.4.1-1/gatk-package-4.1.4.1-local.jar  
Running:  
java -Dsamjdk.use\_async\_io\_read\_samtools=false -Dsamjdk.use\_async\_io\_write\_samtools=true -Dsamjdk.use\_async\_io\_write\_tribble=false -Dsamjdk.compression\_level=2 -jar /data1/BIOINFORMATICS/SOFTWARE/ANACONDA\_JN/MINI-CONDA/envs/gatk-newest/share/gatk4-4.1.4.1-1/gatk-package-4.1.4.1-local.jar CollectHsMetrics --INPUT /data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/R3f\_MARK\_DUPLICATES\_FALSE/19065WBC\_fixmate\_novosort\_dupsrmFalse.bam --OUTPUT TEMP\_NEW/19065WBC\_fixmate\_novosort\_dupsrm.bam\_hs\_metrics.txt --BAIT\_INTERVALS /data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/R3d\_INTERVALS/19065WBC\_R1.bait.interval.list --TARGET\_INTERVALS /data/BIOINFORMATICS/PROJECT\_PROD\_JN/CAS-0010688777/snakemake-ez-dpops/R3d\_INTERVALS/19065WBC\_R1.target.interval.list<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/4552'>Zendesk ticket #4552</a>)<br>gz#4552</i>

**Comment by bhanugandham** [comment]
Hi @lbergelson as discussed during the office hrs, I created this issue ticket to brainstorm ideas around how to check for either "@"/"#" identifiers in the interval list file.

**Comment by yfarjoun** [comment]
I think that this is a GATK (not picard) problem.

**Comment by whaleberg** [comment]
It's a barclay problem. We patched barclay to add a warning in the case of an incorrectly labelled interval.list file which should mitigate it.  Waiting on a barclay release though.

**Comment by lbergelson** [comment]
Huh, a mysterious stranger with insight into the problem.  Lets all forget about whoever that person may be.  I'm pretty sure they're correct in their assessment though..

**Comment by yfarjoun** [comment]
lol
