### ISSUE TITLE
CollectSamErrorMetrics fails if a read has a leading insertion and maps to the start of a contig

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#1511]
For example, a 10bp insertion at the start of the mitochondria.  This can happen more often for circular genomes, but also when we turn off soft/hard-clipping in alignment.

```
1	99	chrM	1	60	10I26M	chrM	1	0	AAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNNNNN	AAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBB	RG:Z:62A40.2
```

See https://github.com/samtools/htsjdk/pull/1481

Exception:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at htsjdk.samtools.reference.SamLocusAndReferenceIterator.next(SamLocusAndReferenceIterator.java
:82)
        at htsjdk.samtools.reference.SamLocusAndReferenceIterator.next(SamLocusAndReferenceIterator.java
:42)
        at picard.sam.SamErrorMetric.CollectSamErrorMetrics.processData(CollectSamErrorMetrics.java:356)
        at picard.sam.SamErrorMetric.CollectSamErrorMetrics.doWork(CollectSamErrorMetrics.java:483)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

**Comment by nh13** [comment]
Awaiting an htsjdk release

**Comment by nh13** [comment]
Looks like https://github.com/samtools/htsjdk/pull/1481 got fixed and released and update in https://github.com/broadinstitute/picard/pull/1518.  @lbergelson let me know when you think you'll make a release here and I can help bump bioconda

**Comment by lbergelson** [comment]
@nh13 I don't handle picard releases anymore.  I think @sahakiann is doing them now.  Maybe they can help.  I think it's due for a release new.

**Comment by nh13** [comment]
@sahakiann is it possible to do a release this week so we can have this fix in the wild?

**Comment by lbergelson** [comment]
@nh13 Thanks for the fix / shepherding this through.
