### ISSUE TITLE
CleanSam crashes because of one read with AbstractAlignmentMerger.createNewCigarIfMapsOffEndOfReference

### ISSUE THREAD

**Issue by chrarnold** [broadinstitute/picard#1519]
### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
CleanSam

### Affected version(s)
- Latest public release version

### Description 

CleanSam seems to trip over one read. it seems to run through, ignoring one read with several errors, but in the end, still fails, see below. 
```

14:12:47.197 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:TOOLS/miniconda3/share/picard-2.22.8-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu May 28 14:12:47 CEST 2020] CleanSam INPUT=in.bam OUTPUT=out.bam CREATE_INDEX=true    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu May 28 14:12:47 CEST 2020] Executing as carnold@bla on Linux 3.10.0-1062.12.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 11.0.1-internal+0-adhoc..src; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.22.8

...
[no warning or error for any read until the lalst chromosome]
...
INFO	2020-05-28 14:19:43	CleanSam	Processed    61,000,000 records.  Elapsed time: 00:06:56s.  Time for last 1,000,000:    6s.  Last read position: chrX:123,300,890

Ignoring SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 61567996, Read name SRR7650754.39037696, Mate Alignment start should be 0 because reference name = *.
Ignoring SAM validation error: ERROR::INVALID_FLAG_MATE_UNMAPPED:Record 61567996, Read name SRR7650754.39037696, Mapped mate should have mate reference name
Ignoring SAM validation error: ERROR::INVALID_MAPPING_QUALITY:Record 61567996, Read name SRR7650754.39037696, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 61567996, Read name SRR7650754.39037696, Alignment start should be 0 because reference name = *.
Ignoring SAM validation error: ERROR::INVALID_UNALIGNED_MATE_START:Record 61567996, Read name SRR7650754.39037696, The unaligned mate start position is -1, should be 0

[Thu May 28 14:19:47 CEST 2020] picard.sam.CleanSam done. Elapsed time: 7.01 minutes.
Runtime.totalMemory()=536870912

To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NullPointerException
	at picard.sam.AbstractAlignmentMerger.createNewCigarIfMapsOffEndOfReference(AbstractAlignmentMerger.java:925)
	at picard.sam.AbstractAlignmentMerger.createNewCigarsIfMapsOffEndOfReference(AbstractAlignmentMerger.java:962)
	at picard.sam.CleanSam.doWork(CleanSam.java:88)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

#### Steps to reproduce
I will upload and attach a MWE and minimal BAM file to reproduce the issue.

#### Actual behavior
Exits with an error code > 0

**Comment by chrarnold** [comment]
I updated a MWE to reproduce.Please take a look. Thank you.

**Comment by chrarnold** [comment]
Any comment here?
