### ISSUE TITLE
CollectWGSMetrics failing using FAST_ALGORITHM 

### ISSUE THREAD

**Issue by gbggrant** [broadinstitute/picard#1523]
### Bug Report
Running latest (2.22.9) version of picard, and running CollectWgsMetrics (and I think CollectRawWgsMetrics) with USE_FAST_ALGORITHM=true causes an exception.  Running it in without the FAST ALGORITHM works.

There is an example (on prem) at /seq/tng/ggrant/Support/GL-744/NA12891.bam.  This is a bam generated by the latest version of the WholeGenomeGermlineSingleSample wdl, run using gatk 4.1.7.0.  

Example:
java -jar /seq/software/picard-public/2.22.9/picard.jar  CollectWgsMetrics INPUT=NA12891.bam VALIDATION_STRINGENCY=SILENT REFERENCE_SEQUENCE=/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta INCLUDE_BQ_HISTOGRAM=true INTERVALS=wgs_coverage_regions.hg38.interval_list OUTPUT=NA12891.wgs_metrics USE_FAST_ALGORITHM=true READ_LENGTH=250

To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: The requested position is not covered by this StartEdgingRecordAndOffset object.
	at htsjdk.samtools.util.AbstractRecordAndOffset.validateOffset(AbstractRecordAndOffset.java:146)
	at htsjdk.samtools.util.EdgingRecordAndOffset$StartEdgingRecordAndOffset.getBaseQuality(EdgingRecordAndOffset.java:112)
	at picard.analysis.FastWgsMetricsCollector.excludeByQuality(FastWgsMetricsCollector.java:189)
	at picard.analysis.FastWgsMetricsCollector.processRecord(FastWgsMetricsCollector.java:144)
	at picard.analysis.FastWgsMetricsCollector.addInfo(FastWgsMetricsCollector.java:105)
	at picard.analysis.WgsMetricsProcessorImpl.processFile(WgsMetricsProcessorImpl.java:93)
	at picard.analysis.CollectWgsMetrics.doWork(CollectWgsMetrics.java:231)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

----

### Tool(s) involved
_Tool name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by gbggrant** [comment]
I put a debugger on this and it's failing (with an array index of -7) on this bam record:

`HTL2KCCXX160412:5:1214:2920:10240       99      chr1    790408  27      63M5I73M10S     =       790478  221     ACTCTAATGGAATGGAATGCAAGGGACTGGACTCAAATGGAATGGAATGGAATTGACTCAAATGGTAGGGAAAGGAATTGAATGGACTCGAAAGGATTGGGATGGAGTACAGGGGAATGGACTCGAATGGAATGGAATGGACGGAACTCGA +?55??????????????????????&5????????5????????????????????????????5?+??????????????5??????????????????????????5??5???5???????????????+????5???########## MC:Z:151M       RG:Z:HTL2K.5    MQ:i:27 AS:i:65`

But when I made a sam of that record (and its mate) and ran CollectWgsMetrics with just that file, it did not fail.?  The file is attached

**Comment by gbggrant** [comment]
[test.sam.gz](https://github.com/broadinstitute/picard/files/4800730/test.sam.gz)

**Comment by yfarjoun** [comment]
so the included sam file does or does not fail?

**Comment by gbggrant** [comment]
It did not.  Which confused me.  I originally had a debugger hanging on an instance of the CollectWGSMetrics task and it was throwing an exception on that readgroup (I think the first).  So I cut that out of the bam and created the test sam, and ran it and it worked.  Perhaps I did something wrong?  The big NA12891.bam definitely throws the exception

**Comment by yfarjoun** [comment]
yeah. I see the exception... :-(

**Comment by gbggrant** [comment]
This issue has been resolved.

**Comment by yfarjoun** [comment]
for the record, this was resolved by samtools/htsjdk#1489 and then by taking in those changes in #1537
