### ISSUE TITLE
CollectGcBiasMetrics Array Index Out Of Bounds Exception

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/picard#1532]
This issue was originally reported on the forums, but was put into the [GATK repo](https://github.com/broadinstitute/gatk/issues/6372) instead of Picard, so I'm just porting the ticket to the correct repo.

There seem to be a few Picard tickets with slight variants of this (i.e https://github.com/broadinstitute/picard/issues/1483) - not sure if they're all the same issue or not.

User Report:
Link: https://gatk.broadinstitute.org/hc/en-us/community/posts/360055990891-CollectGcBiasMetrics-Array-Index-Out-Of-Bounds-Exception
Hello,

When running CollectGcBiasMetrics on a moderately sized sam file (~500Mb), picard gives ArrayIndexOutOfBoundsException and "Exception counting mismatches for read ..."

The SCAN_WINDOW_SIZE=1000. When it's set to default value 100, the error message is slightly different but ArrayIndexOutOfBoundsException persists. I have also experimented with different window sizes, all values >1000 give same error at the same read on chrX (details below).

The reference fasta file is taken from UCSC: https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.fa.gz

Any feedback leading to resolving the issue is greatly appreciated.

a) Picard version:

2.21.6-SNAPSHOT

b) Command script:

java -jar picard.jar CollectGcBiasMetrics \

I=sorted.sam \

O=gc_bias_metrics.txt \

CHART=gc_bias_metrics.pdf \

S=summary_metrics.txt \

R=hg19.fa \

SCAN_WINDOW_SIZE=1000

c) Error log:

MINIMUM_GENOME_FRACTION=1.0E-5 IS_BISULFITE_SEQUENCED=false METRIC_ACCUMULATION_LEVEL=[ALL_READS] ALSO_IGNORE_DUPLICATES=false ASSUME_SORTED=true STOP_AFTER=0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false

[Tue Jan 07 16:48:19 PST 2020] Executing as akoch@hpc5-0-3.local on Linux 2.6.32-431.11.2.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_181-b13; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.21.6-SNAPSHOT

INFO 2020-01-07 16:51:24 SinglePassSamProgram Processed 1,000,000 records. Elapsed time: 00:00:33s. Time for last 1,000,000: 27s. Last read position: chr5:92,832,908

INFO 2020-01-07 16:51:53 SinglePassSamProgram Processed 2,000,000 records. Elapsed time: 00:01:01s. Time for last 1,000,000: 28s. Last read position: chr11:121,228,669

[Tue Jan 07 16:52:25 PST 2020] picard.analysis.CollectGcBiasMetrics done. Elapsed time: 4.10 minutes.

Runtime.totalMemory()=4236247040

To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp

Exception in thread "main" htsjdk.samtools.SAMException: Exception counting mismatches for read XXXXXXXX0434501/1 32b aligned to chrX:51305151-51305182.

at htsjdk.samtools.util.SequenceUtil.countMismatches(SequenceUtil.java:490)

at htsjdk.samtools.util.SequenceUtil.countMismatches(SequenceUtil.java:466)

at htsjdk.samtools.util.SequenceUtil.countMismatches(SequenceUtil.java:504)

at picard.analysis.GcBiasMetricsCollector.addRead(GcBiasMetricsCollector.java:389)

at picard.analysis.GcBiasMetricsCollector.access$600(GcBiasMetricsCollector.java:48)

at picard.analysis.GcBiasMetricsCollector$PerUnitGcBiasMetricsCollector.addReadToGcData(GcBiasMetricsCollector.java:221)

at picard.analysis.GcBiasMetricsCollector$PerUnitGcBiasMetricsCollector.acceptRecord(GcBiasMetricsCollector.java:155)

at picard.analysis.GcBiasMetricsCollector$PerUnitGcBiasMetricsCollector.acceptRecord(GcBiasMetricsCollector.java:100)

at picard.metrics.MultiLevelCollector$AllReadsDistributor.acceptRecord(MultiLevelCollector.java:192)

at picard.metrics.MultiLevelCollector.acceptRecord(MultiLevelCollector.java:315)

at picard.analysis.CollectGcBiasMetrics.acceptRead(CollectGcBiasMetrics.java:172)

at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:158)

at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:94)

at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)

at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)

at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

Caused by: java.lang.ArrayIndexOutOfBoundsException: 51305150

at htsjdk.samtools.util.SequenceUtil.countMismatches(SequenceUtil.java:482)

... 15 more

(created from Zendesk ticket #4315)
gz#4315

**Comment by jaiswalok** [comment]
running into a similar issue. Any solutions to this? Thanks!

**Comment by yfarjoun** [comment]
I'm confused about the value of the OOB value: 51305150. this is the base _before_ the start of the alignment. Could you please provide the following information:
- @SQ line for the contig in question (the one that the read is aligned to)
- the actual read (the entire record) that is mentioned in the stack trace.
- your stack trace (if it's different than the one in this ticket...the information I need from there is that OOB value)
