### ISSUE TITLE
After SortSam, file can't be validated with ValidateSam or processed with MarkDuplicates

### ISSUE THREAD

**Issue by maquezaihou** [broadinstitute/picard#155]
Hi,

I have some DNA-Seq data for SNP calling. I did bwa mem (or aln + sampe) alignemnt, but after I sorted the alignment bam file using SortSam (or samtools  sort), the sorted file can't be validated with ValidateSam nor further processed with MarkDuplicates. The same error was thrown out: 
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/ref/Finalizer$2
	at java.lang.ref.Finalizer.runFinalization(Finalizer.java:144)
	at java.lang.Runtime.runFinalization0(Native Method)
	at java.lang.Runtime.runFinalization(Runtime.java:705)
	at java.lang.System.runFinalization(System.java:967)
	at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:58)
	at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:49)
	at htsjdk.samtools.util.ResourceLimitedMap.get(ResourceLimitedMap.java:76)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.getOutputStreamForSequence(CoordinateSortedPairInfoMap.java:180)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.put(CoordinateSortedPairInfoMap.java:164)
	at picard.sam.DiskReadEndsMap.put(DiskReadEndsMap.java:67)
	at picard.sam.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:449)
	at picard.sam.MarkDuplicates.doWork(MarkDuplicates.java:177)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:183)
	at picard.sam.MarkDuplicates.main(MarkDuplicates.java:161)

Anyone knows how to get around that error? Thanks!!!

**Comment by vdauwera** [comment]
Hi @maquezaihou, 

Sorry for the late response. This looks like a problem with your jar file. You should download the latest precompiled jar file and try again. Let us know if the error persists.

**Comment by yfarjoun** [comment]
closed due to lack of interest. if this can be replicated with a current version of picard, please reopen with the logs.
