### ISSUE TITLE
Checkfingerprint sequence dictionary check exception

### ISSUE THREAD

**Issue by gbrandt6** [broadinstitute/picard#1573]
### Affected tool(s)
CheckFingerprint

### Affected version(s)
-Latest release: 4.1.8.1
-Affected version: 4.1.8.1
-Unaffected version:4.1.2.0,4.1.3.0

### Description 
A user wrote into the GATK forum using Checkfingerprint and has a java.lang.NullPointer.Exception. It is pointing to picard.fingerprint.FingerprintChecker.checkDictionaryGoodForFingerprinting(FingerprintChecker.java:214) and may be related to PR #1303 

Is this intentional behavior, does the user need to make changes on their end?

Link to gatk forum post: https://gatk.broadinstitute.org/hc/en-us/community/posts/360072725112-Trouble-running-CheckFingerprint-with-gatk-4-1-8-1

####Command
`gatk CheckFingerprint -I MyBAM.bam --GENOTYPES MyGenotypeVCF.vcf --HAPLOTYPE_MAP MyHapMapVCF.vcf --IGNORE_READ_GROUPS --GENOTYPE_LOD_THRESHOLD 0 --SUMMARY_OUTPUT picard_ID_metrics.tsv --DETAIL_OUTPUT picard_ID_detailMetrics.tsv `

####Stack Trace
```
Using GATK jar /ngs_pipelines/snake_created_conda_envs/a188324a/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar
Running:
java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /ngs_pipelines/snake_created_conda_envs/a188324a/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar CheckFingerprint -I analysis_ready_bam/sample.bam --GENOTYPES tmp_picard_CheckFingerprint/sample_SID_Agena.vcf --HAPLOTYPE_MAP /ngs_pipelines/hg38_reference_files/capture_kits/idt_sample_id/sampleID_AgenaOnlyRefSNPs_ForPicard.vcf --IGNORE_READ_GROUPS --GENOTYPE_LOD_THRESHOLD 0 --SUMMARY_OUTPUT tmp_picard_CheckFingerprint/sample.picard_ID_metrics.tsv --DETAIL_OUTPUT tmp_picard_CheckFingerprint/sample.picard_ID_detailMetrics.tsv
10:13:12.572 INFO NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/ngs_pipelines/snake_created_conda_envs/a188324a/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue Sep 01 10:13:12 ACST 2020] CheckFingerprint --INPUT analysis_ready_bam/sample.bam --SUMMARY_OUTPUT tmp_picard_CheckFingerprint/sample.picard_ID_metrics.tsv --DETAIL_OUTPUT tmp_picard_CheckFingerprint/sample.picard_ID_detailMetrics.tsv --GENOTYPES tmp_picard_CheckFingerprint/sample_SID_Agena.vcf --HAPLOTYPE_MAP /ngs_pipelines/hg38_reference_files/capture_kits/idt_sample_id/sampleID_AgenaOnlyRefSNPs_ForPicard.vcf --GENOTYPE_LOD_THRESHOLD 0.0 --IGNORE_READ_GROUPS true --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
Sep 01, 2020 10:13:12 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
[Tue Sep 01 10:13:12 ACST 2020] Executing as user@server.sa.gov.au on Linux 3.10.0-1062.7.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_192-b01; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.1.8.1
[Tue Sep 01 10:13:13 ACST 2020] picard.fingerprint.CheckFingerprint done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2082471936
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
java.lang.NullPointerException
at picard.fingerprint.FingerprintChecker.checkDictionaryGoodForFingerprinting(FingerprintChecker.java:214)
at picard.fingerprint.FingerprintChecker.loadFingerprints(FingerprintChecker.java:196)
at picard.fingerprint.FingerprintChecker.checkFingerprints(FingerprintChecker.java:748)
at picard.fingerprint.CheckFingerprint.doWork(CheckFingerprint.java:268)
at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
at org.broadinstitute.hellbender.Main.main(Main.java:289)
```<br><br><i>(related to <a href='https://broadinstitute.zendesk.com/agent/tickets/13585'>Zendesk ticket #13585</a>)<br>gz#13585</i>

**Comment by yfarjoun** [comment]
do all the input files have dictionaries?

**Comment by jsoubrier** [comment]
Excellent catch!
My VCF input "_--GENOTYPES tmp_picard_CheckFingerprint/sample_SID_Agena.vcf_" did not have a contig dictionary. I copied the same hg38 dictionary from the HAPLOTYPE_MAP one and it went through with no problem using gatk4-4.1.8.1-0.
I'll implement [UpdateVCFSequenceDictionary](https://gatk.broadinstitute.org/hc/en-us/articles/360037425731-UpdateVCFSequenceDictionary) in the pipeline.

gatk4-4.1.2.0-1 apparently ignored this issue (_i.e.,_ running the same with or without the contig dictionary).

Thanks a lot for the help here @gbrandt6 and @yfarjoun!

BTW, I did not realize how much faster it would be with the latest version:
```
Picard version: Version:4.1.2.0
INFO	2020-09-02 11:38:08	CheckFingerprint	Read Group: null / sample vs. sample: LOD = 0.9884074043597283
[Wed Sep 02 11:38:08 ACST 2020] picard.fingerprint.CheckFingerprint done. Elapsed time: 1.02 minutes.
Runtime.totalMemory()=2196766720

Picard version: Version:4.1.8.1
INFO	2020-09-02 11:36:52	CheckFingerprint	Read Group: null / sample vs. sample: LOD = 0.9884074043597284
[Wed Sep 02 11:36:52 ACST 2020] picard.fingerprint.CheckFingerprint done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=2142240768

```

**Comment by yfarjoun** [comment]
awesome!
