### ISSUE TITLE
Sequence name regex issue in SortSam

### ISSUE THREAD

**Issue by rwinand** [broadinstitute/picard#1574]
### Affected tool(s)
- SortSam

### Affected version(s)
- 2.23.3

### Description
When I try to run SortSam on my file, I get the following error:

```
Exception in thread "main" htsjdk.samtools.SAMException: Sequence name 'ACol-X0348-2020-VARS(H06)-S2' doesn't match regex: '[0-9A-Za-z!#$%&+./:;?@^_|~-][0-9A-Za-z!#$%&*+./:;=?@^_|~-]*' 
	at htsjdk.samtools.SAMSequenceRecord.validateSequenceName(SAMSequenceRecord.java:210)
	at htsjdk.samtools.SAMSequenceRecord.<init>(SAMSequenceRecord.java:93)
	at htsjdk.samtools.SAMTextHeaderCodec.parseSQLine(SAMTextHeaderCodec.java:214)
	at htsjdk.samtools.SAMTextHeaderCodec.decode(SAMTextHeaderCodec.java:113)
	at htsjdk.samtools.SAMTextReader.readHeader(SAMTextReader.java:216)
	at htsjdk.samtools.SAMTextReader.<init>(SAMTextReader.java:63)
	at htsjdk.samtools.SAMTextReader.<init>(SAMTextReader.java:73)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:434)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:208)
	at picard.sam.SortSam.doWork(SortSam.java:152)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:301)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
Exit status: 1
```

This error is caused by the '()' characters in the sequence name. I found that for some tools, there is the paramater READ_NAME_REGEX that can be used but that is not a valid parameter for this tool.

For the moment I went back to version 2.8.3 because there it still works.

Is it possible to change the regex that is used for this on the command line? If not, is there a reason that the parentheses were not included in the default regex because otherwise, I could make try to make a pull request where they are added?

#### Steps to reproduce

Run the following command on any file where the sequence name contains parentheses:

`picard SortSam  I=readmap.sam  O=sorted.bam SORT_ORDER=coordinate CREATE_INDEX=true`

#### Expected behavior

Output a sorted BAM file with index

#### Actual behavior

Exception due to parentheses in the sequence name

**Comment by rwinand** [comment]
After looking into this some more, it found that the issue is a direct result of the SAM specification (e.g. [htsjdk issue #1295](https://github.com/samtools/htsjdk/issues/1295)) and that it is not a issue that can be solved in Picard. Therefore, I will close the issue here and find a workaround or raise an issue at [hts-specs](https://github.com/samtools/hts-specs/issues).
