### ISSUE TITLE
Sequences at index 0 don't match Error in GenotypeConcordance

### ISSUE THREAD

**Issue by montenegrina** [broadinstitute/picard#1575]
### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
Picard version: 2.23.4

### Affected version(s)
- [ ] Latest public release version [version?]
- [ ] Latest development/master branch as of [date of test?]

### Description 
INFO	2020-09-04 15:27:48	GenotypeConcordance	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    GenotypeConcordance -CALL_VCF old.vcf -CALL_SAMPLE 0_fam0110_G110 -O gc_concordance.vcf -TRUTH_VCF new.vcf -TRUTH_SAMPLE 0_fam0110_G110
**********

15:27:48.847 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/projects/com_grassim/anamaria/anamaria/anamaria/gatk-4.1.8.1/picard/build/libs/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Sep 04 15:27:48 CDT 2020] GenotypeConcordance TRUTH_VCF=new.vcf CALL_VCF=old.vcf OUTPUT=gc_concordance.vcf TRUTH_SAMPLE=0_fam0110_G110 CALL_SAMPLE=0_fam0110_G110    OUTPUT_VCF=false INTERSECT_INTERVALS=true MIN_GQ=0 MIN_DP=0 OUTPUT_ALL_ROWS=false USE_VCF_INDEX=false MISSING_SITES_HOM_REF=false IGNORE_FILTER_STATUS=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Fri Sep 04 15:27:48 CDT 2020] Executing as anamaria@login-1.saber.acer.uic.edu on Linux 3.10.0-693.21.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_161-b14; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.23.4-SNAPSHOT
[Fri Sep 04 15:27:48 CDT 2020] picard.vcf.GenotypeConcordance done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2020081664
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequences at index 0 don't match: 0/249139234/1 0/247185616/1
	at htsjdk.samtools.util.SequenceUtil.assertSequenceListsEqual(SequenceUtil.java:272)
	at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:334)
	at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:320)
	at picard.vcf.GenotypeConcordance.doWork(GenotypeConcordance.java:344)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:301)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

#### Steps to reproduce

java -jar picard.jar GenotypeConcordance \
CALL_VCF=old.vcf \
CALL_SAMPLE=0_fam0110_G110 \
O=gc_concordance.vcf \
TRUTH_VCF=new.vcf \
TRUTH_SAMPLE=0_fam0110_G110 

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) involved
_Tool name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) involved
_Tool name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by pshapiro4broad** [comment]
Can you share test data that reproduces this problem? Minimal VCFs would be nice to make it easier to share the files.

**Comment by montenegrina** [comment]
Hi

Thanks for getting back to me. Can you please tell me which command I can
use to extract the reproducible example from my old.vcf.gz and new.vcf.gz
files?

Also I on the same set of files I was able to run this without error:

gatk Concordance -R human_g1k_v37.fasta -eval new.vcf.gz --truth old.vcf.gz
--summary summary.tsv
