### ISSUE TITLE
Allow underscores in barcode tags when using BARCODE_TAG option in MarkDuplicates

### ISSUE THREAD

**Issue by ghuls** [broadinstitute/picard#1579]
### Tool(s) involved
MarkDuplicates with `BARCODE_TAG` option

### Description

Allow `_` to appear in barcode tags.

My BAM file is made with STAR solo and uses a cell barcode whitelist which consists of 3 10bp barcodes
which get encoded as `CB:Z:AGGACATGAA_AAGGTGTGGT_TACGACGATG` in the BAM file.

STAR command to generate the BAM file (`--soloCBwhitelist bc1.txt bc2.txt bc3.txt` is responsable for the `CB:Z:AGGACATGAA_AAGGTGTGGT_TACGACGATG` format):
```bash
STAR \
    --runMode alignReads \
    --runThreadN 24 \
    --genomeDir ${genome_dir} \
    --readFilesIn ${fastq1} ${fastq2} \
    --readFilesCommand "gzip -c -d" \
    --outFileNamePrefix ${output_prefix} \
    --outReadsUnmapped Fastx \
    --outSAMtype BAM SortedByCoordinate \
    --outSAMattributes NH HI AS nM CB UB CR CY UR UY \
    --outFilterMultimapNmax 1 \
    --alignIntronMin 20 \
    --alignIntronMax 100000 \
    --alignEndsType Local \
    --sjdbGTFfile ${gtf} \
    --sjdbGTFfeatureExon exon \
    --soloType CB_UMI_Complex \
    --soloCBwhitelist bc1.txt bc2.txt bc3.txt \
    --soloCBmatchWLtype 1MM \
    --soloCBposition 0_0_0_9   0_20_0_29   0_40_0_49 \
    --soloUMIposition 0_55_0_64 \
    --soloCellFilter None
```

Excerpt from the BAM file:
```
NB501171:585:HLM2TBGXG:3:21410:20944:11818      0       chr1    3005850 255     91M     *       0       0       CCAATCCAGCTGTGGCACCTGTGGACCACAACAAAGACTAGCTTGACACAATAACCCTAAGGGTATACTAGTGACATGCAGTAACTATGAT     AAAAAEEAEEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEEAEAEEAAEEAEEAA/EEEEEEEEEAAEAE6EE<E<AEAA//E<EE/E/     NH:i:1  HI:i:1  AS:i:89 nM:i:0  CR:Z:AGGACATGAA_AAGGTGTGGT_TACGACGATG   CY:Z:AAAAAEEEEE_EEEEEEEEEE_EEEAEE<EEE   UR:Z:CAAGACGCGC UY:Z:AAAAAAAAAA CB:Z:AGGACATGAA_AAGGTGTGGT_TACGACGATG   UB:Z:CAAGACGCGC
NB501171:585:HLM2TBGXG:3:22408:2332:9008        0       chr1    3005850 255     91M     *       0       0       CCAATCCAGCTGTGGCACCTGTGGACCACAACAAAGACTAGCTTGACACAATAACCCTAAGGGTATACTAGTGACATGCAGTAACTATGAT     AAAAAEEEEEEEEEEE/EEEEEEEEAE/EEEEEA/EEEEEEE<<E/EEEEEEE/EA<AEEEEAEEEEEEEEEEEE/EEE/<AEAAEE<AEE     NH:i:1  HI:i:1  AS:i:89 nM:i:0  CR:Z:AGGACATGAA_AAGGTGTGGT_TACGACGATG   CY:Z:AAAAAEEEEE_EEEE<EEEEE_EEEAEEEEE<   UR:Z:CGCACAGGGC UY:Z:AAAAAAAAAA CB:Z:AGGACATGAA_AAGGTGTGGT_TACGACGATG   UB:Z:CGCACAGGGC
NB501171:585:HLM2TBGXG:1:11108:3124:7932        0       chr1    3011820 255     91M     *       0       0       GTATTTATATATCAATTCAATCACTATCCCAGGTTCTCTTTTGATTATCCCATGAGTAACCACTTTATGATTTAAGAGCCTTGATTCATAT     AAAAAEEEEEEEEE6EEEEEEEEEEEEEE6EEEEE<AEEEAEEAEEEAA<EEEEEEEE/EEEEEEEEEEEEAEE/EE/AEEE/E<AAEEEE     NH:i:1  HI:i:1  AS:i:89 nM:i:0  CR:Z:ACTCGCAATG_CTGATATTCA_CTTATCAGGA   CY:Z:AAAAAEEEEE_AEEEEEEEEE_EEEEEEEEEE   UR:Z:AAGCCGCGGG UY:Z:AAAAAAAAAA CB:Z:ACTCGCAATG_CTGATATTCA_CTTATCAGGA   UB:Z:AAGCCGCGGG
NB501171:585:HLM2TBGXG:1:22104:17956:2555       0       chr1    3011820 255     91M     *       0       0       GTATTTATATATCAATTCAATCACTATCCCAGGTTCTCTTTTGATTATCCCATGAGTAACCACTTTATGATTTAAGAGCCTTGATTCATAT     AAAAAEEEEEEEEE/EAEEAEEEEEEEEEEEEEEEEAEEEEEAEAEEEEEEEEEEAEEAEEEAEEEEEEE<AEEE/A<E<E<<EAEAA/E<     NH:i:1  HI:i:1  AS:i:89 nM:i:0  CR:Z:ACTCGCAATG_CTGATATTCA_CTTATCAGGA   CY:Z:AAAAAEEEEE_EEEEEEEEEE_EEEEEEEEEE   UR:Z:CACCCGCACA UY:Z:AAAAAAAAAA CB:Z:ACTCGCAATG_CTGATATTCA_CTTATCAGGA   UB:Z:CACCCGCACA
NB501171:585:HLM2TBGXG:4:21409:7740:19553       0       chr1    3011820 255     91M     *       0       0       GTATTTATATATCAATTCAATCACTATCCCAGGTTCTCTTTTGATTATCCCATGAGTAACCACTTTATGATTTAAGAGCCTTGATTCATAT     AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEAEEE<EEEEEEEE/EEEEEAEEEEAEEEEEEA<E<6E<EEEEE<EE     NH:i:1  HI:i:1  AS:i:89 nM:i:0  CR:Z:ACTCGCAATG_CTGATATTCA_CTTATCAGGA   CY:Z:AAAAAEEEEE_EEEEEEEEEE_AAEEEEEEEA   UR:Z:ACACGAAACC UY:Z:AAAAAAAAAA CB:Z:ACTCGCAATG_CTGATATTCA_CTTATCAGGA   UB:Z:ACACGAAACC
```

```bash
mark_duplicates () {
    local input_bam_file="${1}";
    local output_bam_file="${2}";

    module --ignore-cache load picard/2.23.4-Java-1.8.0

    java -Dpicard.useLegacyParser=false -jar $EBROOTPICARD/picard.jar MarkDuplicates \
        -I "${input_bam_file}" \
        -O "${output_bam_file}" \
        -M "${output_bam_file%.bam}.mark_duplicates_metrics.txt" \
        -BARCODE_TAG CB \
        -REMOVE_DUPLICATES true \
        -OPTICAL_DUPLICATE_PIXEL_DISTANCE 100

    return $?
}

mark_duplicates input.bam output.dedup.bam
```

It gives the following crash:

```
❯ mark_duplicates input.bam output.dedup.bam
To execute picard run: java -jar $EBROOTPICARD/picard.jar

17:11:40.772 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/vsc-hard-mounts/leuven-data/software/biomed/skylake_centos7/2018a/software/picard/2.23.4-Java-1.8.0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Sep 18 17:11:40 CEST 2020] MarkDuplicates  --BARCODE_TAG CB --INPUT input.bam --OUTPUT output.dedup.bam --METRICS_FILE output.dedup.mark_duplicates_metrics.txt --REMOVE_DUPLICATES true --OPTICAL_DUPLICATE_PIXEL_DISTANCE 100  --MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP 50000 --MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 8000 --SORTING_COLLECTION_SIZE_RATIO 0.25 --TAG_DUPLICATE_SET_MEMBERS false --REMOVE_SEQUENCING_DUPLICATES false --TAGGING_POLICY DontTag --CLEAR_DT true --DUPLEX_UMI false --ADD_PG_TAG_TO_READS true --ASSUME_SORTED false --DUPLICATE_SCORING_STRATEGY SUM_OF_BASE_QUALITIES --PROGRAM_RECORD_ID MarkDuplicates --PROGRAM_GROUP_NAME MarkDuplicates --READ_NAME_REGEX <optimized capture of last three ':' separated fields as numeric values> --MAX_OPTICAL_DUPLICATE_SET_SIZE 300000 --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Fri Sep 18 17:11:40 CEST 2020] Executing as vsc30366@r23i27n22 on Linux 3.10.0-1127.18.2.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_221-b11; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: Version:2.20.5-SNAPSHOT
INFO    2020-09-18 17:11:40     MarkDuplicates  Start of doWork freeMemory: 2037340912; totalMemory: 2058354688; maxMemory: 28631367680
INFO    2020-09-18 17:11:40     MarkDuplicates  Reading input file and constructing read end information.
INFO    2020-09-18 17:11:40     MarkDuplicates  Will retain up to 88368418 data points before spilling to disk.
[Fri Sep 18 17:11:41 CEST 2020] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2058354688
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: UMI found with illegal characters.  UMIs must match the regular expression ^[ATCGNatcgn-]*$.
        at picard.sam.markduplicates.UmiUtil.getTopStrandNormalizedUmi(UmiUtil.java:73)
        at picard.sam.markduplicates.MarkDuplicates.buildReadEnds(MarkDuplicates.java:699)
        at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:571)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

Wnen replacing the underscores with dashes for the CB tag, picard MarkDuplicates runs fine.
```
NB501171:585:HLM2TBGXG:3:21410:20944:11818      0       chr1    3005850 255     91M     *       0       0       CCAATCCAGCTGTGGCACCTGTGGACCACAACAAAGACTAGCTTGACACAATAACCCTAAGGGTATACTAGTGACATGCAGTAACTATGAT     AAAAAEEAEEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEEAEAEEAAEEAEEAA/EEEEEEEEEAAEAE6EE<E<AEAA//E<EE/E/     NH:i:1  HI:i:1  AS:i:89 nM:i:0  CR:Z:AGGACATGAA_AAGGTGTGGT_TACGACGATG   CY:Z:AAAAAEEEEE_EEEEEEEEEE_EEEAEE<EEE   UR:Z:CAAGACGCGC UY:Z:AAAAAAAAAA CB:Z:AGGACATGAA-AAGGTGTGGT-TACGACGATG   UB:Z:CAAGACGCGC
NB501171:585:HLM2TBGXG:3:22408:2332:9008        0       chr1    3005850 255     91M     *       0       0       CCAATCCAGCTGTGGCACCTGTGGACCACAACAAAGACTAGCTTGACACAATAACCCTAAGGGTATACTAGTGACATGCAGTAACTATGAT     AAAAAEEEEEEEEEEE/EEEEEEEEAE/EEEEEA/EEEEEEE<<E/EEEEEEE/EA<AEEEEAEEEEEEEEEEEE/EEE/<AEAAEE<AEE     NH:i:1  HI:i:1  AS:i:89 nM:i:0  CR:Z:AGGACATGAA_AAGGTGTGGT_TACGACGATG   CY:Z:AAAAAEEEEE_EEEE<EEEEE_EEEAEEEEE<   UR:Z:CGCACAGGGC UY:Z:AAAAAAAAAA CB:Z:AGGACATGAA-AAGGTGTGGT-TACGACGATG   UB:Z:CGCACAGGGC
NB501171:585:HLM2TBGXG:1:11108:3124:7932        0       chr1    3011820 255     91M     *       0       0       GTATTTATATATCAATTCAATCACTATCCCAGGTTCTCTTTTGATTATCCCATGAGTAACCACTTTATGATTTAAGAGCCTTGATTCATAT     AAAAAEEEEEEEEE6EEEEEEEEEEEEEE6EEEEE<AEEEAEEAEEEAA<EEEEEEEE/EEEEEEEEEEEEAEE/EE/AEEE/E<AAEEEE     NH:i:1  HI:i:1  AS:i:89 nM:i:0  CR:Z:ACTCGCAATG_CTGATATTCA_CTTATCAGGA   CY:Z:AAAAAEEEEE_AEEEEEEEEE_EEEEEEEEEE   UR:Z:AAGCCGCGGG UY:Z:AAAAAAAAAA CB:Z:ACTCGCAATG-CTGATATTCA-CTTATCAGGA   UB:Z:AAGCCGCGGG
NB501171:585:HLM2TBGXG:1:22104:17956:2555       0       chr1    3011820 255     91M     *       0       0       GTATTTATATATCAATTCAATCACTATCCCAGGTTCTCTTTTGATTATCCCATGAGTAACCACTTTATGATTTAAGAGCCTTGATTCATAT     AAAAAEEEEEEEEE/EAEEAEEEEEEEEEEEEEEEEAEEEEEAEAEEEEEEEEEEAEEAEEEAEEEEEEE<AEEE/A<E<E<<EAEAA/E<     NH:i:1  HI:i:1  AS:i:89 nM:i:0  CR:Z:ACTCGCAATG_CTGATATTCA_CTTATCAGGA   CY:Z:AAAAAEEEEE_EEEEEEEEEE_EEEEEEEEEE   UR:Z:CACCCGCACA UY:Z:AAAAAAAAAA CB:Z:ACTCGCAATG-CTGATATTCA-CTTATCAGGA   UB:Z:CACCCGCACA
NB501171:585:HLM2TBGXG:4:21409:7740:19553       0       chr1    3011820 255     91M     *       0       0       GTATTTATATATCAATTCAATCACTATCCCAGGTTCTCTTTTGATTATCCCATGAGTAACCACTTTATGATTTAAGAGCCTTGATTCATAT     AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEAEEE<EEEEEEEE/EEEEEAEEEEAEEEEEEA<E<6E<EEEEE<EE     NH:i:1  HI:i:1  AS:i:89 nM:i:0  CR:Z:ACTCGCAATG_CTGATATTCA_CTTATCAGGA   CY:Z:AAAAAEEEEE_EEEEEEEEEE_AAEEEEEEEA   UR:Z:ACACGAAACC UY:Z:AAAAAAAAAA CB:Z:ACTCGCAATG-CTGATATTCA-CTTATCAGGA   UB:Z:ACACGAAACC
```

Allowing understores in the barcode tag would be a huge help.

**Comment by theheking** [comment]
Hi I just want to echo that this would be a really useful feature
