### ISSUE TITLE
AddOrReplaceReadGroups error: "Alignments added out of order in SAMFileWriterImpl.addAlignment"

### ISSUE THREAD

**Issue by moldach** [broadinstitute/picard#1587]
I'm getting the following error from running `picard:latest`:

` java -jar /usr/picard/picard.jar AddOrReplaceReadGroups I=alignment/razers3/tmp/MTG324.bam O=alignment/razers3/MTG324.bam RGID=MTG324 RGLB=lib1 RGPL=ILLUMINA RGSM=MTG324 RGPU=unit1 SORT_ORDER=coordinate`

### Brief

`Exception in thread "main" java.lang.IllegalArgumentException: Alignments added out of order in SAMFileWriterImpl.addAlignment for file:///scratch/moldach/MTG-workflows/alignment/razers3/MTG324.bam. Sort order is coordinate. Offending records are at [I:219] and [I:180]`

### Full

```
Workflow defines that rule get_vep_cache is eligible for caching between workflows (use the --cache argument to enable this).
Building DAG of jobs...
Using shell: /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	add_RG_to_razers3
	1

[Thu Oct  1 12:09:27 2020]
rule add_RG_to_razers3:
    input: alignment/razers3/tmp/MTG324.bam
    output: alignment/razers3/MTG324.bam
    log: MTG324_picard.log
    jobid: 0
    wildcards: sample=MTG324
    resources: mem=200, time=5


                java -jar /usr/picard/picard.jar AddOrReplaceReadGroups I=alignment/razers3/tmp/MTG324.bam O=alignment/razers3/MTG324.bam RGID=MTG324 RGLB=lib1 RGPL=ILLUMINA RGSM=MTG324 RGPU=unit1 SORT_ORDER=coordinate
                
Activating singularity image /home/moldach/projects/def-mtarailo/common/snakemake_cache/singularity_images/05ac22873a34d65b25b9e750fb82b7e5.simg
INFO	2020-10-01 19:09:29	AddOrReplaceReadGroups	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    AddOrReplaceReadGroups -I alignment/razers3/tmp/MTG324.bam -O alignment/razers3/MTG324.bam -RGID MTG324 -RGLB lib1 -RGPL ILLUMINA -RGSM MTG324 -RGPU unit1 -SORT_ORDER coordinate
**********


19:09:30.620 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/picard/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Oct 01 19:09:30 UTC 2020] AddOrReplaceReadGroups INPUT=alignment/razers3/tmp/MTG324.bam OUTPUT=alignment/razers3/MTG324.bam SORT_ORDER=coordinate RGID=MTG324 RGLB=lib1 RGPL=ILLUMINA RGPU=unit1 RGSM=MTG324    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Oct 01 19:09:30 UTC 2020] Executing as moldach@cdr650.int.cedar.computecanada.ca on Linux 3.10.0-1062.12.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_265-b01; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.23.5-3-gc631f56-SNAPSHOT
INFO	2020-10-01 19:09:30	AddOrReplaceReadGroups	Created read-group ID=MTG324 PL=ILLUMINA LB=lib1 SM=MTG324

[Thu Oct 01 19:09:30 UTC 2020] picard.sam.AddOrReplaceReadGroups done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2041446400
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Alignments added out of order in SAMFileWriterImpl.addAlignment for file:///scratch/moldach/MTG-workflows/alignment/razers3/MTG324.bam. Sort order is coordinate. Offending records are at [I:219] and [I:180]
	at htsjdk.samtools.SAMFileWriterImpl.assertPresorted(SAMFileWriterImpl.java:197)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:184)
	at picard.sam.AddOrReplaceReadGroups.doWork(AddOrReplaceReadGroups.java:184)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:301)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
[Thu Oct  1 12:09:31 2020]
Error in rule add_RG_to_razers3:
    jobid: 0
    output: alignment/razers3/MTG324.bam
    log: MTG324_picard.log (check log file(s) for error message)
    shell:
        
                java -jar /usr/picard/picard.jar AddOrReplaceReadGroups I=alignment/razers3/tmp/MTG324.bam O=alignment/razers3/MTG324.bam RGID=MTG324 RGLB=lib1 RGPL=ILLUMINA RGSM=MTG324 RGPU=unit1 SORT_ORDER=coordinate
                
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job add_RG_to_razers3 since they might be corrupted:
alignment/razers3/MTG324.bam
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by moldach** [comment]
This issue occurs when running on un-sorted `BAM`s.

Could either:

A) better error be provided so users don't think `SORT_ORDER=coordinate` does this for them _on-the-fly_ - _i.e._ tell them you must sort data first.

B) include the option to `SORT` with `AddOrReplaceReadGroups`

**Comment by yfarjoun** [comment]
What does the header of the (input) file say about the sort order?

**Comment by yfarjoun** [comment]
The reason I ask is that if the input is stated to be coordinate-sorted, the code will shortcut and not sort the output since the sort orders are supposed to agree....then the output validation catches the out-of-order records and throws an exception.
