### ISSUE TITLE
Can somebody explain these extremely unhelpful messages please

### ISSUE THREAD

**Issue by 7PintsOfCherryGarcia** [broadinstitute/picard#1590]
### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
_Tool name(s), special parameters?_

### Affected version(s)
- [x] Latest public release version [version?]
- [ ] Latest development/master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem and provide a minimal test case._

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) involved
_Tool name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) involved
_Tool name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by 7PintsOfCherryGarcia** [comment]
INFO	2020-10-02 10:52:45	MarkDuplicates	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    MarkDuplicates -REMOVE_DUPLICATES TRUE -INPUT CZ100L1.bam -OUTPUT CZ100L1dedup.bam -METRICS_FILE picardmetrics
**********


10:52:46.371 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/science/willerslev/users-shared/science-snm-willerslev-jmn549/Software/picard_tools/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Oct 02 10:52:46 CEST 2020] MarkDuplicates INPUT=[CZ100L1.bam] OUTPUT=CZ100L1dedup.bam METRICS_FILE=picardmetrics REMOVE_DUPLICATES=true    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag CLEAR_DT=true DUPLEX_UMI=false ADD_PG_TAG_TO_READS=true ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Fri Oct 02 10:52:46 CEST 2020] Executing as jmn549@a00709.science.domain on Linux 3.10.0-1062.12.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_242-b08; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.23.6
INFO	2020-10-02 10:52:46	MarkDuplicates	Start of doWork freeMemory: 102352072864; totalMemory: 102900432896; maxMemory: 190887493632
INFO	2020-10-02 10:52:46	MarkDuplicates	Reading input file and constructing read end information.
INFO	2020-10-02 10:52:46	MarkDuplicates	Will retain up to 691621353 data points before spilling to disk.
INFO	2020-10-02 10:53:11	MarkDuplicates	Read     1,000,000 records.  Elapsed time: 00:00:14s.  Time for last 1,000,000:   14s.  Last read position: contig1916:982
INFO	2020-10-02 10:53:11	MarkDuplicates	Tracking 47174 as yet unmatched pairs. 6 records in RAM.
INFO	2020-10-02 10:53:24	MarkDuplicates	Read     2,000,000 records.  Elapsed time: 00:00:27s.  Time for last 1,000,000:   13s.  Last read position: contig28429:345
INFO	2020-10-02 10:53:24	MarkDuplicates	Tracking 72136 as yet unmatched pairs. 1502 records in RAM.
INFO	2020-10-02 10:53:38	MarkDuplicates	Read     3,000,000 records.  Elapsed time: 00:00:40s.  Time for last 1,000,000:   13s.  Last read position: contig38483:2,448
INFO	2020-10-02 10:53:38	MarkDuplicates	Tracking 102401 as yet unmatched pairs. 9070 records in RAM.
INFO	2020-10-02 10:54:25	MarkDuplicates	Read     4,000,000 records.  Elapsed time: 00:01:28s.  Time for last 1,000,000:   47s.  Last read position: contig4474:1,313
INFO	2020-10-02 10:54:25	MarkDuplicates	Tracking 122513 as yet unmatched pairs. 21880 records in RAM.
[Fri Oct 02 10:55:09 CEST 2020] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 2.39 minutes.
Runtime.totalMemory()=102900432896
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: /tmp/jmn549/CSPI.6371056538491718258.tmp/6881.tmpnot found
	at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:64)
	at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:49)
	at htsjdk.samtools.util.ResourceLimitedMap.get(ResourceLimitedMap.java:76)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.getOutputStreamForSequence(CoordinateSortedPairInfoMap.java:180)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.put(CoordinateSortedPairInfoMap.java:164)
	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.put(DiskBasedReadEndsForMarkDuplicatesMap.java:65)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:566)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:301)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
Caused by: java.io.FileNotFoundException: /tmp/jmn549/CSPI.6371056538491718258.tmp/6881.tmp (Too many open files)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:61)
	... 10 more
