### ISSUE TITLE
Issue with SV Liftover

### ISSUE THREAD

**Issue by parvathisudha** [broadinstitute/picard#1602]
Hi,

I am trying to Liftover my vcf files from Panel analysis. The snvs and indwells were successfully completed. But, I am having trouble doing the "structural variants". Log shows, it has problem in two locations. This sample has 22 structural variants, but none of them got Liftover to hg38. Can you please explain this? 

I am attached the Error report here. 

----

## Log Report
picard.vcf.LiftoverVcf INPUT=/manta/Sample2/results/variants/somaticSV.vcf OUTPUT=/Liftover_vcf_hg38/sample_S2_somaticSV_hg38.vcf CHAIN=hg19ToHg38.over.chain REJECT=/Liftover_vcf_hg38/sample2_rejected_SV.vcf REFERENCE_SEQUENCE=/ref_genome/GATK/gatk-bundle/hg38/Homo_sapiens_assembly38.fasta    WARN_ON_MISSING_CONTIG=false WRITE_ORIGINAL_POSITION=false LIFTOVER_MIN_MATCH=1.0 ALLOW_MISSING_FIELDS_IN_HEADER=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Fri Oct 30 10:20:59 EDT 2020] Executing on Linux 3.10.0-1127.19.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_262-b10; Picard version: 2.10.0-SNAPSHOT
INFO	2020-10-30 10:21:00	LiftoverVcf	Loading up the target reference genome.
INFO	2020-10-30 10:21:13	LiftoverVcf	Lifting variants over and sorting.
INFO	2020-10-30 10:21:14	LiftOver	Interval chr2:89132268-89442060 failed to match chain 1 because intersection length 309770 < minMatchSize 309793.0 (0.99992573 < 1.0)
INFO	2020-10-30 10:21:14	LiftOver	Interval chr14:106177538-106326380 failed to match chain 15 because intersection length 148581 < minMatchSize 148843.0 (0.99823976 < 1.0)
[Fri Oct 30 10:21:14 EDT 2020] picard.vcf.LiftoverVcf done. Elapsed time: 0.24 minutes.
Runtime.totalMemory()=4205838336
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.tribble.TribbleException: Badly formed variant context at location chr14:105862800; getEnd() was 105862800 but this VariantContext contains an END key with value 106329010
	at htsjdk.variant.variantcontext.VariantContext.validateStop(VariantContext.java:1321)
	at htsjdk.variant.variantcontext.VariantContext.validate(VariantContext.java:1294)
	at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:401)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:494)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:488)
	at picard.vcf.LiftoverVcf.tryToAddVariant(LiftoverVcf.java:327)
	at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:247)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)

**Comment by jjfarrell** [comment]
I also got saw this error and the issue was submitted #1552.   The INFO/END field is not being lifted over and is triggering the error when the original INFO/END is before the liftover start position.  Still not resolved.
