### ISSUE TITLE
getting error in MarkDuplicates

### ISSUE THREAD

**Issue by shanmugavadivelps** [broadinstitute/picard#1604]
Sir, I am using picard tool to mark duplicates in .bam file and getting following error.
picard MarkDuplicates -I icc67RAW.bam -O marked_icc6733.bam -M mcs.txt
11:14:16.603 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/iipruser/yes/share/picard-2.23.8-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Nov 11 11:14:16 IST 2020] MarkDuplicates --INPUT icc67RAW.bam --OUTPUT marked_icc6733.bam --METRICS_FILE mcs.txt --MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP 50000 --MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 8000 --SORTING_COLLECTION_SIZE_RATIO 0.25 --TAG_DUPLICATE_SET_MEMBERS false --REMOVE_SEQUENCING_DUPLICATES false --TAGGING_POLICY DontTag --CLEAR_DT true --DUPLEX_UMI false --ADD_PG_TAG_TO_READS true --REMOVE_DUPLICATES false --ASSUME_SORTED false --DUPLICATE_SCORING_STRATEGY SUM_OF_BASE_QUALITIES --PROGRAM_RECORD_ID MarkDuplicates --PROGRAM_GROUP_NAME MarkDuplicates --READ_NAME_REGEX <optimized capture of last three ':' separated fields as numeric values> --OPTICAL_DUPLICATE_PIXEL_DISTANCE 100 --MAX_OPTICAL_DUPLICATE_SET_SIZE 300000 --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Wed Nov 11 11:14:16 IST 2020] Executing as iipruser@iipr on Linux 4.19.0-6-amd64 amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: Version:2.23.8
INFO	2020-11-11 11:14:16	MarkDuplicates	Start of doWork freeMemory: 501694904; totalMemory: 514850816; maxMemory: 1908932608
INFO	2020-11-11 11:14:16	MarkDuplicates	Reading input file and constructing read end information.
INFO	2020-11-11 11:14:16	MarkDuplicates	Will retain up to 6916422 data points before spilling to disk.
WARNING	2020-11-11 11:14:16	AbstractOpticalDuplicateFinderCommandLineProgram	A field field parsed out of a read name was expected to contain an integer and did not. Read name: SRR5183158.19928893. Cause: String 'SRR5183158.19928893' did not start with a parsable number.
INFO	2020-11-11 11:14:22	MarkDuplicates	Read     1,000,000 records.  Elapsed time: 00:00:05s.  Time for last 1,000,000:    5s.  Last read position: NC_021160.1:13,997,847
INFO	2020-11-11 11:14:22	MarkDuplicates	Tracking 42977 as yet unmatched pairs. 1704 records in RAM.
[Wed Nov 11 11:14:30 IST 2020] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.23 minutes.
Runtime.totalMemory()=1479540736
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: /tmp/iipruser/CSPI.941376537499226672.tmp/5266.tmpnot found
	at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:64)
	at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:49)
	at htsjdk.samtools.util.ResourceLimitedMap.get(ResourceLimitedMap.java:76)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.getOutputStreamForSequence(CoordinateSortedPairInfoMap.java:180)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.put(CoordinateSortedPairInfoMap.java:164)
	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.put(DiskBasedReadEndsForMarkDuplicatesMap.java:65)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:566)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:303)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
Caused by: java.io.FileNotFoundException: /tmp/iipruser/CSPI.941376537499226672.tmp/5266.tmp (Too many open files)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:61)
	... 10 more

pls help me to solve this

**Comment by yfarjoun** [comment]
it looks like markduplicates is trying to open more files than your system allows....did you look at the MAX_FILE_HANDLES_FOR_READ_ENDS_MAP argument?

**Comment by shanmugavadivelps** [comment]
I will try and update you sir. thanks for your suggestion and support.
