### ISSUE TITLE
vcfliftover error

### ISSUE THREAD

**Issue by yyshi1** [broadinstitute/picard#1636]
### Affected tool(s)
picard

### Affected version(s)
- [ ] Latest public release version [version?]
- [ ] Latest development/master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._
[Thu Jan 28 17:23:30 EST 2021] Executing as vhabhsshiy@lnx012 on Linux 3.10.0-1127.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_151-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.24.1
INFO    2021-01-28 17:23:30     LiftoverVcf     Loading up the target reference genome.
INFO    2021-01-28 17:23:46     LiftoverVcf     Lifting variants over and sorting (not yet writing the output file.)
[Thu Jan 28 17:23:49 EST 2021] picard.vcf.LiftoverVcf done. Elapsed time: 0.33 minutes.
Runtime.totalMemory()=4580179968
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 37: unparsable vcf record with allele -, for input source: file:///group/operations/op_tech/snp/data/tickets/rel4/gDacs_223/chrXp.01.GroupA.vcf
        at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:887)
        at htsjdk.variant.vcf.AbstractVCFCodec.checkAllele(AbstractVCFCodec.java:678)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseSingleAltAllele(AbstractVCFCodec.java:706)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseAlleles(AbstractVCFCodec.java:645)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:443)
        at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:384)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:328)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:48)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:70)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:37)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.readNextRecord(TribbleIndexedFeatureReader.java:375)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:354)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:315)
        at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:411)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:304)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

#### Steps to reproduce
java -jar /group/operations/op_tech/tools/picard/picard-2.24.1/picard.jar LiftoverVcf \
     I=chrXp.01.GroupA.vcf \
     O=chrXp.01.GroupA_lifted_over.vcf \
     CHAIN=/group/operations/op_tech/resources/hg19ToHg38.over.chain \
     REJECT=rejected_variants.vcf \
     R=/group/operations/op_tech/resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) involved
_Tool name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) involved
_Tool name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by yyshi1** [comment]
Could you delete the ticket from the database?

**Comment by yfarjoun** [comment]
closing it is good enough.
