### ISSUE TITLE
ExtractIlluminaBarcodes: no output is produced, all PerTileBarcodeExtractors fail

### ISSUE THREAD

**Issue by akt68** [broadinstitute/picard#1674]
### Affected tool(s)
ExtractIlluminaBarcodes

### Affected version(s)
-  [x] Latest public release version [2.25.3]

### Description 
ExtractIlluminaBarcodes in Picard version 2.25.3 does not produce any output barcode files or metrics. It reports an ERROR for each tile (see below). The same command worked as expected, without error, with the same input data in version 2.25.2 and earlier versions (I tested 2.24.2 and 2.20.8). Excerpts from log:

ERROR   2021-04-29 23:59:36     ExtractIlluminaBarcodes Error processing tile 1102
picard.PicardException: No barcode files found in the barcodesDirectory /testdir1/Data/Intensities/BaseCalls
        at picard.illumina.parser.NewIlluminaDataProvider.<init>(NewIlluminaDataProvider.java:81)
        at picard.illumina.parser.IlluminaDataProviderFactory.makeDataProvider(IlluminaDataProviderFactory.java:245)
        at picard.illumina.parser.IlluminaDataProviderFactory.makeDataProvider(IlluminaDataProviderFactory.java:228)
        at picard.illumina.ExtractIlluminaBarcodes$PerTileBarcodeExtractor.run(ExtractIlluminaBarcodes.java:681)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
ERROR   2021-04-29 23:59:36     ExtractIlluminaBarcodes Error processing tile 1104

#### Steps to reproduce
Command used:
ExtractIlluminaBarcodes BASECALLS_DIR=/testdir1/Data/Intensities/BaseCalls OUTPUT_DIR=testdir2 LANE=1 READ_STRUCTURE=151T8B8B151T BARCODE_FILE=barcode_file.txt METRICS_FILE=barcode_metrics.txt MAX_MISMATCHES=2 MIN_MISMATCH_DELTA=2 MAX_NO_CALLS=2 MINIMUM_BASE_QUALITY=0 MINIMUM_QUALITY=2 COMPRESS_OUTPUTS=true NUM_PROCESSORS=4 COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=2000000    DISTANCE_MODE=HAMMING VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false

Note that the BASECALLS_DIR is read-only and therefore the specified OUTPUT_DIR is separate.

#### Expected behavior
Output one barcode file per tile and a metrics file. Previous versions produced one 17-18MB barcode file per tile and a metrics file using the exact same command and input data.

#### Actual behavior
No output barcode files or metrics file are produced.

**Comment by gbggrant** [comment]
Thank you for finding this bug.  We have a fix for it underway.

**Comment by gbggrant** [comment]
Hi @akt68 this bug was fixed in Release [2.25.4](https://github.com/broadinstitute/picard/releases/tag/2.25.4) - thanks for finding it so quickly.
