### ISSUE TITLE
Picard FixVcfHeader possible bug

### ISSUE THREAD

**Issue by NTNguyen13** [broadinstitute/picard#1681]
### Affected tool(s)
FixVcfHeader, version 2.25.4

### Description 

When I run FixVcfHeader on union SV set from Genome in a bottle, I ran into a problem, but the log isn't clear for me.

```
java -jar /home/nguyen/picard.jar FixVcfHeader \
>      I=/mnt/Data_SSD/GIAB/union_171212_refalt.sort.vcf \
>      O=/mnt/Data_SSD/GIAB/union_171212_refalt.reheader.sort.vcf
INFO    2021-05-22 10:55:36     FixVcfHeader

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    FixVcfHeader -I /mnt/Data_SSD/GIAB/union_171212_refalt.sort.vcf -O /mnt/Data_SSD/GIAB/union_171212_refalt.reheader.sort.vcf
**********


10:55:36.782 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/nguyen/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Sat May 22 10:55:36 ICT 2021] FixVcfHeader INPUT=/mnt/Data_SSD/GIAB/union_171212_refalt.sort.vcf OUTPUT=/mnt/Data_SSD/GIAB/union_171212_refalt.reheader.sort.vcf    CHECK_FIRST_N_RECORDS=-1 ENFORCE_SAME_SAMPLES=true VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Sat May 22 10:55:36 ICT 2021] Executing as nguyen@nguyenws on Linux 5.8.0-50-generic amd64; OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.20.04; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.25.4
INFO    2021-05-22 10:55:36     FixVcfHeader    Reading in records to re-build the header.
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: OLD_MULTIALLELIC
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: AC
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: MQRankSum
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: MQ
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: AF
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: MLEAC
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: BaseQRankSum
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: ExcessHet
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: MLEAF
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: DP
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: ReadPosRankSum
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: AN
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: FS
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: QD
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: SOR
INFO    2021-05-22 10:55:36     FixVcfHeader    Will add an INFO line with id: ClippingRankSum
[Sat May 22 10:55:36 ICT 2021] picard.vcf.FixVcfHeader done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=1061158912
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index -34 out of bounds for length 2
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at htsjdk.variant.vcf.AbstractVCFCodec.oneAllele(AbstractVCFCodec.java:582)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseGenotypeAlleles(AbstractVCFCodec.java:602)
        at htsjdk.variant.vcf.AbstractVCFCodec.createGenotypeMap(AbstractVCFCodec.java:834)
        at htsjdk.variant.vcf.AbstractVCFCodec$LazyVCFGenotypesParser.parse(AbstractVCFCodec.java:121)
        at htsjdk.variant.variantcontext.LazyGenotypesContext.decode(LazyGenotypesContext.java:158)
        at htsjdk.variant.variantcontext.LazyGenotypesContext.getGenotypes(LazyGenotypesContext.java:148)
        at htsjdk.variant.variantcontext.GenotypesContext.iterator(GenotypesContext.java:465)
        at picard.vcf.FixVcfHeader.doWork(FixVcfHeader.java:169)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

#### Steps to reproduce
1. Dowload SV union set from GIAB
`wget ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_UnionSVs_12122017/union_171212_refalt.sort.vcf.gz`
2. Run FixVcfHeader
```
java -jar /home/nguyen/picard.jar FixVcfHeader \
     I=/mnt/Data_SSD/GIAB/union_171212_refalt.sort.vcf \
     O=/mnt/Data_SSD/GIAB/union_171212_refalt.reheader.sort.vcf
```

#### Expected behavior
I have run this tool successfully on VCF file generate by CuteSV, SVIM and other SV callers
----

**Comment by gbggrant** [comment]
Hi @NTNguyen13 it looks like Picard's FixVcfHeader tool is complaining about the contents of the GT field in the sample column of your VCF.  From the VCF 4.2 spec (https://samtools.github.io/hts-specs/VCFv4.2.pdf) - the contents of the GT field should be of the format 0|1 (or 0/1, or ….) but in your file, starting with record name HG4_Ill_GATKHC_1, the GT values are '-34'.  Perhaps this is due to an upstream processing issue?
