### ISSUE TITLE
The name of output file can not contain  ":"   in HaplotypeCaller analysis

### ISSUE THREAD

**Issue by shenweima** [broadinstitute/picard#1688]
My command
`gatk HaplotypeCaller -I test.rmdup.filter.sorted.bam -OVI False -O test.chr1A:1-141715383.g.vcf.gz -R /public1/home/sca2417/bwa_index/bwa_mem2_gtz_index_Chinese_spring2.1_KN9204_1RS.fasta --emit-ref-confidence GVCF -L chr1A:1-141715383`
The error information:
```
Using GATK jar /public1/home/sca2417/software/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /public1/home/sca2417/software/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar HaplotypeCaller -I test.rmdup.filter.sorted.bam -OVI False -O test.chr1A:1-141715383.g.vcf.gz -R /public1/home/sca2417/bwa_index/bwa_mem2_gtz_index_Chinese_spring2.1_KN9204_1RS.fasta --emit-ref-confidence GVCF -L chr1A:1-141715383
13:51:56.329 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/public1/home/sca2417/software/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jun 07, 2021 1:52:06 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
13:52:06.662 INFO  HaplotypeCaller - ------------------------------------------------------------
13:52:06.663 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.2.0.0
13:52:06.663 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
13:52:06.666 INFO  HaplotypeCaller - Executing as sca2417@ln121.para.bscc on Linux v3.10.0-1160.el7.x86_64 amd64
13:52:06.667 INFO  HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_275-b01
13:52:06.667 INFO  HaplotypeCaller - Start Date/Time: June 7, 2021 1:51:56 PM CST
13:52:06.667 INFO  HaplotypeCaller - ------------------------------------------------------------
13:52:06.667 INFO  HaplotypeCaller - ------------------------------------------------------------
13:52:06.669 INFO  HaplotypeCaller - HTSJDK Version: 2.24.0
13:52:06.670 INFO  HaplotypeCaller - Picard Version: 2.25.0
13:52:06.670 INFO  HaplotypeCaller - Built for Spark Version: 2.4.5
13:52:06.670 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
13:52:06.671 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
13:52:06.672 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
13:52:06.672 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
13:52:06.672 INFO  HaplotypeCaller - Deflater: IntelDeflater
13:52:06.672 INFO  HaplotypeCaller - Inflater: IntelInflater
13:52:06.672 INFO  HaplotypeCaller - GCS max retries/reopens: 20
13:52:06.672 INFO  HaplotypeCaller - Requester pays: disabled
13:52:06.673 INFO  HaplotypeCaller - Initializing engine
13:52:07.655 INFO  IntervalArgumentCollection - Processing 141715383 bp from intervals
13:52:07.676 INFO  HaplotypeCaller - Done initializing engine
13:52:07.684 INFO  HaplotypeCallerEngine - Tool is in reference confidence mode and the annotation, the following changes will be made to any specified annotations: 'StrandBiasBySample' will be enabled. 'ChromosomeCounts', 'FisherStrand', 'StrandOddsRatio' and 'QualByDepth' annotations have been disabled
13:52:07.714 INFO  HaplotypeCallerEngine - Standard Emitting and Calling confidence set to 0.0 for reference-model confidence output
13:52:07.714 INFO  HaplotypeCallerEngine - All sites annotated with PLs forced to true for reference-model confidence output
13:52:07.755 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/public1/home/sca2417/software/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_utils.so
13:52:07.758 INFO  NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/public1/home/sca2417/software/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
13:52:07.887 INFO  IntelPairHmm - Using CPU-supported AVX-512 instructions
13:52:07.887 INFO  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
13:52:07.888 INFO  IntelPairHmm - Available threads: 32
13:52:07.889 INFO  IntelPairHmm - Requested threads: 4
13:52:07.889 INFO  PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
13:52:07.891 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 0.0
13:52:07.892 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 0.0
13:52:07.894 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 0.00 sec
13:52:07.895 INFO  HaplotypeCaller - Shutting down engine
[June 7, 2021 1:52:07 PM CST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.19 minutes.
Runtime.totalMemory()=2193620992
java.nio.file.ProviderNotFoundException: Provider "test.chr1A" not found
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:341)
        at org.broadinstitute.hellbender.engine.GATKPath.toPath(GATKPath.java:77)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.makeVCFWriter(HaplotypeCallerEngine.java:376)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.onTraversalStart(HaplotypeCaller.java:263)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1056)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```
**If I change the output file name from  'test.chr1A:1-141715383.g.vcf.gz' to 'test.chr1A.1-141715383.g.vcf.gz', it works well again**....
`gatk HaplotypeCaller -I test.rmdup.filter.sorted.bam -OVI False -O test.chr1A.1-141715383.g.vcf.gz -R /public1/home/sca2417/bwa_index/bwa_mem2_gtz_index_Chinese_spring2.1_KN9204_1RS.fasta --emit-ref-confidence GVCF -L chr1A:1-141715383
Using GATK jar /public1/home/sca2417/software/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar`

```
Using GATK jar /public1/home/sca2417/software/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /public1/home/sca2417/software/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar HaplotypeCaller -I test.rmdup.filter.sorted.bam -OVI False -O test.chr1A.1-141715383.g.vcf.gz -R /public1/home/sca2417/bwa_index/bwa_mem2_gtz_index_Chinese_spring2.1_KN9204_1RS.fasta --emit-ref-confidence GVCF -L chr1A:1-141715383
13:54:34.495 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/public1/home/sca2417/software/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jun 07, 2021 1:54:44 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
13:54:44.876 INFO  HaplotypeCaller - ------------------------------------------------------------
13:54:44.878 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.2.0.0
13:54:44.878 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
13:54:44.879 INFO  HaplotypeCaller - Executing as sca2417@ln121.para.bscc on Linux v3.10.0-1160.el7.x86_64 amd64
13:54:44.880 INFO  HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_275-b01
13:54:44.880 INFO  HaplotypeCaller - Start Date/Time: June 7, 2021 1:54:34 PM CST
13:54:44.880 INFO  HaplotypeCaller - ------------------------------------------------------------
13:54:44.880 INFO  HaplotypeCaller - ------------------------------------------------------------
13:54:44.881 INFO  HaplotypeCaller - HTSJDK Version: 2.24.0
13:54:44.882 INFO  HaplotypeCaller - Picard Version: 2.25.0
13:54:44.882 INFO  HaplotypeCaller - Built for Spark Version: 2.4.5
13:54:44.882 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
13:54:44.882 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
13:54:44.882 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
13:54:44.882 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
13:54:44.882 INFO  HaplotypeCaller - Deflater: IntelDeflater
13:54:44.883 INFO  HaplotypeCaller - Inflater: IntelInflater
13:54:44.883 INFO  HaplotypeCaller - GCS max retries/reopens: 20
13:54:44.883 INFO  HaplotypeCaller - Requester pays: disabled
13:54:44.883 INFO  HaplotypeCaller - Initializing engine
13:54:45.895 INFO  IntervalArgumentCollection - Processing 141715383 bp from intervals
13:54:45.916 INFO  HaplotypeCaller - Done initializing engine
13:54:45.922 INFO  HaplotypeCallerEngine - Tool is in reference confidence mode and the annotation, the following changes will be made to any specified annotations: 'StrandBiasBySample' will be enabled. 'ChromosomeCounts', 'FisherStrand', 'StrandOddsRatio' and 'QualByDepth' annotations have been disabled
13:54:45.940 INFO  HaplotypeCallerEngine - Standard Emitting and Calling confidence set to 0.0 for reference-model confidence output
13:54:45.940 INFO  HaplotypeCallerEngine - All sites annotated with PLs forced to true for reference-model confidence output
13:54:45.976 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/public1/home/sca2417/software/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_utils.so
13:54:45.979 INFO  NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/public1/home/sca2417/software/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
13:54:46.076 INFO  IntelPairHmm - Using CPU-supported AVX-512 instructions
13:54:46.076 INFO  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
13:54:46.077 INFO  IntelPairHmm - Available threads: 32
13:54:46.077 INFO  IntelPairHmm - Requested threads: 4
13:54:46.077 INFO  PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
13:54:46.164 INFO  ProgressMeter - Starting traversal
13:54:46.164 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Regions Processed   Regions/Minute
13:54:56.177 INFO  ProgressMeter -        chr1A:3593209              0.2                 11980          71880.0
```

**Comment by cmnbroad** [comment]
@shenweima GATK converts filename inputs to a URI internally, and is interpreting the colon embedded in your filename as a URI scheme separator. If you want to use a filename with an embedded colon, you need to specify it as a full URI on the command line (including the full absolute path). For instance, if you want the file to be in  `/my/home`, you need to specify it on the command line as:

`file:///my/home/test.chr1A:1-141715383.g.vcf.gz`

**Comment by cmnbroad** [comment]
Closing as resolved; feel free to reopen if you have problems getting that to work.
