### ISSUE TITLE
Aligned record iterator (...) is behind the unmapped reads

### ISSUE THREAD

**Issue by marctormo** [broadinstitute/picard#1689]
Hi there,

I'm trying to add headers from unmapped BAM to an aligned one with MergeBamAlignment (I tried with versions 2.18.6 and 2.25.5) and I'm getting an error that I don't know how to solve:

Exception in thread "main" java.lang.IllegalStateException: Aligned record iterator (M00724:69:000000000-DC4KT:1:1101:10001:13361) is behind the unmapped reads (M00724:69:000000000-DC4KT:1:1101:10001:13361	mi:Z:TTCGAGTTGTTA	pr:Z:chrM-1-8845	pe:Z:0)

Both BAMs are sorted by queryname with SortSam. I checked both BAMs and there are two reads each (forward and reverse) in the same positions (9 and 10).

Do you know what is the problem here? 

Many thanks!

**Comment by DonFreed** [comment]
I'm also running into this issue with 2.25.6. I've attached a minimal test case here to demonstrate the issue, [testcase.tar.gz](https://github.com/broadinstitute/picard/files/6688883/testcase.tar.gz). Here is how I can replicate this issue with the testcase:
```sh
$ tar -zxf testcase.tar.gz
$ java -jar picard/2.25.6/picard.jar MergeBamAlignment \
  UNMAPPED="testcase/consensus_sorted.ubam" \
  ALIGNED="testcase/consensus_sorted.bam" \
  O="testcase/consensus_sorted_merged.bam" \
  R=GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
  CLIP_ADAPTERS=false ORIENTATIONS=FR ATTRIBUTES_TO_RETAIN=X0 \
  ATTRIBUTES_TO_RETAIN=ZS ATTRIBUTES_TO_RETAIN=ZI ATTRIBUTES_TO_RETAIN=ZM \
  ATTRIBUTES_TO_RETAIN=ZC ATTRIBUTES_TO_RETAIN=ZF ATTRIBUTES_TO_RETAIN=ZN \
  RV=ad RV=bd RV=cd RV=ae RV=be  RV=ce MAX_GAPS=-1 ALIGNER_PROPER_PAIR_FLAGS=false
...
12:14:13.058 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/dfreed/Downloads/picard/2.25.6/picard.jar!/com/intel/gkl/native/libgkl_compression.dylib
[Mon Jun 21 12:14:13 PDT 2021] MergeBamAlignment UNMAPPED_BAM=testcase/consensus_sorted.ubam ALIGNED_BAM=[testcase/consensus_sorted.bam] OUTPUT=testcase/consensus_sorted_merged.bam CLIP_ADAPTERS=false MAX_INSERTIONS_OR_DELETIONS=-1 ATTRIBUTES_TO_RETAIN=[X0, ZS, ZI, ZM, ZC, ZF, ZN] ATTRIBUTES_TO_REVERSE=[OQ, U2, ad, ae, bd, be, cd, ce] EXPECTED_ORIENTATIONS=[FR] ALIGNER_PROPER_PAIR_FLAGS=false REFERENCE_SEQUENCE=GCA_000001405.15_GRCh38_no_alt_analysis_set.fna    ADD_PG_TAG_TO_READS=true PAIRED_RUN=true IS_BISULFITE_SEQUENCE=false ALIGNED_READS_ONLY=false ATTRIBUTES_TO_REVERSE_COMPLEMENT=[E2, SQ] READ1_TRIM=0 READ2_TRIM=0 SORT_ORDER=coordinate PRIMARY_ALIGNMENT_STRATEGY=BestMapq CLIP_OVERLAPPING_READS=true HARD_CLIP_OVERLAPPING_READS=false INCLUDE_SECONDARY_ALIGNMENTS=true ADD_MATE_CIGAR=true UNMAP_CONTAMINANT_READS=false MIN_UNCLIPPED_BASES=32 MATCHING_DICTIONARY_TAGS=[M5, LN] UNMAPPED_READ_STRATEGY=DO_NOT_CHANGE VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Jun 21 12:14:13 PDT 2021] Executing as dfreed@Donalds-MacBook-Pro.local on Mac OS X 10.15.7 x86_64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.25.6
INFO	2021-06-21 12:14:18	SamAlignmentMerger	Processing SAM file(s): [testcase/consensus_sorted.bam]
WARNING	2021-06-21 12:14:18	SamAlignmentMerger	Exception merging bam alignment - attempting to sort aligned reads and try again: Aligned record iterator (umi-lb:3147279) is behind the unmapped reads (umi-lb:314728)
INFO	2021-06-21 12:14:18	SamAlignmentMerger	Finished reading 4 total records from alignment SAM/BAM.
[Mon Jun 21 12:14:18 PDT 2021] picard.sam.MergeBamAlignment done. Elapsed time: 0.09 minutes.
Runtime.totalMemory()=257425408
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalStateException: Aligned record iterator (umi-lb:3147279) is behind the unmapped reads (umi-lb:314728)
	at picard.sam.AbstractAlignmentMerger.mergeAlignment(AbstractAlignmentMerger.java:557)
	at picard.sam.SamAlignmentMerger.mergeAlignment(SamAlignmentMerger.java:186)
	at picard.sam.MergeBamAlignment.doWork(MergeBamAlignment.java:368)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

Both input files are queryname sorted (by Picard's SortSam).

**Comment by DonFreed** [comment]
After a second look, I was able to determine that my issue was the result of a user error. My uBAM file had undergone some additional processing which dropped some reads. The missing reads seemed to cause the "Aligned record iterator (...) is behind the unmapped reads" error.

**Comment by teryyoung** [comment]
@DonFreed I'm processing reads with umi, too. I called consensus reads, aligned them with bwa, then use `picard MergeBamAlignment` , and got this problem. could I know how did you solve this?
