### ISSUE TITLE
LeftAlignIndels Error

### ISSUE THREAD

**Issue by VikArz02** [broadinstitute/picard#1754]
Hello!

I input sorted and indexing bam file  to LeftAlignIndels:
`~/Soft/gatk-4.1.9.0/gatk LeftAlignIndels -I bam_fin/Exome_dups.bam -R /mnt/lapd/Index_hum/dna2/GRCh_2021.fa -O bam_fin/Exome.bam`

And have this error:

'java.lang.IllegalArgumentException: Alignments added out of order in SAMFileWriterImpl.addAlignment for file:///mnt/lapd/Vika_data/RNF_raw/exome/bam_fin/Exome_S33.bam. Sort order is coordinate. Offending records are at [1:152985370] and [1:152985347]
	at htsjdk.samtools.SAMFileWriterImpl.assertPresorted(SAMFileWriterImpl.java:197)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:184)
	at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:36)
	at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:16)
	at htsjdk.samtools.util.AbstractAsyncWriter$WriterRunnable.run(AbstractAsyncWriter.java:123)
	at java.base/java.lang.Thread.run(Thread.java:829)'

I want to note that the unsorted file is the output bam.

I appreciate your help!

With best regards,
Viktoriia

**Comment by gbggrant** [comment]
Hi @VikArz02 this appears to be an issue with the gatk tool 'LeftAlignIndels' - could you please redirect your question to their support forum: https://gatk.broadinstitute.org/hc/en-us/community/topics ?

Thanks.

George
