### ISSUE TITLE
xxx did not start with a parsable number

### ISSUE THREAD

**Issue by jingydz** [broadinstitute/picard#1761]
##command
java -jar ~/xxx/software/picard.jar MarkDuplicates I=xxx_rep2.rmchrM.mm10.bam O=xxx_rep2.rmchrM.rmdup.mm10.bam M=xxx_rep2.rmchrM.rmdup.mm10.dups.txt REMOVE_DUPLICATES=true

## Bug Report
WARNING 2021-12-14 13:22:35     AbstractOpticalDuplicateFinderCommandLineProgram        A field field parsed out of a read name was expected to contain an integer and did not. Read name: E100015604L1C038R0322738395. Cause: String 'E100015604L1C038R0322738395' did not start with a parsable number.

Runtime.totalMemory()=13564379136
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Alignments added out of order in SAMFileWriterImpl.addAlignment for file:///xxx/04_bowtie2/xxx_rep2.rmchrM.rmdup.mm10.bam. Sort order is coordinate. Offending records are at [*:0] and [chrX:3051879]
        at htsjdk.samtools.SAMFileWriterImpl.assertPresorted(SAMFileWriterImpl.java:197)
        at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:184)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:425)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

##version
Picard version: 2.25.5

**Comment by yfarjoun** [comment]
It seems that your readname do not conform to the format that Picard is
expecting. set the regular-expression to null to avoid _optical_ duplicate
marking (doesn NOT effect the actual duplicate marking, only the
library size estimation .


--READ_NAME_REGEX null / READ_NAME_REGEX=null

**Comment by jingydz** [comment]
Thanks! But it doesn't seem to work? It always has a problem with ChrX. ChrX is also filtered out when PCR repeats are filtered.
`java -jar ~/xxx/picard.jar MarkDuplicates I=xxx_rep2.rmchrM.mm10.bam READ_NAME_REGEX=null O=xxx_rep2.rmchrM.rmdup.mm10.bam M=4dups.txt REMOVE_DUPLICATES=true`

## logfile 
INFO    2021-12-15 02:58:21     MarkDuplicates  Marking 151936 records as duplicates.
WARNING 2021-12-15 02:58:21     MarkDuplicates  Skipped optical duplicate cluster discovery; library size estimation may be inaccurate!
INFO    2021-12-15 02:58:21     MarkDuplicates  Reads are assumed to be ordered by: coordinate
[Wed Dec 15 02:59:36 UTC 2021] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 1.63 minutes.
Runtime.totalMemory()=13543407616
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Alignments added out of order in SAMFileWriterImpl.addAlignment for file:///xxx/xxx_rep2.rmchrM.rmdup.mm10.bam. Sort order is coordinate. Offending records are at [*:0] and [chrX:3051879]
        at htsjdk.samtools.SAMFileWriterImpl.assertPresorted(SAMFileWriterImpl.java:197)
        at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:184)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:425)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

**Comment by yfarjoun** [comment]
Oh sorry I didn’t see that…. Did you check that your input bank is properly
sorted?

**Comment by kockan** [comment]
Closing issue due to time passed since open date. Please feel free to reopen if still relevant.
