### ISSUE TITLE
IlluminaBasecallsToSam does not detect exception until ThreadPoolExecutor has drained

### ISSUE THREAD

**Issue by alecw** [broadinstitute/picard#1770]
### Affected tool(s)
IlluminaBasecallsToSam

### Affected version(s)
- [ ] Latest public release version [2.26.10]

### Description 

In this example, GC overhead limit is hit 10 minutes into execution.  However, because there are 72 TileProcessor jobs, the program waits until all have ended before failing, after 2 hours of execution.

```
java -Djava.io.tmpdir=/broad/hptmp/alecw/HFNTVAFX3 -XX:+UseParallelOldGC -XX:ParallelGCThreads=1 -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx19384m -jar /humgen/cnp04/sandbox/alecw/tmp/test_deploy/3rdParty/picard/picard.jar IlluminaBasecallsToSam TMP_DIR=/broad/hptmp/alecw/HFNTVAFX3 VALIDATION_STRINGENCY=SILENT BASECALLS_DIR=/broad/mccarroll/dropulation_census/raw_data/2022-01-04/225552339/Data/Intensities/BaseCalls LANE=1 RUN_BARCODE=HFNTVAFX3 NUM_PROCESSORS=1 READ_STRUCTURE=83T83T INCLUDE_NON_PF_READS=false APPLY_EAMSS_FILTER=false MAX_RECORDS_IN_RAM=600000 IGNORE_UNEXPECTED_BARCODES=false SEQUENCING_CENTER=BI OUTPUT=/humgen/cnp04/sandbox/alecw/tmp/data/libraries/2022-01-04_d0ML-AstrovillagePerturb/HFNTVAFX3.1.0.d0ML-AstrovillagePerturb.unmapped.bam SAMPLE_ALIAS=d0ML-AstrovillagePerturb LIBRARY_NAME=d0ML-AstrovillagePerturb ADAPTERS_TO_CHECK=null RUN_START_DATE=01/04/2022 

INFO	2022-01-13 17:09:16	IlluminaBasecallsToSam	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    IlluminaBasecallsToSam -TMP_DIR /broad/hptmp/alecw/HFNTVAFX3 -VALIDATION_STRINGENCY SILENT -BASECALLS_DIR /broad/mccarroll/dropulation_census/raw_data/2022-01-04/225552339/Data/Intensities/BaseCalls -LANE 1 -RUN_BARCODE HFNTVAFX3 -NUM_PROCESSORS 1 -READ_STRUCTURE 83T83T -INCLUDE_NON_PF_READS false -APPLY_EAMSS_FILTER false -MAX_RECORDS_IN_RAM 600000 -IGNORE_UNEXPECTED_BARCODES false -SEQUENCING_CENTER BI -OUTPUT /humgen/cnp04/sandbox/alecw/tmp/data/libraries/2022-01-04_d0ML-AstrovillagePerturb/HFNTVAFX3.1.0.d0ML-AstrovillagePerturb.unmapped.bam -SAMPLE_ALIAS d0ML-AstrovillagePerturb -LIBRARY_NAME d0ML-AstrovillagePerturb -ADAPTERS_TO_CHECK null -RUN_START_DATE 01/04/2022
**********


17:09:17.192 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/humgen/cnp04/sandbox/alecw/tmp/test_deploy/3rdParty/picard/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Jan 13 17:09:17 EST 2022] IlluminaBasecallsToSam OUTPUT=/humgen/cnp04/sandbox/alecw/tmp/data/libraries/2022-01-04_d0ML-AstrovillagePerturb/HFNTVAFX3.1.0.d0ML-AstrovillagePerturb.unmapped.bam RUN_BARCODE=HFNTVAFX3 SAMPLE_ALIAS=d0ML-AstrovillagePerturb LIBRARY_NAME=d0ML-AstrovillagePerturb SEQUENCING_CENTER=BI RUN_START_DATE=Tue Jan 04 00:00:00 EST 2022 ADAPTERS_TO_CHECK=[] NUM_PROCESSORS=1 APPLY_EAMSS_FILTER=false INCLUDE_NON_PF_READS=false IGNORE_UNEXPECTED_BARCODES=false LANE=[1] READ_STRUCTURE=83T83T BASECALLS_DIR=/broad/mccarroll/dropulation_census/raw_data/2022-01-04/225552339/Data/Intensities/BaseCalls TMP_DIR=[/broad/hptmp/alecw/HFNTVAFX3] VALIDATION_STRINGENCY=SILENT MAX_RECORDS_IN_RAM=600000    PLATFORM=ILLUMINA INCLUDE_BC_IN_RG_TAG=false MAX_READS_IN_RAM_PER_TILE=-1 MOLECULAR_INDEX_TAG=RX MOLECULAR_INDEX_BASE_QUALITY_TAG=QX BARCODE_POPULATION_STRATEGY=ORPHANS_ONLY INCLUDE_BARCODE_QUALITY=false SORT=true MATCH_BARCODES_INLINE=false DISTANCE_MODE=HAMMING MAX_MISMATCHES=1 MIN_MISMATCH_DELTA=1 MAX_NO_CALLS=2 MINIMUM_BASE_QUALITY=0 MINIMUM_QUALITY=2 COMPRESS_OUTPUTS=false VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Jan 13 17:09:17 EST 2022] Executing as alecw@uger-c024.broadinstitute.org on Linux 3.10.0-1160.49.1.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_181-b13; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.26.10
INFO	2022-01-13 17:09:17	IlluminaBasecallsToSam	DONE_READING STRUCTURE IS 83T83T
INFO	2022-01-13 17:09:17	SortedBasecallsConverter	Tile Read Executor - Queueing: 72 TileProcessor jobs
INFO	2022-01-13 17:09:26	SortedBasecallsConverter	Read     1,000,000 records.  Elapsed time: 00:00:09s.  Time for last 1,000,000:    6s.  Last read position: */*
INFO	2022-01-13 17:09:39	SortedBasecallsConverter	Read     2,000,000 records.  Elapsed time: 00:00:21s.  Time for last 1,000,000:   12s.  Last read position: */*
INFO	2022-01-13 17:09:43	SortedBasecallsConverter	Read     3,000,000 records.  Elapsed time: 00:00:25s.  Time for last 1,000,000:    4s.  Last read position: */*
INFO	2022-01-13 17:09:58	SortedBasecallsConverter	Read     4,000,000 records.  Elapsed time: 00:00:41s.  Time for last 1,000,000:   15s.  Last read position: */*
INFO	2022-01-13 17:10:04	SortedBasecallsConverter	Read     5,000,000 records.  Elapsed time: 00:00:47s.  Time for last 1,000,000:    6s.  Last read position: */*
INFO	2022-01-13 17:10:07	SortedBasecallsConverter	Read     6,000,000 records.  Elapsed time: 00:00:50s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2022-01-13 17:10:14	SortedBasecallsConverter	Read     7,000,000 records.  Elapsed time: 00:00:57s.  Time for last 1,000,000:    6s.  Last read position: */*
INFO	2022-01-13 17:10:48	SortedBasecallsConverter	Read     8,000,000 records.  Elapsed time: 00:01:31s.  Time for last 1,000,000:   34s.  Last read position: */*
INFO	2022-01-13 17:10:51	SortedBasecallsConverter	Read     9,000,000 records.  Elapsed time: 00:01:34s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2022-01-13 17:10:59	SortedBasecallsConverter	Read    10,000,000 records.  Elapsed time: 00:01:41s.  Time for last 1,000,000:    7s.  Last read position: */*
INFO	2022-01-13 17:11:02	SortedBasecallsConverter	Read    11,000,000 records.  Elapsed time: 00:01:45s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2022-01-13 17:11:10	SortedBasecallsConverter	Read    12,000,000 records.  Elapsed time: 00:01:52s.  Time for last 1,000,000:    7s.  Last read position: */*
INFO	2022-01-13 17:11:49	SortedBasecallsConverter	Read    13,000,000 records.  Elapsed time: 00:02:31s.  Time for last 1,000,000:   39s.  Last read position: */*
INFO	2022-01-13 17:11:52	SortedBasecallsConverter	Read    14,000,000 records.  Elapsed time: 00:02:34s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2022-01-13 17:12:00	SortedBasecallsConverter	Read    15,000,000 records.  Elapsed time: 00:02:43s.  Time for last 1,000,000:    8s.  Last read position: */*
INFO	2022-01-13 17:12:08	SortedBasecallsConverter	Read    16,000,000 records.  Elapsed time: 00:02:50s.  Time for last 1,000,000:    7s.  Last read position: */*
INFO	2022-01-13 17:12:11	SortedBasecallsConverter	Read    17,000,000 records.  Elapsed time: 00:02:53s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2022-01-13 17:12:56	SortedBasecallsConverter	Read    18,000,000 records.  Elapsed time: 00:03:39s.  Time for last 1,000,000:   45s.  Last read position: */*
INFO	2022-01-13 17:13:00	SortedBasecallsConverter	Read    19,000,000 records.  Elapsed time: 00:03:42s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2022-01-13 17:13:38	SortedBasecallsConverter	Read    20,000,000 records.  Elapsed time: 00:04:20s.  Time for last 1,000,000:   38s.  Last read position: */*
INFO	2022-01-13 17:14:51	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 34 : Running jobs - 1 : Queued jobs  - 37
INFO	2022-01-13 17:14:51	SortedBasecallsConverter	Read    21,000,000 records.  Elapsed time: 00:05:33s.  Time for last 1,000,000:   72s.  Last read position: */*
ERROR	2022-01-13 17:28:30	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at picard.illumina.parser.ClusterData.(ClusterData.java:53)
	at picard.illumina.parser.IlluminaDataProvider.next(IlluminaDataProvider.java:114)
	at picard.illumina.parser.IlluminaDataProvider.next(IlluminaDataProvider.java:41)
	at picard.illumina.SortedBasecallsConverter$TileProcessor.run(SortedBasecallsConverter.java:192)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO	2022-01-13 17:28:30	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 35 : Running jobs - 1 : Queued jobs  - 36

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-1"
ERROR	2022-01-13 17:31:23	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.(StringBuilder.java:89)
	at picard.fastq.IlluminaReadNameEncoder.generateReadName(IlluminaReadNameEncoder.java:21)
	at picard.illumina.ClusterDataToSamConverter.convertClusterToOutputRecord(ClusterDataToSamConverter.java:240)
	at picard.illumina.ClusterDataToSamConverter.convertClusterToOutputRecord(ClusterDataToSamConverter.java:52)
	at picard.illumina.SortedBasecallsConverter$TileProcessor.run(SortedBasecallsConverter.java:196)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-2"
INFO	2022-01-13 17:34:09	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 37 : Running jobs - 1 : Queued jobs  - 34
ERROR	2022-01-13 17:34:44	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at picard.illumina.ClusterDataToSamConverter.createSamRecord(ClusterDataToSamConverter.java:184)
	at picard.illumina.ClusterDataToSamConverter.convertClusterToOutputRecord(ClusterDataToSamConverter.java:283)
	at picard.illumina.ClusterDataToSamConverter.convertClusterToOutputRecord(ClusterDataToSamConverter.java:52)
	at picard.illumina.SortedBasecallsConverter$TileProcessor.run(SortedBasecallsConverter.java:196)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-3"
ERROR	2022-01-13 17:36:56	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at picard.illumina.ClusterDataToSamConverter.createSamRecord(ClusterDataToSamConverter.java:184)
	at picard.illumina.ClusterDataToSamConverter.convertClusterToOutputRecord(ClusterDataToSamConverter.java:283)
	at picard.illumina.ClusterDataToSamConverter.convertClusterToOutputRecord(ClusterDataToSamConverter.java:52)
	at picard.illumina.SortedBasecallsConverter$TileProcessor.run(SortedBasecallsConverter.java:196)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-4"
INFO	2022-01-13 17:38:04	SortedBasecallsConverter	Read    22,000,000 records.  Elapsed time: 00:28:47s.  Time for last 1,000,000: 1,393s.  Last read position: */*
INFO	2022-01-13 17:39:09	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 39 : Running jobs - 1 : Queued jobs  - 32
ERROR	2022-01-13 17:39:42	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-5"
ERROR	2022-01-13 17:42:27	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-6"
INFO	2022-01-13 17:44:40	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 41 : Running jobs - 1 : Queued jobs  - 30
ERROR	2022-01-13 17:45:12	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-7"
ERROR	2022-01-13 17:47:58	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-8"
INFO	2022-01-13 17:50:11	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 43 : Running jobs - 1 : Queued jobs  - 28
ERROR	2022-01-13 17:50:44	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-9"
ERROR	2022-01-13 17:53:29	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-10"
INFO	2022-01-13 17:54:38	SortedBasecallsConverter	Read    23,000,000 records.  Elapsed time: 00:45:21s.  Time for last 1,000,000:  993s.  Last read position: */*
INFO	2022-01-13 17:55:43	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 45 : Running jobs - 1 : Queued jobs  - 26
ERROR	2022-01-13 17:56:16	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-11"
ERROR	2022-01-13 17:59:01	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-12"
INFO	2022-01-13 18:01:15	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 47 : Running jobs - 1 : Queued jobs  - 24
ERROR	2022-01-13 18:01:48	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-13"
ERROR	2022-01-13 18:04:35	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-14"
INFO	2022-01-13 18:06:17	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 49 : Running jobs - 1 : Queued jobs  - 22
ERROR	2022-01-13 18:07:22	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-15"
ERROR	2022-01-13 18:10:10	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-16"
INFO	2022-01-13 18:10:47	SortedBasecallsConverter	Read    24,000,000 records.  Elapsed time: 01:01:29s.  Time for last 1,000,000:  968s.  Last read position: */*
INFO	2022-01-13 18:11:19	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 51 : Running jobs - 1 : Queued jobs  - 20
ERROR	2022-01-13 18:12:58	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-17"
ERROR	2022-01-13 18:15:46	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-18"
INFO	2022-01-13 18:16:21	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 53 : Running jobs - 1 : Queued jobs  - 18
ERROR	2022-01-13 18:18:33	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-19"
ERROR	2022-01-13 18:21:20	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-20"
INFO	2022-01-13 18:21:55	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 55 : Running jobs - 1 : Queued jobs  - 16
ERROR	2022-01-13 18:24:07	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-21"
INFO	2022-01-13 18:24:43	SortedBasecallsConverter	Read    25,000,000 records.  Elapsed time: 01:15:25s.  Time for last 1,000,000:  836s.  Last read position: */*
ERROR	2022-01-13 18:26:54	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-22"
INFO	2022-01-13 18:27:29	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 57 : Running jobs - 1 : Queued jobs  - 14
ERROR	2022-01-13 18:29:41	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-23"
ERROR	2022-01-13 18:32:28	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-24"
INFO	2022-01-13 18:33:03	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 59 : Running jobs - 1 : Queued jobs  - 12
ERROR	2022-01-13 18:35:16	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-25"
INFO	2022-01-13 18:37:31	SortedBasecallsConverter	Read    26,000,000 records.  Elapsed time: 01:28:13s.  Time for last 1,000,000:  767s.  Last read position: */*
ERROR	2022-01-13 18:38:03	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-26"
INFO	2022-01-13 18:38:38	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 61 : Running jobs - 1 : Queued jobs  - 10
ERROR	2022-01-13 18:40:51	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-27"
INFO	2022-01-13 18:43:39	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 62 : Running jobs - 1 : Queued jobs  - 9
ERROR	2022-01-13 18:43:39	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-28"
ERROR	2022-01-13 18:46:26	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-29"
INFO	2022-01-13 18:48:41	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 64 : Running jobs - 1 : Queued jobs  - 7
ERROR	2022-01-13 18:49:13	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-30"
INFO	2022-01-13 18:49:50	SortedBasecallsConverter	Read    27,000,000 records.  Elapsed time: 01:40:32s.  Time for last 1,000,000:  739s.  Last read position: */*
ERROR	2022-01-13 18:52:01	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-31"
INFO	2022-01-13 18:53:43	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 66 : Running jobs - 1 : Queued jobs  - 5
ERROR	2022-01-13 18:54:48	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-32"
ERROR	2022-01-13 18:57:36	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-33"
INFO	2022-01-13 18:58:45	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 68 : Running jobs - 1 : Queued jobs  - 3
ERROR	2022-01-13 19:00:23	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-34"
INFO	2022-01-13 19:00:59	SortedBasecallsConverter	Read    28,000,000 records.  Elapsed time: 01:51:42s.  Time for last 1,000,000:  669s.  Last read position: */*
ERROR	2022-01-13 19:03:10	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-35"
INFO	2022-01-13 19:03:45	ThreadPoolExecutorUtil	Tile Read Executor waiting for job completion. Finished jobs - 70 : Running jobs - 1 : Queued jobs  - 1
ERROR	2022-01-13 19:05:58	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-36"
ERROR	2022-01-13 19:08:45	ThreadPoolExecutorWithExceptions	A thread failed:
java.lang.OutOfMemoryError: GC overhead limit exceeded

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-2-thread-37"
[Thu Jan 13 19:08:45 EST 2022] picard.illumina.IlluminaBasecallsToSam done. Elapsed time: 119.47 minutes.
Runtime.totalMemory()=18067488768
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: Exceptions in tile processing. There were 0 tasks still running or queued and they have been cancelled. Errors: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at picard.illumina.BasecallsConverter.interruptAndShutdownExecutors(BasecallsConverter.java:318)
	at picard.illumina.SortedBasecallsConverter.awaitExecutor(SortedBasecallsConverter.java:263)
	at picard.illumina.SortedBasecallsConverter.awaitTileProcessingCompletion(SortedBasecallsConverter.java:244)
	at picard.illumina.SortedBasecallsConverter.processTilesAndWritePerSampleOutputs(SortedBasecallsConverter.java:126)
	at picard.illumina.IlluminaBasecallsToSam.doWork(IlluminaBasecallsToSam.java:278)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

#### Steps to reproduce
Run IlluminaBasecallsToSam with NUM_PROCESSORS=1, and not enough memory.  
#### Expected behavior
Program should terminate relatively soon after OOM error.  My guess is that picard.util.ThreadPoolExecutorUtil#awaitThreadPoolTermination should call `executor.hasError()` in its loop.  I could submit a PR, but I'm not confident I know what you all would consider the right way to do this.

#### Actual behavior
Program runs for almost 2 hours after initial exception.

**Comment by alecw** [comment]
Thanks!
