### ISSUE TITLE
Duplicate reads remain in sci-ATAC-seq bam after MarkDuplicates --REMOVE_DUPLICATES true

### ISSUE THREAD

**Issue by kalavattam** [broadinstitute/picard#1780]
### Affected tool(s)
`MarkDuplicates`, `FixMateInformation`, `MarkDuplicatesWithMateCigar`

### Version(s) used
- [x] Public release version [Version:2.26.4]

### Description 
When I use `picard MarkDuplicates` to deduplicate a merged bam file from a [sci-ATAC-seq](https://www.science.org/doi/10.1126/science.aab1601) experiment, duplicates remain in the file. The merged bam file is made from paired-end fastq files aligned with `bowtie2` and merged with `sambamba merge`. The bam file is sorted by coordinate with `picard SamSort`, and then `picard MarkDuplicates` was called (see *Steps to reproduce* below). A small number of duplicates appear to be removed (see the attached file "log.MarkDuplicates.txt"); many more remain:
```
samtools view "${bam_chrX_rmdup}.bam" | head -20
# GAATTCGTGCGCGTTCATCAGAGAGGTCGTACTGAC:0  99  chrX    3041    42  50M =   3205    214 AGTTAATTCATATGGATAACAGCAATAATACTGAGCCCCTGAGACTACTT  AAAAAEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:0  YT:Z:CP
# GAATTCGTGCGCGTTCATCAGAGAGGTCGTACTGAC:0  99  chrX    3041    42  50M =   3205    214 AGTTAATTCATATGGATAACAGCAATAATACTGAGCCCCTGAGACTACTT  AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:-3 YT:Z:CP
# GAATTCGTGCGCGTTCATCAGAGAGGTCGTACTGAC:0  147 chrX    3205    42  50M =   3041    -214    CTGGGTGGGACACAGTCTTCTCTTGTTTTCTTTTGTAACAAGATGTAGAA  EEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE6EEEEEEAAAAA  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:0  YT:Z:CP
# GAATTCGTGCGCGTTCATCAGAGAGGTCGTACTGAC:0  147 chrX    3205    42  50M =   3041    -214    CTGGGTGGGACTCAGTCTTCTCTTGTTTTCTTTTGTAACAAGATGTAGAA  EEEEE<EEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA  MD:Z:11A38  PG:Z:MarkDuplicates XG:i:0  NM:i:1  XM:i:1  XN:i:0  XO:i:0  AS:i:-3 YS:i:0  YT:Z:CP
# GAATTCGTGCGCTATGGTTTAATTAGCCGTACTGAC:0  99  chrX    22016   39  50M =   22179   213 ACATTCTAGCGTGACCCCAGTCAATTCTGAGACTGAAGACAAACTTAATA  AAAAAEEEEEEEE/EEEEEEEEEEEEEEAEEAEEEEEEEEEEEEEEEAEE  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-25    YS:i:0  YT:Z:CP
# GAATTCGTGCGCTATGGTTTAATTAGCCGTACTGAC:0  99  chrX    22016   39  50M =   22179   213 ACATTCTAGCGTGACCCCAGTCAATTCTGAGACTGAAGACAAACTTAATA  AAAAAEEEAEAEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEAEA  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-30    YS:i:0  YT:Z:CP
# GAATTCGTGCGCTATGGTTTAATTAGCCGTACTGAC:0  147 chrX    22179   39  50M =   22016   -213    TAAAATGGCTTGTCATAATGACTGAAATACTTGAGCCTACTTCCTTGTCC  EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-15    YS:i:0  YT:Z:CP
# GAATTCGTGCGCTATGGTTTAATTAGCCGTACTGAC:0  147 chrX    22179   39  50M =   22016   -213    TAAAATGGCTTGTCATAATGACTGAAATACTTGAGCCTACTTCCTTGTCC  EEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-15    YS:i:0  YT:Z:CP
# GAATTCGTACGGCGTTAACTCTAACTCGTAATCTTA:0  99  chrX    23671   42  50M =   23786   165 CATTGATAATCCCAGCCTAAACGACCAGCAGTCACTCTGGAAGCCACAGA  A/A6A6A66AEAEAA//A6/A6//AE6/A6/AAA6666AA/<//A/66A/  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:0  YT:Z:CP
# GAATTCGTACGGCGTTAACTCTAACTCGTAATCTTA:0  147 chrX    23786   42  50M =   23671   -165    TCAATCCCTCATTATCATCCTCAGACCTTTTGTTATAGTCTCTCCCACTA  6EEEEEEEAEE/EEEEEEEEEE/EEEEEEEEEE6E6EEEE6E/EEAAAAA  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:0  YT:Z:CP
# GAATTCGTGCGCTATGGTTTAATTAGCCGTACTGAC:0  163 chrX    24055   40  50M =   24088   83  GAACCACAGAGAAAATAGAAACCAAGGAACAAAACACCCACCTCACAACG  AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE<AEEEEEEEEEEE  MD:Z:48G1   PG:Z:MarkDuplicates XG:i:0  NM:i:1  XM:i:1  XN:i:0  XO:i:0  AS:i:-5 YS:i:-10    YT:Z:CP
# GAATTCGTTCTATCGCTGAGGCGAGAGCTAATCTTA:0  99  chrX    24083   42  50M =   24178   145 ACAAAACACCCACCTCACAACGAGAAGACCAGGTATCAGGATGTAGGAAT  AAAAAAEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEE  MD:Z:20G15T13   PG:Z:MarkDuplicates XG:i:0  NM:i:2  XM:i:2  XN:i:0  XO:i:0  AS:i:-10    YS:i:0  YT:Z:CP
# GAATTCGTTCTATCGCTGAGGCGAGAGCTAATCTTA:0  99  chrX    24083   42  50M =   24178   145 ACAAAACACCCACCTCACAACGAGAAGACCAGGTATCAGGATGTAGGAAT  AAAAAEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEE/EEE  MD:Z:20G15T13   PG:Z:MarkDuplicates XG:i:0  NM:i:2  XM:i:2  XN:i:0  XO:i:0  AS:i:-10    YS:i:0  YT:Z:CP
# GAATTCGTTCTATCGCTGAGGCGAGAGCTAATCTTA:0  99  chrX    24083   42  50M =   24178   145 ACAAAACACCCACCTCACAACGAGAAGACCAGGTATCAGGATGTAGGAAT  AAAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  MD:Z:20G15T13   PG:Z:MarkDuplicates XG:i:0  NM:i:2  XM:i:2  XN:i:0  XO:i:0  AS:i:-10    YS:i:0  YT:Z:CP
# GAATTCGTGCGCTATGGTTTAATTAGCCGTACTGAC:0  83  chrX    24088   40  50M =   24055   -83 ACACCCACCTCACAACGAGAAGACCAGGTATCAGGATGTAGGAATACAAT  EEEEEEEEEEEEEEEEEEEEEEEA/EEEEEEEEEEEEEEEEEEEEAAAAA  MD:Z:15G15T18   PG:Z:MarkDuplicates XG:i:0  NM:i:2  XM:i:2  XN:i:0  XO:i:0  AS:i:-10    YS:i:-5 YT:Z:CP
# GAATTCGTTCTATCGCTGAGGCGAGAGCTAATCTTA:0  147 chrX    24178   42  50M =   24083   -145    AATAATAGCCTGAACAATACATCTCCATTAAAGCCCAGCAACCCTACCAC  EE/EEEEEEEE/EEEEEEEEE6EEEEEEEAEEEEEEEEEEEEEEEAAAAA  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:-10    YT:Z:CP
# GAATTCGTTCTATCGCTGAGGCGAGAGCTAATCTTA:0  147 chrX    24178   42  50M =   24083   -145    AATAATAGCCTGAACAATACATCTCCATTAAAGCCCAGCAACCCTACCAC  EEAEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:-10    YT:Z:CP
# GAATTCGTTCTATCGCTGAGGCGAGAGCTAATCTTA:0  147 chrX    24178   42  50M =   24083   -145    AATAATAGCCTGAACAATACATCTCCATTAAAGCCCAGCAACCCTACCAC  EEAEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:-10    YT:Z:CP
# GAATTCGTTCTATCGCTGAGGCGAGAGCTAATCTTA:0  99  chrX    24589   42  50M =   24948   409 AAGTTTGGGTTGAAAGTTTTGTGGGTGAGTTTGAAGTGGAAACTTCTAGT  AAAAAEEEEEEAEEEEEEEEAEEEEEEEEEEE6E//EEEE/<EEEEEEEE  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:0  YT:Z:CP
# GAATTCGTTCTATCGCTGAGGCGAGAGCTAATCTTA:0  147 chrX    24948   42  50M =   24589   -409    AAAAACTCACCTAAGAACTGCTTGTGAGGTTCCTGCAGCAACTTGTAGTT  EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-30    YS:i:0  YT:Z:CP
```
Relatedly, I attempted to use `markDuplicatesWithMateCigar`; in preparation for that, I tried to use `FixMateInformation`. In doing so, I encountered an error described in *Actual behavior* below (see the attached file "log.FixMateInformation.txt" too).

#### Steps to reproduce
To test the issue, I've attached a small bam file (in order to upload it, I've zipped it).

How I called `MarkDuplicates`:
```
bam_chrX="picard-test.chrX.bam"
bam_chrX_rmdup="picard-test.chrX.rmdup"

picard MarkDuplicates \
--INPUT "${bam_chrX}" \
--OUTPUT "${bam_chrX_rmdup}.bam" \
--METRICS_FILE "${bam_chrX_rmdup}.txt" \
--REMOVE_DUPLICATES true
```
How I called `FixMateInformation`:
```
bam_chrX="picard-test.chrX.bam"
bam_chrX_fixmate="picard-test.chrX.fixmate.bam"

picard FixMateInformation \
--INPUT "${bam_chrX}" \
--OUTPUT "${bam_chrX_fixmate}" \
--ADD_MATE_CIGAR true
```
#### Expected behavior
Regarding `picard MarkDuplicates`, I expect all duplicates removed; for example, instead of...
```
# GAATTCGTGCGCGTTCATCAGAGAGGTCGTACTGAC:0  99  chrX    3041    42  50M =   3205    214 AGTTAATTCATATGGATAACAGCAATAATACTGAGCCCCTGAGACTACTT  AAAAAEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:0  YT:Z:CP
# GAATTCGTGCGCGTTCATCAGAGAGGTCGTACTGAC:0  99  chrX    3041    42  50M =   3205    214 AGTTAATTCATATGGATAACAGCAATAATACTGAGCCCCTGAGACTACTT  AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:-3 YT:Z:CP
# GAATTCGTGCGCGTTCATCAGAGAGGTCGTACTGAC:0  147 chrX    3205    42  50M =   3041    -214    CTGGGTGGGACACAGTCTTCTCTTGTTTTCTTTTGTAACAAGATGTAGAA  EEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE6EEEEEEAAAAA  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:0  YT:Z:CP
# GAATTCGTGCGCGTTCATCAGAGAGGTCGTACTGAC:0  147 chrX    3205    42  50M =   3041    -214    CTGGGTGGGACTCAGTCTTCTCTTGTTTTCTTTTGTAACAAGATGTAGAA  EEEEE<EEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA  MD:Z:11A38  PG:Z:MarkDuplicates XG:i:0  NM:i:1  XM:i:1  XN:i:0  XO:i:0  AS:i:-3 YS:i:0  YT:Z:CP
```
...I expect the following:
```
# GAATTCGTGCGCGTTCATCAGAGAGGTCGTACTGAC:0  99  chrX    3041    42  50M =   3205    214 AGTTAATTCATATGGATAACAGCAATAATACTGAGCCCCTGAGACTACTT  AAAAAEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:0  YT:Z:CP
# GAATTCGTGCGCGTTCATCAGAGAGGTCGTACTGAC:0  147 chrX    3205    42  50M =   3041    -214    CTGGGTGGGACACAGTCTTCTCTTGTTTTCTTTTGTAACAAGATGTAGAA  EEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE6EEEEEEAAAAA  MD:Z:50 PG:Z:MarkDuplicates XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  YS:i:0  YT:Z:CP
```

#### Actual behavior
In running `picard MarkDuplicates`, very few duplicates were removed; most duplicates remained in the file (see above and "log.MarkDuplicates.txt").

In running `FixMateInformation`, I encountered the following error (see the attached file "log.FixMateInformation.txt" too):
```
# Exception in thread "main" htsjdk.samtools.SAMException: Found two records that are paired, not supplementary, and first of the pair: ATTACTCGAACGAATTCGAGATCTTGGTTATAGCCT:0
#     at htsjdk.samtools.SamPairUtil$SetMateInfoIterator.advance(SamPairUtil.java:454)
#     at htsjdk.samtools.SamPairUtil$SetMateInfoIterator.next(SamPairUtil.java:501)
#     at htsjdk.samtools.SamPairUtil$SetMateInfoIterator.next(SamPairUtil.java:388)
#     at picard.sam.FixMateInformation.doWork(FixMateInformation.java:224)
#     at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
#     at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
#     at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```
Thank you so much; I greatly appreciate you attention to this matter.
[log.MarkDuplicates.txt](https://github.com/broadinstitute/picard/files/8150914/log.MarkDuplicates.txt)
[log.FixMateInformation.txt](https://github.com/broadinstitute/picard/files/8150940/log.FixMateInformation.txt)
[picard-test.chrX.bam.zip](https://github.com/broadinstitute/picard/files/8150920/picard-test.chrX.bam.zip)

**Comment by kalavattam** [comment]
In the processing steps prior to deduplication with `picard MarkDuplicates`, fastq sequence identifiers are converted from  sequencing platform-specific information to nucleus barcode information. I think this is related to the errors I reported. Is this correct? If so, is it still possible to use Picard Tools for deduplication of bam files resulting from this pipeline?

**Comment by kalavattam** [comment]
Issue is due to fastq sequence identifiers having been changed. Closing.
