### ISSUE TITLE
Snappy Error on M1 mac when running SortSam

### ISSUE THREAD

**Issue by RomeroMatt** [broadinstitute/picard#1797]
### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
_Tool name(s), special parameters?_

### Affected version(s)
- [x] Latest public release version [version?]
- [ ] Latest development/master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem and provide a minimal test case._

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) involved
_Tool name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) involved
_Tool name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by RomeroMatt** [comment]
Hi All, 
I'm new to picard and was using it to sort a sam file using the following command:
picard SortSam -I /Users/matthewa/Data/scripts/cut_tag/alignment/sam/H3K27me3_rep1_bowtie2.sam \
-O /Users/matthewa/Data/scripts/cut_tag/alignment/sam/H3K27me3_rep1_bowtie2.sorted.sam -SORT_ORDER coordinate -USE_JDK_DEFLATER true -USE_JDK_INFLATER true

When doing so I get the following output and warning from SnappyLoader:

[Sat Apr 09 07:45:53 PDT 2022] SortSam --INPUT /Users/matthewa/Data/scripts/cut_tag/alignment/sam/H3K27ac_H1_bowtie2.sam --OUTPUT /Users/matthewa/Data/scripts/cut_tag/alignment/sam/H3K27ac_H1_bowtie2.sorted.sam --SORT_ORDER coordinate --USE_JDK_DEFLATER true --USE_JDK_INFLATER true --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false
[Sat Apr 09 07:45:53 PDT 2022] Executing as matthewa@Matthews-MacBook-Pro.local on Mac OS X 12.2.1 aarch64; OpenJDK 64-Bit Server VM 18+0; Deflater: Jdk; Inflater: Jdk; Provider GCS is not available; Picard version: Version:2.27.1
INFO	2022-04-09 07:45:53	SortSam	Seen many non-increasing record positions. Printing Read-names as well.
WARNING	2022-04-09 07:45:54	SnappyLoader	Snappy native library failed to load.
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64
	at org.xerial.snappy.SnappyLoader.findNativeLibrary(SnappyLoader.java:342)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:176)
	at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:154)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:99)
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:91)
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:81)
	at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:58)
	at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:48)
	at htsjdk.samtools.util.TempStreamFactory.getSnappyLoader(TempStreamFactory.java:42)
	at htsjdk.samtools.util.TempStreamFactory.wrapTempOutputStream(TempStreamFactory.java:74)
	at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:251)
	at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:182)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:187)
	at picard.sam.SortSam.doWork(SortSam.java:163)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

It still produces a sorted sam file (I think it's all correct), but I can't seem to find a fix. Perhaps I just need to install something or set an option? I'm also not exactly certain what SnappyLoader is used for, but it seems like it might be related to speeding up the processing of the commands? 
Thanks for all the help!
-Matt

**Comment by RobertHu0817** [comment]
update snappy jars for M1 mac
https://github.com/xerial/snappy-java/releases/tag/1.1.8.2

**Comment by lbergelson** [comment]
@RomeroMatt @RobertHu0817 Try using the newest picard (2.27.4), this is a known issue that should have been fixed in 2.27.3.

**Comment by RomeroMatt** [comment]
Thanks @RobertHu0817 and @lbergelson!
