### ISSUE TITLE
MarkDuplicate memory issue

### ISSUE THREAD

**Issue by guptapa** [broadinstitute/picard#1800]
I keep getting following error with MarkDuplicate:

picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 42.35 minutes.
Runtime.totalMemory()=10541858816
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: Exception writing ReadEnds to file.
        at picard.sam.markduplicates.util.ReadEndsForMarkDuplicatesCodec.encode(ReadEndsForMarkDuplicatesCodec.java:74)
        at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap$Codec.encode(DiskBasedReadEndsForMarkDuplicatesMap.java:104)
        at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap$Codec.encode(DiskBasedReadEndsForMarkDuplicatesMap.java:76)
        at htsjdk.samtools.CoordinateSortedPairInfoMap.ensureSequenceLoaded(CoordinateSortedPairInfoMap.java:105)
        at htsjdk.samtools.CoordinateSortedPairInfoMap.remove(CoordinateSortedPairInfoMap.java:86)
        at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.remove(DiskBasedReadEndsForMarkDuplicatesMap.java:61)
        at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:558)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:258)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
Caused by: java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
        at java.io.DataOutputStream.writeLong(DataOutputStream.java:224)
        at picard.sam.markduplicates.util.ReadEndsForMarkDuplicatesCodec.encode(ReadEndsForMarkDuplicatesCodec.java:59)
        ... 10 more

I'm using using java -Xmx10g with 20G of input bam file on single core.
Need help!

**Comment by kachulis** [comment]
It looks like you ran out of disk space, not memory.  For a 20G bam you likely need around 50-100G of disk available to run markDuplicates.
