### ISSUE TITLE
Cannot build Extended Illumina Manifest 

### ISSUE THREAD

**Issue by yilevine** [broadinstitute/picard#1819]
----

### Affected tool(s)
picard CreateExtendedIlluminaManifest
REFERENCE_SEQUENCE=reference_all/hg_37/genome.fa  \
INPUT=raw_data/bpm/InfiniumOmni2-5-8v1-5_A1.csv \
OUTPUT=raw_data/bpm/InfiniumOmni2-5-8v1-5_A1.extended.csv \
CLUSTER_FILE=raw_data/egt/infinium-omni2-5-exome-8v1-5-a1-cluster-file.egt \
REPORT_FILE=raw_data/bpm/InfiniumOmni2-5-8v1-5_A1_manifest.report.txt \
TB=37

### Affected version(s)
Version:2.27.4-SNAPSHOT

### Description 
I was trying to use the code above to create Extended Illumina Manifest file to convert GTC to VCF file. But I obtained errors. 

Runtime.totalMemory()=2075918336
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOfRange(Arrays.java:4030)
        at java.base/java.lang.StringCoding.decodeUTF8(StringCoding.java:710)
        at java.base/java.lang.StringCoding.decode(StringCoding.java:318)
        at java.base/java.lang.String.<init>(String.java:592)
        at picard.util.AbstractInputParser.parseLine(AbstractInputParser.java:112)
        at picard.util.AbstractInputParser.advance(AbstractInputParser.java:88)
        at picard.util.AbstractInputParser.advance(AbstractInputParser.java:44)
        at htsjdk.samtools.util.AbstractIterator.next(AbstractIterator.java:57)
        at picard.arrays.illumina.IlluminaManifest$1.next(IlluminaManifest.java:197)
        at picard.arrays.illumina.IlluminaManifest$1.next(IlluminaManifest.java:180)
        at picard.arrays.illumina.CreateExtendedIlluminaManifest.doWork(CreateExtendedIlluminaManifest.java:185)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

I understood that the java required more memory. But I was running on cluster. I cannot change the memory. How can I solve this problem? Thanks very much.

**Comment by kachulis** [comment]
You can increase the available java heap space using the `-Xmx` flag.
