### ISSUE TITLE
FilterSamReads not able to solve soft links for reference file

### ISSUE THREAD

**Issue by RaqManzano** [broadinstitute/picard#1832]
### Affected tool
FilterSamReads

### Affected version
Running with GATK4: v4.2.6.1

### Description 
I am using Nextflow to run FilterSamReads and this works in a way that creates soft links for each input file. However, I am using a CRAM as an input, which needs the reference file. When I do this, I get an error asking for the reference, which is already provided in the command line but it doesn't seem like is being read. My only guess was that it was because it was a soft link and indeed when I run it with the absolute path and not the soft link it works.

I am submitting the issue here because FilterSamReads comes from picard but let me know if I should move this to the GATK repo as I am using gatk.

This is the error:
```
Using GATK jar /usr/local/share/gatk4-4.2.6.1-0/gatk-package-4.2.6.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /usr/local/share/gatk4-4.2.6.1-0/gatk-package-4.2.6.1-local.jar FilterSamReads --INPUT SAMPLE_NORMAL.cram --OUTPUT SAMPLE_NORMAL_filtered.bam --TMP_DIR . -R chr3.fa --READ_LIST_FILE SAMPLE_NORMAL_IDs_all.txt --FILTER includeReadList --VALIDATION_STRINGENCY LENIENT --CREATE_INDEX true
13:59:47.550 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/gatk4-4.2.6.1-0/gatk-package-4.2.6.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Sep 30 13:59:47 GMT 2022] FilterSamReads --INPUT SAMPLE_NORMAL.cram --FILTER includeReadList --READ_LIST_FILE SAMPLE_NORMAL_IDs_all.txt --OUTPUT SAMPLE_NORMAL_filtered.bam --TMP_DIR . --VALIDATION_STRINGENCY LENIENT --CREATE_INDEX true --REFERENCE_SEQUENCE chr3.fa --WRITE_READS_FILES false --VERBOSITY INFO --QUIET false --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Fri Sep 30 13:59:47 GMT 2022] Executing as user@login-e-14 on Linux 3.10.0-1160.71.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 11.0.9.1-internal+0-adhoc..src; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.2.6.1
ERROR	2022-09-30 13:59:48	FilterSamReads	Failed to filter SAMPLE_NORMAL.cram
java.lang.IllegalArgumentException: A reference must be supplied (reference sequence SAMSequenceRecord(name=chr3,length=198295559,dict_index=0,assembly=null,alternate_names=[]) not found).
	at htsjdk.samtools.cram.build.CRAMReferenceRegion.getReferenceBases(CRAMReferenceRegion.java:77)
	at htsjdk.samtools.cram.structure.Slice.normalizeCRAMRecords(Slice.java:450)
	at htsjdk.samtools.cram.structure.Container.getSAMRecords(Container.java:322)
	at htsjdk.samtools.CRAMIterator.nextContainer(CRAMIterator.java:112)
	at htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:204)
	at htsjdk.samtools.SamReader$AssertingIterator.hasNext(SamReader.java:608)
	at htsjdk.samtools.util.PeekableIterator.advance(PeekableIterator.java:70)
	at htsjdk.samtools.util.PeekableIterator.<init>(PeekableIterator.java:38)
	at htsjdk.samtools.filter.FilteringSamIterator.<init>(FilteringSamIterator.java:80)
	at picard.sam.FilterSamReads.doWork(FilterSamReads.java:324)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:37)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
[Fri Sep 30 13:59:48 GMT 2022] picard.sam.FilterSamReads done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2147483648
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Tool returned:
1
```

#### Steps to reproduce
Command I used (all inputs are soft links created with `ln -s`):
```
gatk FilterSamReads \
   --INPUT SAMPLE_NORMAL.cram \
   --OUTPUT SAMPLE_NORMAL_filtered.bam \
   --TMP_DIR . \
   -R chr3.fa \
   --READ_LIST_FILE SAMPLE_NORMAL_IDs_all.txt --FILTER includeReadList --VALIDATION_STRINGENCY LENIENT --CREATE_INDEX true
```

#### Expected behavior
Should run as normal.

#### Actual behavior
Gives an error when the reference file is a soft link.

**Comment by cmnbroad** [comment]
@RaqManzano I would have expected that to work (assuming the soft link is to the correct reference, and contains a chr3 contig). Does the link cross file system boundaries (can you post the full paths of the actual file and of the link ?).

**Comment by RaqManzano** [comment]
Hi @cmnbroad, I have tested the softlink and it seems fine . I am not sure what you mean by the 'file system boundaries'. Here is the path and the softlink:
/rds/user899/resources/genome/hg38/chr3.fa
/rds/user899/analysis/pipeline/work/97/e6f1bc26765e6f9adae36ac73b8d9d/chr3.fa -> /rds/user899/resources/genome/hg38/chr3.fa

**Comment by kachulis** [comment]
Hi @RaqManzano did this issue ever get resolved?  I have tested with softlinks on the newest version of picard and it works fine.  You may need to also make sure that there is a softlink for the fasta index as well, ie /rds/user899/analysis/pipeline/work/97/e6f1bc26765e6f9adae36ac73b8d9d/chr3.fa.fai -> /rds/user899/resources/genome/hg38/chr3.fa.fai
