### ISSUE TITLE
CollectSamErrorMetrics error

### ISSUE THREAD

**Issue by joegeorgeson** [broadinstitute/picard#1835]
Dear picard community,

I would like to run 'picard CollectSamErrorMetrics' but receive the below error. Can anyone offer advice?

a) GATK version used:

Picard version: Version:2.27.5

b) Exact command used:

```java -jar picard.jar CollectSamErrorMetrics --INPUT ./myBAM_Aligned.sortedByCoord.out.bam --OUTPUT ./myBAM_Aligned.sortedByCoord.out.bam.errorMetrics.txt --VCF ./gnomad.exomes.r2.0.2.sites.vcf --MIN_MAPPING_Q 0 --MIN_BASE_Q 20 --REFERENCE_SEQUENCE ./hg19.fa```

c) Entire program log: 

```20:27:56.348 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:~/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Mon Oct 10 20:27:56 IDT 2022] CollectSamErrorMetrics --INPUT ./myBAM_Aligned.sortedByCoord.out.bam --OUTPUT ./myBAM_Aligned.sortedByCoord.out.bam.errorMetrics.txt --VCF ./gnomad.exomes.r2.0.2.sites.vcf --MIN_MAPPING_Q 0 --MIN_BASE_Q 20 --REFERENCE_SEQUENCE ./hg19.fa --ERROR_METRICS ERROR --ERROR_METRICS ERROR:BASE_QUALITY --ERROR_METRICS ERROR:INSERT_LENGTH --ERROR_METRICS ERROR:GC_CONTENT --ERROR_METRICS ERROR:READ_DIRECTION --ERROR_METRICS ERROR:PAIR_ORIENTATION --ERROR_METRICS ERROR:HOMOPOLYMER --ERROR_METRICS ERROR:BINNED_HOMOPOLYMER --ERROR_METRICS ERROR:CYCLE --ERROR_METRICS ERROR:READ_ORDINALITY --ERROR_METRICS ERROR:READ_ORDINALITY:CYCLE --ERROR_METRICS ERROR:READ_ORDINALITY:HOMOPOLYMER --ERROR_METRICS ERROR:READ_ORDINALITY:GC_CONTENT --ERROR_METRICS ERROR:READ_ORDINALITY:PRE_DINUC --ERROR_METRICS ERROR:MAPPING_QUALITY --ERROR_METRICS ERROR:READ_GROUP --ERROR_METRICS ERROR:MISMATCHES_IN_READ --ERROR_METRICS ERROR:ONE_BASE_PADDED_CONTEXT --ERROR_METRICS OVERLAPPING_ERROR --ERROR_METRICS OVERLAPPING_ERROR:BASE_QUALITY --ERROR_METRICS OVERLAPPING_ERROR:INSERT_LENGTH --ERROR_METRICS OVERLAPPING_ERROR:READ_ORDINALITY --ERROR_METRICS OVERLAPPING_ERROR:READ_ORDINALITY:CYCLE --ERROR_METRICS OVERLAPPING_ERROR:READ_ORDINALITY:HOMOPOLYMER --ERROR_METRICS OVERLAPPING_ERROR:READ_ORDINALITY:GC_CONTENT --ERROR_METRICS INDEL_ERROR --PRIOR_Q 30 --MAX_LOCI 0 --LONG_HOMOPOLYMER 6 --LOCATION_BIN_SIZE 2500 --PROBABILITY 1.0 --PROGRESS_STEP_INTERVAL 100000 --INTERVAL_ITERATOR false --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Mon Oct 10 20:27:56 IDT 2022] Executing as user@place on Linux 3.10.0-514.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: Version:2.27.5
INFO 2022-10-10 20:27:56 CollectSamErrorMetrics Getting SamLocusIterator
INFO 2022-10-10 20:27:56 CollectSamErrorMetrics Using 26 aggregators.
INFO 2022-10-10 20:27:56 CollectSamErrorMetrics Starting iteration over loci
INFO 2022-10-10 20:27:56 CollectSamErrorMetrics Really starting iteration now.
[Mon Oct 10 20:36:31 IDT 2022] picard.sam.SamErrorMetric.CollectSamErrorMetrics done. Elapsed time: 8.59 minutes.
Runtime.totalMemory()=3184525312
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NullPointerException
at picard.sam.SamErrorMetric.ReadBaseStratification.stratifyReadGroup(ReadBaseStratification.java:1210)
at picard.sam.SamErrorMetric.ReadBaseStratification$2.stratify(ReadBaseStratification.java:171)
at picard.sam.SamErrorMetric.ReadBaseStratification$RecordStratifier.stratify(ReadBaseStratification.java:105)
at picard.sam.SamErrorMetric.ReadBaseStratification$CollectionStratifier.stratify(ReadBaseStratification.java:242)
at picard.sam.SamErrorMetric.BaseErrorAggregation.addBase(BaseErrorAggregation.java:55)
at picard.sam.SamErrorMetric.CollectSamErrorMetrics.addRecordAndOffset(CollectSamErrorMetrics.java:624)
at picard.sam.SamErrorMetric.CollectSamErrorMetrics.addLocusBases(CollectSamErrorMetrics.java:694)
at picard.sam.SamErrorMetric.CollectSamErrorMetrics.processData(CollectSamErrorMetrics.java:395)
at picard.sam.SamErrorMetric.CollectSamErrorMetrics.doWork(CollectSamErrorMetrics.java:509)
at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:309)
at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)```

**Comment by droazen** [comment]
@joegeorgeson This error indicates that there's at least one read in your bam that lacks a read group tag. Can you check your bam for the presence of read groups, and add them via `AddOrReplaceReadGroups` if they're missing?
