### ISSUE TITLE
CrosscheckFingerprints : Sequences at index 0 don't match:

### ISSUE THREAD

**Issue by MjelleLab** [broadinstitute/picard#1836]
I am running CrosscheckFingerprints and get an error related to the genome files it seems. I am using the haplotypes from the fingerprint_maps tools. 

### Affected tool(s)
CrosscheckFingerprints

java -jar build/libs/picard.jar CrosscheckFingerprints -H ../fingerprint_maps/map_files/hg19_chr.map -I sample.bam 

[Tue Oct 11 14:05:47 CEST 2022] picard.fingerprint.CrosscheckFingerprints done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2122317824
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: Failed to fingerprint
	at picard.fingerprint.FingerprintChecker.fingerprintFiles(FingerprintChecker.java:733)
	at picard.fingerprint.CrosscheckFingerprints.doWork(CrosscheckFingerprints.java:524)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:309)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
Caused by: java.util.concurrent.ExecutionException: htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequences at index 0 don't match: 0/249250621/chr1/AS=GRCh37/UR=http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta/M5=1b22b98cdeb4a9304cb5d48026a85128/SP=Homo Sapiens 0/16571/chrM
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at picard.fingerprint.FingerprintChecker.fingerprintFiles(FingerprintChecker.java:731)
	... 4 more
Caused by: htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequences at index 0 don't match: 0/249250621/chr1/AS=GRCh37/UR=http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta/M5=1b22b98cdeb4a9304cb5d48026a85128/SP=Homo Sapiens 0/16571/chrM
	at htsjdk.samtools.util.SequenceUtil.assertSequenceListsEqual(SequenceUtil.java:280)
	at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:342)
	at picard.fingerprint.FingerprintChecker.checkDictionaryGoodForFingerprinting(FingerprintChecker.java:228)
	at picard.fingerprint.FingerprintChecker.fingerprintSamFile(FingerprintChecker.java:526)
	at picard.fingerprint.FingerprintChecker.lambda$fingerprintFiles$10(FingerprintChecker.java:706)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by kachulis** [comment]
It looks like the first contig in the sequence dictionary in you bam is chrM, whereas in the haplotype map the sequence dictionary starts with chr1.  The dictionaries need to match (including their order).
