### ISSUE TITLE
Exception in thread "main" htsjdk.samtools.SAMException: Cannot read non-existent file

### ISSUE THREAD

**Issue by beaufor** [broadinstitute/picard#1846]
my code :
java -jar picard.jar AddOrReplaceReadGroups \
       I=/path/BoneMarrow_62016.bam \
       O=/path/bone2016_RG.bam \
       RGID=4 \
       RGLB=lib1 \
       RGPL=ILLUMINA \
       RGPU=unit1 \
       RGSM=20

The error report:
[Mon Nov 28 22:36:39 CST 2022] AddOrReplaceReadGroups INPUT=/path/BoneMarrow_62016.bam OUTPUT=/path/bone2016_RG.bam RGID=4 RGLB=lib1 RGPL=ILLUMINA RGPU=unit1 RGSM=20    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Nov 28 22:36:39 CST 2022] Executing as hxh@node3 on Linux 3.10.0-1160.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_262-b10; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.27.5
[Mon Nov 28 22:36:39 CST 2022] picard.sam.AddOrReplaceReadGroups done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2058354688
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Cannot read non-existent file: file:///path/BoneMarrow_62016.bam
        at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:498)
        at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:485)
        at htsjdk.samtools.util.IOUtil.assertInputIsValid(IOUtil.java:461)
        at picard.sam.AddOrReplaceReadGroups.doWork(AddOrReplaceReadGroups.java:147)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:309)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

I don'tknow the reasons.

**Comment by beaufor** [comment]
the path of bam file error

**Comment by zhangyuxin1012** [comment]
I have encountered the same error. How did you solve the above problem?

**Comment by tytr777** [comment]
Maybe change name can be helpful : change BoneMarrow_62016.bam like unmapped-queryname-sorted.bam. _ may not be welcome.
