### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by TKsh6** [broadinstitute/picard#1861]
No matter how much memory I set, this error will always be reported：
```
WARNING	2023-02-19 17:57:26	SortingCollection	There is not enough memory per file for buffering. Reading will be unbuffered.
INFO	2023-02-19 17:58:16	MarkDuplicates	Sorting list of duplicate records.
INFO	2023-02-19 17:58:50	MarkDuplicates	After generateDuplicateIndexes freeMemory: 14148538224; totalMemory: 29108994048; maxMemory: 29108994048
INFO	2023-02-19 17:58:50	MarkDuplicates	Marking 28724856 records as duplicates.
INFO	2023-02-19 17:58:50	MarkDuplicates	Found 1041970 optical duplicate clusters.
INFO	2023-02-19 18:29:32	MarkDuplicates	Reads are assumed to be ordered by: coordinate
[Sun Feb 19 18:35:00 CST 2023] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 355.92 minutes.
Runtime.totalMemory()=29914300416
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.StringBuffer.toString(StringBuffer.java:675)
	at java.io.StringWriter.toString(StringWriter.java:210)
	at htsjdk.samtools.SAMFileWriterImpl.writeHeader(SAMFileWriterImpl.java:255)
	at htsjdk.samtools.SAMFileWriterImpl.setHeader(SAMFileWriterImpl.java:149)
	at htsjdk.samtools.SAMFileWriterFactory.initializeBAMWriter(SAMFileWriterFactory.java:316)
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:301)
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:263)
	at htsjdk.samtools.SAMFileWriterFactory.makeSAMOrBAMWriter(SAMFileWriterFactory.java:444)
	at htsjdk.samtools.SAMFileWriterFactory.makeWriter(SAMFileWriterFactory.java:496)
	at htsjdk.samtools.SAMFileWriterFactory.makeWriter(SAMFileWriterFactory.java:461)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:297)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```
So how can I do to solve this problem?

yours tk,

**Comment by rickymagner** [comment]
Hi, have you tried using some of the suggestions in this [comment](https://github.com/broadinstitute/picard/issues/1773#issuecomment-1028291075)? I have found those suggestions helpful in the past for working with MarkDuplicates.
