### ISSUE TITLE
Sequence dictionaries are not the same size

### ISSUE THREAD

**Issue by pd3** [broadinstitute/picard#1869]
### Affected tool(s)
CollectHsMetrics

### Affected version(s)
Latest public release version [version 3.0.0]

### Description 
The program ends with the error
```
Sequence dictionaries are not the same size (3366, 195)
```
which is puzzling because as far as I can see, both the input CRAM file and the reference sequence have 3366 sequences.

The full command and the error message is:
```
CollectHsMetrics --BAIT_INTERVALS targets.bed.intervals --TARGET_INTERVALS targets.bed.intervals --INPUT input.cram  --VALIDATION_STRINGENCY SILENT --REFERENCE_SEQUENCE hs38DH.fa  \
--METRIC_ACCUMULATION_LEVEL ALL_READS --NEAR_DISTANCE 250 --MINIMUM_MAPPING_QUALITY 20 --MINIMUM_BASE_QUALITY 20 --CLIP_OVERLAPPING_READS true --INCLUDE_INDELS false --COVERAGE_CAP 200 --SAMPLE_SIZE 10000 --ALLELE_FRACTION 0.001 --ALLELE_FRACTION 0.005 --ALLELE_FRACTION 0.01 --ALLELE_FRACTION 0.02 --ALLELE_FRACTION 0.05 --ALLELE_FRACTION 0.1 --ALLELE_FRACTION 0.2 --ALLELE_FRACTION 0.3 --ALLELE_FRACTION 0.5 --VERBOSITY INFO --QUIET false --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false

Executing on Linux 4.15.0-208-generic amd64; Java HotSpot(TM) 64-Bit Server VM 20+36-2344; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: Version:3.0.0
WARNING 2023-04-07 12:12:09 CRAMFileReader  CRAM index file input.cram.crai is older than CRAM input.cram
[Fri Apr 07 12:12:10 BST 2023] picard.analysis.directed.CollectHsMetrics done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=3145728000
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequence dictionaries are not the same size (3366, 195)
    at htsjdk.samtools.util.SequenceUtil.assertSequenceListsEqual(SequenceUtil.java:259)
    at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:342)
    at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:328)
    at picard.analysis.directed.CollectTargetedMetrics.doWork(CollectTargetedMetrics.java:124)
    at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:289)
    at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:104)
    at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:114)
```

and the sequence dictionaries appear to be of the same size in both CRAM and the reference file:
```
$ samtools view -H input.cram | grep ^@SQ | wc -l
3366

$ cat hs38DH.dict | grep ^@SQ | wc -l
3366

$ cat  hs38DH.fa.fai | wc -l
3366

$ cat hs38DH.fa | grep '^>' | wc -l
3366
```

**Comment by jmarshall** [comment]
How many reference sequences are represented in _targets.bed.intervals_? (That's the file that the code at _CollectTargetedMetrics.java:124_ is comparing the CRAM headers to.)

**Comment by pd3** [comment]
27

**Comment by pd3** [comment]
I did not look in that file by eye until now, was assuming it's a bed file. Indeed, there are only 195 @SQ lines, it makes sense now. Thank you.

The check seems unnecessarily strict. It would be nice to allow cases where targets are a subset of the fasta reference sequence or give a more informative error message.

Thank you for your help

**Comment by jmarshall** [comment]
No worries. I think the idea is that — no matter what subset of the reference sequences actually have intervals on them — the Picard interval list `@SQ` headers should show that they are ~~mapped to~~ intended for exactly the same reference sequence dictionary as the other input files.

It would be nice if the error message told you which files it was complaining about! :smile:

**Comment by cmnbroad** [comment]
I'll make a single consolidated method in Picard for this, and then Chris can re-review.
