### ISSUE TITLE
picard markduplicate issue

### ISSUE THREAD

**Issue by Subhajeet1997** [broadinstitute/picard#1894]
[Wed Jun 21 19:30:24 IST 2023] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.17 minutes.
Runtime.totalMemory()=7247757312
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Value was put into PairInfoMap more than once.  1: RGA01580:48:HJVLLDSX3:3:1326:16215:30044
        at htsjdk.samtools.CoordinateSortedPairInfoMap.ensureSequenceLoaded(CoordinateSortedPairInfoMap.java:133)
        at htsjdk.samtools.CoordinateSortedPairInfoMap.remove(CoordinateSortedPairInfoMap.java:86)
        at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.remove(DiskBasedReadEndsForMarkDuplicatesMap.java:61)
        at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:560)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:270)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:289)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:104)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:114)
picard tool markduplicate error

**Comment by kockan** [comment]
@Subhajeet1997 The most common reason I've seen for that issue is the same read appearing more than once in your fastq files, so perhaps you could check whether there are multiple occurrences of the read name in the error message in your original fastqs?

**Comment by kockan** [comment]
Closing this issue for now. Feel free to reopen if there are any updates.
