### ISSUE TITLE
unable to run picard

### ISSUE THREAD

**Issue by shanmugavadivelps** [broadinstitute/picard#1911]
I am running picard tool for marking duplicate reads and encountering an error as below.

Pls suggest to solve the issue. 

picard MarkDuplicates I=Annigiri1.bam O=11.bam M=111.txt
INFO	2023-08-30 08:43:59	MarkDuplicates	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    MarkDuplicates -I Annigiri1.bam -O 11.bam -M 111.txt
**********

08:44:00.260 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/microbiology/anaconda3/envs/py38/share/picard-2.22.0-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Aug 30 08:44:00 IST 2023] MarkDuplicates INPUT=[Annigiri1.bam] OUTPUT=11.bam METRICS_FILE=111.txt    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag CLEAR_DT=true DUPLEX_UMI=false ADD_PG_TAG_TO_READS=true REMOVE_DUPLICATES=false ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Aug 30 08:44:00 IST 2023] Executing as microbiology@iipr on Linux 6.1.0-11-amd64 amd64; OpenJDK 64-Bit Server VM 1.8.0_332-b09; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.22.0-SNAPSHOT
INFO	2023-08-30 08:44:00	MarkDuplicates	Start of doWork freeMemory: 501944256; totalMemory: 514850816; maxMemory: 1908932608
INFO	2023-08-30 08:44:00	MarkDuplicates	Reading input file and constructing read end information.
INFO	2023-08-30 08:44:00	MarkDuplicates	Will retain up to 6916422 data points before spilling to disk.
WARNING	2023-08-30 08:44:00	AbstractOpticalDuplicateFinderCommandLineProgram	A field field parsed out of a read name was expected to contain an integer and did not. Read name: SRR13558034.2316196. Cause: String 'SRR13558034.2316196' did not start with a parsable number.
INFO	2023-08-30 08:44:07	MarkDuplicates	Read     1,000,000 records.  Elapsed time: 00:00:06s.  Time for last 1,000,000:    6s.  Last read position: NC_021160.1:14,082,604
INFO	2023-08-30 08:44:07	MarkDuplicates	Tracking 38823 as yet unmatched pairs. 1360 records in RAM.
[Wed Aug 30 08:44:16 IST 2023] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.27 minutes.
Runtime.totalMemory()=1461714944
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: /tmp/microbiology/CSPI.42174369459495610.tmp/6415.tmpnot found
	at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:64)
	at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:49)
	at htsjdk.samtools.util.ResourceLimitedMap.get(ResourceLimitedMap.java:76)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.getOutputStreamForSequence(CoordinateSortedPairInfoMap.java:180)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.put(CoordinateSortedPairInfoMap.java:164)
	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.put(DiskBasedReadEndsForMarkDuplicatesMap.java:65)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:566)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
Caused by: java.io.FileNotFoundException: /tmp/microbiology/CSPI.42174369459495610.tmp/6415.tmp (Too many open files)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:61)
	... 10 more

**Comment by kockan** [comment]
Based on the line `Caused by: java.io.FileNotFoundException: /tmp/microbiology/CSPI.42174369459495610.tmp/6415.tmp (Too many open files)` this looks like an issue caused by the maximum open file limit imposed by your OS. Could you try increasing this limit (the exact command will depend on your OS, but shouldn't be hard to find) and try again?

**Comment by lbergelson** [comment]
@shanmugavadivelps We haven't heard back from you so I'm assuming this is solved. Feel free to reopen if you're still having issues.
