### ISSUE TITLE
picard MarkDuplicates error: Value was put into PairInfoMap more than once

### ISSUE THREAD

**Issue by RSchley** [broadinstitute/picard#1923]
Hi there, 

I have multiple read files, sequenced from the same library with the same UMI on multiple lanes. I combined these read files per-sample first (i.e. combined the same sample from across different lanes), following which I ran:

`bwa-mem2 mem -M -t 12 Reference.fasta Sample_name_R1_trimmed.fastq.gz Sample_name_R2_trimmed.fastq.gz | samtools view -b | samtools sort -T "Sample_name" > Sample_name_sort.bam`

That worked OK, but when I run picard MarkDuplicates like this:

`picard \
 MarkDuplicates REMOVE_DUPLICATES=true \
 ASSUME_SORTED=true VALIDATION_STRINGENCY=SILENT \
 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 \
 INPUT=Sample_name_sort.bam \
 OUTPUT=Sample_name.rmd.bam \
 METRICS_FILE=Sample_name.rmd.bam.metrics
`

I get this error:

**Exception in thread "main" htsjdk.samtools.SAMException: Value was put into PairInfoMap more than once.  1: RGA00940:309:HHGT2DSX7:2:1101:22462:12117:CTGTTTCAGTT
	at htsjdk.samtools.CoordinateSortedPairInfoMap.ensureSequenceLoaded(CoordinateSortedPairInfoMap.java:133)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.remove(CoordinateSortedPairInfoMap.java:86)
	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.remove(DiskBasedReadEndsForMarkDuplicatesMap.java:61)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:558)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:258)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)**

What should I do? Map the read files from different lanes separately and then combine them? I would rather map them all at once into the same BAM file.

Thanks a lot
Rowan

**Comment by kockan** [comment]
Hi @RSchley , I believe this error is usually due to the same read name(s) appearing multiple times in the input fastq(s). Have you already checked out some of the suggested solutions here: https://gatk.broadinstitute.org/hc/en-us/community/posts/4408717387803-SAMException-Value-was-put-into-PairInfoMap-more-than-once

**Comment by kockan** [comment]
Closed for now. If user has tried the linked suggestions and still has issues, reopen.
