### ISSUE TITLE
Running picard in parallel issue

### ISSUE THREAD

**Issue by Davood-Norouzi** [broadinstitute/picard#1958]
I am using picard 2.18.29 on bioconda.

I have encountered a very strange issue. When I try to run multiple picard MarkDuplicates together, the processes get interrupted after a while. When I do them separately it works fine. I have 2T of free space, 64 CPU cores and 256MB of RAM. I run 5 picard commands like this one below together and they work till they stop. The bam files are less than 30GB in size.

>> picard MarkDuplicates  I=sorted_S3512.bam  O=S3512_dup.bam  M=S3512_matrix.txt  REMOVE_DUPLICATES=false

The input and output files of these commands are different. The error message is something like below. It seems that it is saying there is not enough space left on disk. But I have more that 2T left and while one of the commands breaks the rest continue for quite a while. So, how can it be a disk issue. It doesn't even reach the stage to write the output bam files, so definitely no extra space is used.

Is this a RAM memory management issue with picard or java?

error:
Exception in thread "main" picard.PicardException: Exception writing ReadEnds to file.
	at picard.sam.markduplicates.util.ReadEndsForMarkDuplicatesCodec.encode(ReadEndsForMarkDuplicatesCodec.java:74)
	at picard.sam.markduplicates.util.ReadEndsForMarkDuplicatesCodec.encode(ReadEndsForMarkDuplicatesCodec.java:32)
	at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:255)
	at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:183)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:579)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:264)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
	Suppressed: java.io.IOException: No space left on device
		at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
		at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
		at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
		at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
		at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280)
		at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
		at java.base/java.nio.channels.Channels.writeFully(Channels.java:97)
		at java.base/java.nio.channels.Channels$1.write(Channels.java:172)
		at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
		at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
		at org.xerial.snappy.SnappyOutputStream.dumpOutput(SnappyOutputStream.java:360)
		at org.xerial.snappy.SnappyOutputStream.compressInput(SnappyOutputStream.java:374)
		at org.xerial.snappy.SnappyOutputStream.flush(SnappyOutputStream.java:334)
		at org.xerial.snappy.SnappyOutputStream.close(SnappyOutputStream.java:397)
		at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:260)
		... 6 more
Caused by: java.io.IOException: No space left on device
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280)
	at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
	at java.base/java.nio.channels.Channels.writeFully(Channels.java:97)
	at java.base/java.nio.channels.Channels$1.write(Channels.java:172)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
	at org.xerial.snappy.SnappyOutputStream.dumpOutput(SnappyOutputStream.java:360)
	at org.xerial.snappy.SnappyOutputStream.compressInput(SnappyOutputStream.java:374)
	at org.xerial.snappy.SnappyOutputStream.write(SnappyOutputStream.java:319)
	at java.base/java.io.DataOutputStream.writeShort(DataOutputStream.java:167)
	at picard.sam.markduplicates.util.ReadEndsForMarkDuplicatesCodec.encode(ReadEndsForMarkDuplicatesCodec.java:55)
	... 8 more

**Comment by yfarjoun** [comment]
I'm guessing that you have a smaller partition which is used for temporary
files.

try this:
https://www.biostars.org/p/42613/

you can also look at the state of your partitions using 'df' while picard
is running and see which partition is filling up.

**Comment by Davood-Norouzi** [comment]
Adding   -Djava.io.tmpdir=/path/to/tmp   worked. Thanks a lot!
Cannot believe java is not returning a more understandable error message.

**Comment by yfarjoun** [comment]
It takes some practice to read these tea leaves...but what caught my eye
was:

Caused by: java.io.IOException:* No space left on device*

Glad to hear it worked...

Yossi.
