### ISSUE TITLE
Can CollectWgsMetrics fall back to slow algorithm gracefully if the fast one fails with the default read length?

### ISSUE THREAD

**Issue by gokalpcelik** [broadinstitute/picard#1970]
This issue seems to be present in the latest version as well. I have a collection of WGS bam files (#>100) and fast algorithm works gracefully for most of them whereas only a few of them fail with the same error due to read length is not being optimal

```
java.lang.ArrayIndexOutOfBoundsException: The requested index 1247601 is out of counter bounds. Possible cause of exception can be wrong READ_LENGTH parameter (much smaller than actual read length)
	at picard.analysis.CounterManager$Counter.checkIndex(CounterManager.java:189)
	at picard.analysis.CounterManager$Counter.get(CounterManager.java:183)
	at picard.analysis.FastWgsMetricsCollector.processRecord(FastWgsMetricsCollector.java:137)
	at picard.analysis.FastWgsMetricsCollector.addInfo(FastWgsMetricsCollector.java:105)
	at picard.analysis.WgsMetricsProcessorImpl.processFile(WgsMetricsProcessorImpl.java:93)
	at picard.analysis.CollectWgsMetrics.doWork(CollectWgsMetrics.java:242)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:280)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:37)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:166)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:209)
	at org.broadinstitute.hellbender.Main.main(Main.java:306)
```
I can understand that this parameter is important for estimates however instead of failing can the tool fall back to the slow algorithm gracefully?

**Comment by lbergelson** [comment]
@gokalpcelik What are you envisioning exactly? If it encounters an error it will restart at the beginning of the bam with the slow algorithm?  Or it will process a specific read with the other algorithm and then combines them?

**Comment by lbergelson** [comment]
That seems reasonable then.

**Comment by lbergelson** [comment]
I wonder if it's possible to make the Fast collector work on these files? 

If it's just retrying with the other collector that seems pretty simple, but kind of gross. Do you want to implement that?   I might change the arguments so instead of USE_FAST_ALGORITHM we have a set of inputs SLOW, FAST,  TRY_FAST_AND_FALL_BACK or something like that so you can control the behavior.

**Comment by kockan** [comment]
@lbergelson It is the issue. The `READ_LENGTH` parameter is used by `FastWgsMetricCollector` to allocate arrays (wrapped by `CounterManager`) and if some of your reads are longer than the value of `READ_LENGTH` this might cause `ArrayIndexOutOfBoundsException` in certain cases. Unfortunately, there is no way to set this value in a smart way without performing a first pass over your alignment file and get the maximum read length, and dynamically reallocating arrays at runtime _should be_ a no-go since it affects the processing of previous alignments (don't quote me on this, maybe this can be done somehow, I am not familiar with the intricacies of `FastWgsMetricCollector`).

cc: @gokalpcelik

**Comment by multimeric** [comment]
> The READ_LENGTH parameter is used by FastWgsMetricCollector to allocate arrays (wrapped by CounterManager) and if some of your reads are longer than the value of READ_LENGTH this might cause ArrayIndexOutOfBoundsException in certain cases. 

If this is true, then perhaps the argument is mislabelled? [Currently it is described as the *average* read length](https://gatk.broadinstitute.org/hc/en-us/articles/360037269351-CollectWgsMetrics-Picard#--READ_LENGTH).

**Comment by clintval** [comment]
I hit this too and debugging was tricky. Glad this issue was opened!

I have 100 cycle read data and am relying on the default `--READ_LENGTH` value of 150 but still hit the index out of bounds exceptions on some samples. It doesn't make sense to me why read length must be known ahead of time or why the average read length appears to be treated as "max read length". My exception is:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: The requested index 4198050 is out of counter bounds. Possible cause of exception can be wrong READ_LENGTH parameter (much smaller than actual read length)
```

I'm going to try something naive like:

```bash
picard \
    -Xmx${memory}M \
    CollectWgsMetrics \
        --VALIDATION_STRINGENCY SILENT \
        --INPUT ${bam} \
        --OUTPUT ${sample}.${library}.wgs_metrics.txt \
        --REFERENCE_SEQUENCE ${fasta} \
        --USE_FAST_ALGORITHM true \
        ${intervals} \
|| picard \
    -Xmx${memory}M \
    CollectWgsMetrics \
        --VALIDATION_STRINGENCY SILENT \
        --INPUT ${bam} \
        --OUTPUT ${sample}.${library}.wgs_metrics.txt \
        --REFERENCE_SEQUENCE ${fasta} \
        ${intervals}
```

Alternatively, I'll see if I can't get what I need out of [`mosdepth`](https://pmc.ncbi.nlm.nih.gov/articles/PMC6030888/).
