### ISSUE TITLE
CollectMultipleMetrics IllegalArgumentException in 1.134

### ISSUE THREAD

**Issue by jeremiahsavage** [broadinstitute/picard#225]
I can run 1.133 on a particular BAM without error.

```
$ java -d64 -jar picard-tools-1.133/picard.jar CollectMultipleMetrics INPUT=2817851434.bam OUTPUT=2817851434.bam.metrics VALIDATION_STRINGENCY=LENIENT
[Wed Jun 17 16:58:19 UTC 2015] picard.analysis.CollectMultipleMetrics INPUT=2817851434.bam OUTPUT=2817851434.bam.metrics VALIDATION_STRINGENCY=LENIENT    ASSUME_SORTED=true STOP_AFTER=0 PROGRAM=[CollectAlignmentSummaryMetrics, CollectInsertSizeMetrics, QualityScoreDistribution, MeanQualityByCycle, CollectBaseDistributionByCycle] VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Jun 17 16:58:19 UTC 2015] Executing as ubuntu@frontend001 on Linux 3.13.0-53-generic amd64; OpenJDK 64-Bit Server VM 1.7.0_79-b14; Picard version: 1.133(95818b6e611725775e29d3b4acbaa23747eb3e94_1433169311) IntelDeflater
INFO	2015-06-17 16:58:23	SinglePassSamProgram	Processed     1,000,000 records.  Elapsed time: 00:00:04s.  Time for last 1,000,000:    4s.  Last read position: chr2:121,708,696
.
.
.
```
 However, with 1.134, I get
```
$ java -d64 -jar picard-tools-1.134/picard.jar CollectMultipleMetrics INPUT=2817851434.bam OUTPUT=2817851434.bam.metrics VALIDATION_STRINGENCY=LENIENT
[Wed Jun 17 16:57:46 UTC 2015] picard.analysis.CollectMultipleMetrics INPUT=2817851434.bam OUTPUT=2817851434.bam.metrics VALIDATION_STRINGENCY=LENIENT    ASSUME_SORTED=true STOP_AFTER=0 PROGRAM=[CollectAlignmentSummaryMetrics, CollectInsertSizeMetrics, QualityScoreDistribution, MeanQualityByCycle, CollectBaseDistributionByCycle, CollectGcBiasMetrics] VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Jun 17 16:57:46 UTC 2015] Executing as ubuntu@frontend001 on Linux 3.13.0-53-generic amd64; OpenJDK 64-Bit Server VM 1.7.0_79-b14; Picard version: 1.134(a7a08c474e4d99346eec7a9956a8fe71943b5d80_1434033355) IntelDeflater
[Wed Jun 17 16:57:46 UTC 2015] picard.analysis.CollectMultipleMetrics done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2058354688
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Cannot check readability of null file.
	at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:306)
	at picard.analysis.CollectGcBiasMetrics.setup(CollectGcBiasMetrics.java:126)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:98)
	at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:199)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:206)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
```

**Comment by nh13** [comment]
I think it is because you are not specifying ```REFERENCE_SEQUENCE``` on the command line.  

@vdauwera @kbergin  we should add custom command line validation for when GcBiasMetrics are computed within CollectMultipleMetrics.

**Comment by tfenne** [comment]
I might also suggest *not* making CollectGcBiasMetrics a default operation for CollectMultipleMetrics.  This bit me too during an upgrade.  It's the only default tool that isn't designed to work on *any* BAM, but is specific to WGS.

**Comment by kbergin** [comment]
this is related to https://github.com/broadinstitute/picard-private/pull/315 and #221 for reference..

**Comment by yfarjoun** [comment]
Shouldn't be related to picard-private issues.

I like the suggestion by Tim to make the CollectGcBiasMetrics non-default.

Jeremiyah, currently, as a workaround, you'll need to either provide a
Reference_sequence as mentioned, or remove the CollectGcBiasMetrics from
the list of programs.

**Comment by jeremiahsavage** [comment]
I ran 134 with ```REFERENCE_SEQUENCE``` and that is a fine workaround. Thanks Nils and Yossi.

**Comment by yfarjoun** [comment]
can this be fixed properly?

1. remove CollectGcBiasMetrics from default list
2. improve argument validation as per Nils.

**Comment by kbergin** [comment]
Yes, to both parts. I worked on fixing it today with Nils and Louis's help, should be able to finish it up tomorrow!

**Comment by yfarjoun** [comment]
Fantastic!

**Comment by yfarjoun** [comment]
I think this issue can be closed.

**Comment by kbergin** [comment]
I think so too, we addressed this.
