### ISSUE TITLE
Want better error reporting for Picard RevertSam fail

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#256]
As a newbie, not clear that Exception=error and what device=disk is being referenced. I had no clue this was related to the temporary directory. What would be most helpful is a suggestion to try TMP_DIR=[] or -Djava.io.tmpdir='pwd'/tmp. Thanks.

Stack trace after ~5 hours run time and 0 byte output:
[Mon Aug 10 15:12:34 EDT 2015] picard.sam.RevertSam done. Elapsed time: 321.26 minutes.
Runtime.totalMemory()=3093299200
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.io.IOException: No space left on device
at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:245)
at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:165)

**Comment by akiezun** [comment]
can you paste the whole stacktrace? ie all the way to main(String[])

**Comment by sooheelee** [comment]
Here's a txt of it.

[20150810_SamToFastq_fail_output.txt | uploaded via ZenHub](https://files.zenhub.io/55ca689131cbb33338870bad)

**Comment by akiezun** [comment]
it's a problem in htsjdk, not picard. SortingCollection.spillToDisk should print out more informative message on all paths. 
closing this.
