### ISSUE TITLE
Missing R scripts in maven jar

### ISSUE THREAD

**Issue by ffinfo** [broadinstitute/picard#270]
In the jar on maven central the R scripts are missing, see:
https://github.com/broadinstitute/picard/tree/master/src/scripts/picard/analysis

Because of this de following error can occur:

```
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp             
Exception in thread "main" java.lang.IllegalArgumentException: Script [picard/analysis/meanQualityByCycle.R] not found in classpath                                
        at picard.util.RExecutor.writeScriptFile(RExecutor.java:90)
        at picard.util.RExecutor.executeFromClasspath(RExecutor.java:58)
        at picard.analysis.MeanQualityByCycle.finish(MeanQualityByCycle.java:194)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:133)
        at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:177)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:206)
        at picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:145)
        at picard.analysis.CollectMultipleMetrics.main(CollectMultipleMetrics.java:140)
```

This happens for example when executing picard within a Queue pipeline. Workaround is to add those files manual but they should be packaged in the jar.

**Comment by yfarjoun** [comment]
is this still the case?

**Comment by vdauwera** [comment]
I'm going to guess it's not.
