### ISSUE TITLE
Exception running ValidateSam

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/picard#277]
Any suggestions for the error below.   There are only two reads with E00116:30:H0BL7ALXX:7:2202:27755:2311 but they are not pointing to each other. 
# 

Starting on : Thu Sep  3 14:46:15 EDT 2015
Running on node : scc-ca3
Current directory : /restricted/projectnb/sickle_cell/challenge/users/eshaikho/gem_wgs/MS-7
Current job ID : 8063906
Current job name : validate.sh
# Task index number : undefined

Picked up _JAVA_OPTIONS: -Xmx20g
[Thu Sep 03 14:46:16 EDT 2015] picard.sam.ValidateSamFile INPUT=/restricted/projectnb/sickle_cell/challenge/users/eshaikho/gem_wgs/MS-7/MS-7_fixed.bam OUTPUT=error_summary_ms7 MODE=SUMMARY    MAX_OUTPUT=100 IGNORE_WARNINGS=false VALIDATE_INDEX=true IS_BISULFITE_SEQUENCED=false MAX_OPEN_TEMP_FILES=8000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Thu Sep 03 14:46:16 EDT 2015] Executing as eshaikho@scc-ca3.scc.bu.edu on Linux 2.6.32-504.16.2.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.7.0_21-b11; Picard version: 1.138(aa51703435dc6a423013e74e56b0b68405facd79_1439324166) IntelDeflater
INFO    2015-09-03 14:47:56    SamFileValidator    Validated Read    10,000,000 records.  Elapsed time: 00:01:40s.  Time for last 10,000,000:  100s.  Last read position: 1:40,405,717
INFO    2015-09-03 14:49:35    SamFileValidator    Validated Read    20,000,000 records.  Elapsed time: 00:03:19s.  Time for last 10,000,000:   99s.  Last read position: 1:79,677,403
INFO    2015-09-03 14:51:13    SamFileValidator    Validated Read    30,000,000 records.  Elapsed time: 00:04:57s.  Time for last 10,000,000:   98s.  Last read position: 1:119,110,457
INFO    2015-09-03 14:52:53    SamFileValidator    Validated Read    40,000,000 records.  Elapsed time: 00:06:37s.  Time for last 10,000,000:   99s.  Last read position: 1:171,339,164
INFO    2015-09-03 14:54:32    SamFileValidator    Validated Read    50,000,000 records.  Elapsed time: 00:08:16s.  Time for last 10,000,000:   98s.  Last read position: 1:210,844,931
[Thu Sep 03 14:56:10 EDT 2015] picard.sam.ValidateSamFile done. Elapsed time: 9.90 minutes.
Runtime.totalMemory()=1608318976
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Value was put into PairInfoMap more than once.  1: E00116:30:H0BL7ALXX:7:2202:27755:2311
    at htsjdk.samtools.CoordinateSortedPairInfoMap.ensureSequenceLoaded(CoordinateSortedPairInfoMap.java:132)
    at htsjdk.samtools.CoordinateSortedPairInfoMap.remove(CoordinateSortedPairInfoMap.java:86)
    at htsjdk.samtools.SamFileValidator$CoordinateSortedPairEndInfoMap.remove(SamFileValidator.java:724)
    at htsjdk.samtools.SamFileValidator.validateMateFields(SamFileValidator.java:465)
    at htsjdk.samtools.SamFileValidator.validateSamRecordsAndQualityFormat(SamFileValidator.java:276)
    at htsjdk.samtools.SamFileValidator.validateSamFile(SamFileValidator.java:199)
    at htsjdk.samtools.SamFileValidator.validateSamFileSummary(SamFileValidator.java:127)
    at picard.sam.ValidateSamFile.doWork(ValidateSamFile.java:163)
    at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:206)
    at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
#     at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
# Finished on : Thu Sep  3 14:56:10 EDT 2015

**Comment by yfarjoun** [comment]
Could you paste here these two reads? I'm guessing that they are both
marked as read1 or something like that.

**Comment by jjfarrell** [comment]
Thanks for taking a look. Here are the 2 reads:

E00116:30:H0BL7ALXX:7:2122:23989:33235  401     1       25507   0       38M113H 19      66883   0       AAGAGGAAAGAGGTGCCTGTGGGGGTGGAGGACAGGAA  8->-?;><@@?;8-@>?@?3==??=-?>>?>=@:<=<= SA:Z:1,25551,-,83S68M,0,0;      BD:Z:IIJLKJBIIJLLGMMLNHGLIIILGLKKMLNJPOKJII     MD:Z:38 PG:Z:MarkDuplicates     RG:Z:MS-7_ATTCAGAA_H0BL7ALXX_L007      BI:Z:LLKNIJEKKJMLINOLOJJMIIIMJMJKNKOLOOJKKK     NM:i:0  AS:i:38 XS:i:38



E00116:30:H0BL7ALXX:7:2122:23989:33235  145     1       25551   0       83S68M  19      66883   0       AAGAGGAAAGAGGTGCCTGTGGGGGTGGAGGACAGGAAAGAACACCAAAGAACAGATGCGCTTCCTAACCCTGGCTCCAGGGGACACTCCTGGAATTGCAAAGTGAGGGCAGAGTCTATTTATATTGGGTTTAATTAACTCCTCTCCCTGG        8.:.?;>=BB@;:,A?@BA5>>@@=,A>@@><BB>B@>A?@@<98A8@AA@@AAAA?A;A?@<@AA?;;7?@@AA=3@@@@@@@A?A==@;=@?@>@@@????>@@??@@>@@??@@@??@@@??@?=???@?@?@??@=?@?@>?><><=        SA:Z:1,25507,-,38M113S,0,0;     BD:Z:IIJLJJCKKLNNINNMOIHMJJJMHMLKMLLHMLKJBIIJJHHLLJBIIJJHMILLMKJNJJKLMJJLILNLMNKKLMLIIKLHHMKKLNLKJJJJMNJBILGLJLIMNMIJLLJMJJCJJJJJJLILJCJJJJJJJMKKMLKMMLONLII   MD:Z:68 PG:Z:MarkDuplicates    RG:Z:MS-7_ATTCAGAA_H0BL7ALXX_L007       BI:Z:LLKNKLHNONQOLQQOQLKNJJJNKNKLOKOLOOKLGMMLMLJOLMFLLKLKNLMMOMLPMKLMNMLNJMOMNPMLLNNIIJNKJNMLMOMJKKLLONMFLNJNKNINNNLKNMLMLKEKLLLKKLHMKFLMKLLMLNMLMMMNMKNOMKK   NM:i:0  AS:i:68 XS:i:68

**Comment by kirkmcclure** [comment]
Both have PAIRED and READ2 flags. So, without a read1 alignment, the (1.139) ValidateSamFile error seems to be descriptive:
````
>java -jar picard.jar ValidateSamFile I=issue277Example.bam
... Picard version: 1.139(8ceee52414e8ab9d13e350ff9cd86d48825dd64d_1442240108) JdkDeflater
ERROR: Read name E00116:30:H0BL7ALXX:7:2122:23989:33235, Mate not found for paired read
````
BTW - FixMateInformation has no effect

**Comment by yfarjoun** [comment]
This might be a bug, but I want to get more feedback from other
developers...

The flags of these reads are as such:

>
> 401 =  100010011000
> 145 = 100010010000


In particular the first is not a primary alignment, but both reads are
marked as "paired, not in proper-pair, and second read."

Since they are not properly mated, I'm guessing that the function
validateMateFields
should have returned very early on but the if statement only looks to see
the 0x1(mated) but doesn't check the 0x2(in proper pair).

Is this how it should be?

**Comment by vdauwera** [comment]
Closing due to lack of activity.
