### ISSUE TITLE
CollectVariantCallingMetrics fails when the VCF has no contig header lines

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#298]
It should not fail (from a user's perspective) since ```SEQUENCE_DICTIONARY``` is passed in.

```Exception in thread "main" java.lang.NullPointerException
    at picard.vcf.processor.VcfFileSegmentGenerator$ByWholeContig.readSequences(VcfFileSegmentGenerator.java:112)
    at picard.vcf.processor.VcfFileSegmentGenerator$ByWholeContig.forVcf(VcfFileSegmentGenerator.java:98)
    at picard.vcf.processor.VcfFileSegmentGenerator$WidthLimitingDecorator.forVcf(VcfFileSegmentGenerator.java:194)
    at picard.vcf.processor.VcfFileSegmentGenerator$1.forVcf(VcfFileSegmentGenerator.java:64)
    at picard.vcf.processor.VariantIteratorProducer$Threadsafe.<init>(VariantIteratorProducer.java:140)
    at picard.vcf.processor.VariantIteratorProducer.byHundredMegabaseChunksWithOnTheFlyFilteringByInterval(VariantIteratorProducer.java:72)
    at picard.vcf.processor.VariantProcessor$Builder.composeVcfIteratorProducerFromBuilderArguments(VariantProcessor.java:166)
    at picard.vcf.processor.VariantProcessor$Builder.build(VariantProcessor.java:149)
    at picard.vcf.CollectVariantCallingMetrics.doWork(CollectVariantCallingMetrics.java:128)
    at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:206)
    at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
    at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)```

**Comment by vdauwera** [comment]
Do we really want to enable use of VCFs without complete headers? I know it's spec-legal, but it's poor practice...
