### ISSUE TITLE
CollectSequencingArtifactMetricsTest fails on Java 8

### ISSUE THREAD

**Issue by mattsooknah** [broadinstitute/picard#301]
Running ```ant single-test -Dname=CollectSequencingArtifactMetricsTest``` with Java 8 results in one failed test:

```
   [testng] PASSED: testUnmappedMate
   [testng] PASSED: testIntervalList
   [testng] PASSED: testNoBqCutoff
   [testng] PASSED: testDbSnp
   [testng] PASSED: testNoMqCutoff
   [testng] FAILED: testContext
   [testng] java.lang.AssertionError: expected:<true> but was:<false>
   [testng]     at picard.analysis.artifacts.CollectSequencingArtifactMetricsTest.assertAllFilesEqual(CollectSequencingArtifactMetricsTest.java:75)
   [testng]     at picard.analysis.artifacts.CollectSequencingArtifactMetricsTest.runAnalysis(CollectSequencingArtifactMetricsTest.java:67)
   [testng]     at picard.analysis.artifacts.CollectSequencingArtifactMetricsTest.testContext(CollectSequencingArtifactMetricsTest.java:84)
   [testng] ... Removed 25 stack frames
```

However, the same test works fine using Java 7. I suspect this is another Java 8 iteration order bug, where the expected metrics output was produced under Java 7 and thus has a different ordering than the computed output.

**Comment by eitanbanks** [comment]
@yfarjoun didn't you fix this already?

**Comment by yfarjoun** [comment]
I thought so...but I can't find the PR that did it...so perhaps no.

**Comment by yfarjoun** [comment]
resolved.
