### ISSUE TITLE
MarkDuplicates not working with cram input file

### ISSUE THREAD

**Issue by mmoisse** [broadinstitute/picard#361]
When I try to dedup a cram file I get an error telling me a reference genome should be supplied, although one of my arguments is the reference genome.

```
[Thu Dec 10 11:01:48 CET 2015] picard.sam.markduplicates.MarkDuplicatesWithMateCigar 
  INPUT=[/home/test/test.cram] OUTPUT=/home/test/test.dedup.cram 
  METRICS_FILE=/home/test/test.dedup_metrix.txt VERBOSITY=DEBUG
  REFERENCE_SEQUENCE=/home/test/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz    
  MINIMUM_DISTANCE=-1 SKIP_PAIRS_WITH_NO_MATE_CIGAR=true BLOCK_SIZE=100000 
  REMOVE_DUPLICATES=false ASSUME_SORTED=false 
  DUPLICATE_SCORING_STRATEGY=TOTAL_MAPPED_REFERENCE_LENGTH 
  PROGRAM_RECORD_ID=MarkDuplicates 
  PROGRAM_GROUP_NAME=MarkDuplicatesWithMateCigar
  READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* 
  OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 QUIET=false 
  VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 
  MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false 
  GA4GH_CLIENT_SECRETS=client_secrets.json
[Thu Dec 10 11:01:48 CET 2015] Executing as test@test on Linux 3.16.0-53-generic amd64; 
  OpenJDK 64-Bit Server VM 1.8.0_45-internal-b14; Picard version: 2.0.1
  (fe51f432e4b918385037e6d15e958f0298203e28_1449251266) IntelDeflater
[Thu Dec 10 11:01:48 CET 2015] picard.sam.markduplicates.MarkDuplicatesWithMateCigar 
  done. Elapsed time: 0,00 minutes.
  Runtime.totalMemory()=251658240
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.cram.CRAMException: 
A reference source is required for CRAM files
        at htsjdk.samtools.CRAMIterator.<init>(CRAMIterator.java:86)
        at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:130)
        at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:146)
        at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:152)
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:273)
        at picard.sam.markduplicates.util.AbstractMarkDuplicatesCommandLineProgram.openInputs(AbstractMarkDuplicatesCommandLineProgram.java:204)
        at picard.sam.markduplicates.MarkDuplicatesWithMateCigar.doWork(MarkDuplicatesWithMateCigar.java:96)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
```

**Comment by mmterpstra** [comment]
Not official comment: 

`/home/test/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz`
Never knew you could use the gzipped variant as reference sequence. You could try and unzip the reference sequence (and maybe index it with `samtools faidx` / `java -jar picard.jar CreateSequenceDictionary`).

Good luck!

**Comment by mmoisse** [comment]
The ref genome is bgzipped and I could create a dictionary with ``java -jar picard.jar CreateSequenceDictionary`` on this bgzipped ref file. Also bwa didn't complain about the bgzipped ref genome.
I also tried to dedup while providing the unzipped version of the ref genome, without luck.

**Comment by yfarjoun** [comment]
there have been several improvements in the CRAM code...is this still a problem?
