### ISSUE TITLE
net.sf.samtools.SAMFormatException: Invalid record length: 0

### ISSUE THREAD

**Issue by songmm19900210** [broadinstitute/picard#370]
Exception in thread "main" net.sf.samtools.SAMFormatException: Invalid record length: 0 	at net.sf.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:185) 	at net.sf.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:558) 	at net.sf.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:532) 	at net.sf.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:522) 	at net.sf.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:481) 	at net.sf.samtools.SAMFileReader$AssertableIterator.next(SAMFileReader.java:672) 	at net.sf.samtools.SAMFileReader$AssertableIterator.next(SAMFileReader.java:650) 	at net.sf.picard.sam.AddOrReplaceReadGroups.doWork(AddOrReplaceReadGroups.java:98) 	at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:177) 	at net.sf.picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:119) 	at net.sf.picard.sam.AddOrReplaceReadGroups.main(AddOrReplaceReadGroups.java:66)

**Comment by songmm19900210** [comment]
Exception in thread "main" net.sf.samtools.SAMFormatException: Invalid record length: 0 	at net.sf.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:185) 	at net.sf.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:558) 	at net.sf.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:532) 	at net.sf.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:522) 	at net.sf.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:481) 	at net.sf.samtools.SAMFileReader$AssertableIterator.next(SAMFileReader.java:672) 	at net.sf.samtools.SAMFileReader$AssertableIterator.next(SAMFileReader.java:650) 	at net.sf.picard.sam.AddOrReplaceReadGroups.doWork(AddOrReplaceReadGroups.java:98) 	at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:177) 	at net.sf.picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:119) 	at net.sf.picard.sam.AddOrReplaceReadGroups.main(AddOrReplaceReadGroups.java:66)

**Comment by songmm19900210** [comment]
i used AddOrReplaceReadGroups.jar to SNP analysis. it come out a error: the error is SAMFormatException: Invalid record length: 0. if there is a BAM file is not right? how can i deal with it?
my command is java -XX:ParallelGCThreads=5 -Xmx50g -Djava.io.tmpdir=*/tmp -jar AddOrReplaceReadGroups.jar I=g01.bam O=g01.bam.sorted.bam SO=coordinate RGID=g01 RGLB=library RGPL=ILLUMINA RGPU=machine RGSM=g01.

**Comment by yfarjoun** [comment]
Hello,

You are using a very old version of picard, which makes it difficult to
understand your error message.

Please upgrade to the a recent version, and if you could also make a
smaller bam/sam with the same error and send it along it could be helpful.
It sounds like a premature termination of the bamfile, but it's hard to
tell for sure.

Yossi.

**Comment by yfarjoun** [comment]
closed due to lack of interest. if this is happening with a current version of picard, please reopen with output.
