### ISSUE TITLE
CollectInsertSizeMetrics: no output

### ISSUE THREAD

**Issue by Madelinehazel** [broadinstitute/picard#438]
Hello,

When I enter the following command:
java -jar picard.jar CollectInsertSizeMetrics I=../../mnt/data/A10898.bam O=A10898_insert_size.txt H=insert_size_histogram.pdf M=0.5

The program runs, and then I get this message at the end:
[Fri Feb 12 10:34:26 PST 2016] picard.analysis.CollectInsertSizeMetrics done. Elapsed time: 39.70 minutes.
Runtime.totalMemory()=1271398400
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation er
ror: ERROR: Record 922317609, Read name HS5_408:1:2204:5314:102757, MAPQ should be 0 for unmapped read.
        at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:441)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:644)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:629)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:599)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:545)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:519)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:129)
        at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:77)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)

There is not output called A10898_insert_size.txt or H=insert_size_histogram.pdf. I'm not sure what the issue is. Help would be appreciated!

Best, 
Madeline

**Comment by nh13** [comment]
See the line in the output: **ERROR: Record 922317609, Read name HS5_408:1:2204:5314:102757, MAPQ should be 0 for unmapped read.** 

The answer is in the FAQ: http://broadinstitute.github.io/picard/faq.html

**Comment by vdauwera** [comment]
Hi @Madelinehazel,

We prefer to keep github issues for development-related questions, and handle end-user questions in the GATK forum here: http://gatkforums.broadinstitute.org/gatk

If you have any follow-up questions to this or other Picard tools, we'll be happy to help you there.
