### ISSUE TITLE
CollectRrbsMetrics switches tables for DetailMetrics and SummaryMetrics

### ISSUE THREAD

**Issue by dekling** [broadinstitute/picard#473]
Detailed metrics are produced in the SummaryMetrics file and the summary metrics are written in the DetailedMetrics file.  Will add a script and files shortly.

**Comment by dekling** [comment]
When running on the server, throws the following errors:
Exception in thread "main" htsjdk.samtools.SAMException: Unexpected exception executing [Rscript /tmp/dkling/script8905532640752342085.R /humgen/gsa-scr1/dkling/test_data/rrbsmetrics1.rrbs_detail_metrics /humgen/gsa-scr1/dkling/test_data/rrbsmetrics1.rrbs_summary_metrics /humgen/gsa-scr1/dkling/test_data/rrbsmetrics1.rrbs_qc.pdf]
	at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:111)
	at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:87)
	at picard.util.RExecutor.executeFromFile(RExecutor.java:78)
	at picard.util.RExecutor.executeFromClasspath(RExecutor.java:59)
	at picard.analysis.CollectRrbsMetrics.doWork(CollectRrbsMetrics.java:188)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
Caused by: java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:102)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1023)
	... 10 more

**Comment by dekling** [comment]
Here is the command line and file paths: 
java -jar picard.jar CollectRrbsMetrics I=/humgen/gsa-scr1/dkling/test_data/filtered_san_aln_RG.bam METRICS_FILE_PREFIX=/humgen/gsa-scr1/dkling/test_data/rrbsmetrics1 R=/humgen/gsa-scr1/pub/bundle/2.8/b37/human_g1k_v37.fasta.gz

**Comment by vdauwera** [comment]
The error in your second post is because you don't seem to have rscript set up in your user environment, FYI. I think you can fix that by loading a dotkit.

**Comment by dekling** [comment]
What is a dotkit and how do I get one?

**Comment by vdauwera** [comment]
http://iwww.broadinstitute.org/bits/dotkit

**Comment by dekling** [comment]
I was misinterpreting this.
