### ISSUE TITLE
Bam -> Cram fails with NPE

### ISSUE THREAD

**Issue by iromeo** [broadinstitute/picard#492]
Hi, I'm using picard-tools 2.1.2. According to the readme it supports CRAM format and *SamFormatConverter* is expected to support bam->cram conversion (see https://github.com/broadinstitute/picard/blob/9a6e054c4ebc5ebed20bffcf9bb3a7160973cf2a/src/tests/java/picard/sam/SamFileConverterTest.java). Unfortunately it doesn't work, more over 'CRAM' isn't mentioned anywhere in `java -jar picard.jar -h`
```
java -jar /mnt/stripe/tools/picard-tools/picard.jar SamFormatConverter I=./GSM1973810.bam O=tm
p3.cram
[Mon Mar 28 15:23:10 MSK 2016] picard.sam.SamFormatConverter INPUT=./GSM1973810.bam OUTPUT=tmp3.cram    VERBOSITY=INFO QUIET=false VA
LIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRET
S=client_secrets.json
[Mon Mar 28 15:23:10 MSK 2016] Executing as user@unit-503.labs.intellij.net on Linux 2.6.32-573.8.1.el6.x86_64 amd64; Java HotSpot(TM
) 64-Bit Server VM 1.8.0-b132; Picard version: 2.1.1(6a5237c0f295ddce209ee3a3a5b83a3779408b1b_1457101272) IntelDeflater
[Mon Mar 28 15:23:10 MSK 2016] picard.sam.SamFormatConverter done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2160066560
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NullPointerException
        at htsjdk.samtools.cram.build.Sam2CramRecordFactory.addSubstitutionsAndMaskedBases(Sam2CramRecordFactory.java:306)
        at htsjdk.samtools.cram.build.Sam2CramRecordFactory.createVariations(Sam2CramRecordFactory.java:250)
        at htsjdk.samtools.cram.build.Sam2CramRecordFactory.checkedCreateVariations(Sam2CramRecordFactory.java:195)
        at htsjdk.samtools.cram.build.Sam2CramRecordFactory.createCramRecord(Sam2CramRecordFactory.java:150)
        at htsjdk.samtools.CRAMContainerStreamWriter.flushContainer(CRAMContainerStreamWriter.java:326)
        at htsjdk.samtools.CRAMContainerStreamWriter.writeAlignment(CRAMContainerStreamWriter.java:97)
        at htsjdk.samtools.CRAMFileWriter.writeAlignment(CRAMFileWriter.java:113)
        at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:190)
        at picard.sam.SamFormatConverter.doWork(SamFormatConverter.java:84)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
```

**Comment by cmnbroad** [comment]
Cram files are reference-compressed so you need a reference sequence file argument. Try adding R=your_ref.fasta.

**Comment by iromeo** [comment]
@cmnbroad Thanks, it helps, but no info about such option in:
```
java -jar picard-tools/picard.jar SamFormatConverter -h
USAGE: SamFormatConverter [options]

Documentation: http://broadinstitute.github.io/picard/command-line-overview.html#SamFormatConverter

Convert a BAM file to a SAM file, or SAM to BAM.
Input and output formats are determined by file extension.
Version: 2.1.1(6a5237c0f295ddce209ee3a3a5b83a3779408b1b_1457101272)


Options:

--help
-h                            Displays options specific to this tool.

--stdhelp
-H                            Displays options specific to this tool AND options common to all Picard command line
                              tools.

--version                     Displays program version.

INPUT=File
I=File                        The BAM or SAM file to parse.  Required.

OUTPUT=File
O=File                        The BAM or SAM output file.   Required.
```

**Comment by yfarjoun** [comment]
try with -H

**Comment by iromeo** [comment]
> try with -H

@yfarjoun  thanks, it works
