### ISSUE TITLE
SamToFastq should provide an informative error when RG info is missing

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/picard#496]
As reported in the [GATK forum](http://gatkforums.broadinstitute.org/gatk/discussion/7321/java-lang-nullpointerexception-for-picard-samtofastq-output-per-rg-t-on-bam-without-read-groups)

When running SamToFastq with OUTPUT_PER_RG=T on a bam file without read group information, you get the following error:

```
Exception in thread "main" java.lang.NullPointerException
        at net.sf.picard.sam.SamToFastq.doWork(SamToFastq.java:148)
        at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:177)
        at net.sf.picard.sam.SamToFastq.main(SamToFastq.java:119)
```

This should be handled to return a more informative error message to the user. 

I would guess this should be handled around line 166 of https://github.com/broadinstitute/picard/blob/master/src/java/picard/sam/SamToFastq.java

**Comment by kasont** [comment]
@vdauwera Do you have an example bam, to reproduce this issue?

**Comment by vdauwera** [comment]
@kasont Here's one (zipped sam)
[H0164.2.sam.zip](https://github.com/broadinstitute/picard/files/358538/H0164.2.sam.zip)

````
wmd16-c9e:Desktop vdauwera$ java -jar $PICARD RevertSam I=H0164.2.sam OUTPUT_BY_READGROUP=true O=.
[Mon Jul 11 23:48:21 EDT 2016] picard.sam.RevertSam INPUT=H0164.2.sam OUTPUT=. OUTPUT_BY_READGROUP=true    SORT_ORDER=queryname RESTORE_ORIGINAL_QUALITIES=true REMOVE_DUPLICATE_INFORMATION=true REMOVE_ALIGNMENT_INFORMATION=true ATTRIBUTE_TO_CLEAR=[NM, UQ, PG, MD, MQ, SA, MC, AS] SANITIZE=false MAX_DISCARD_FRACTION=0.01 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Mon Jul 11 23:48:21 EDT 2016] Executing as vdauwera@wmd16-c9e on Mac OS X 10.10.5 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17; Picard version: 2.4.1(90fcb4fd0d760bf12e158dda68d2eec7e520d43c_1466596970) JdkDeflater
[Mon Jul 11 23:48:21 EDT 2016] picard.sam.RevertSam done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=257425408
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NullPointerException
	at picard.sam.RevertSam$RevertSamWriter.addAlignment(RevertSam.java:567)
	at picard.sam.RevertSam.doWork(RevertSam.java:243)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
````

**Comment by vdauwera** [comment]
@kasont Were you able to address this?

**Comment by ronlevine** [comment]
Closed via #748.

**Comment by chandrans** [comment]
Should someone let the user know? I am not sure where this fix is/if Picard has nightlies like GATK?

**Comment by vdauwera** [comment]
Yep, done. Picard doesn't have nightlies but the source code is public so they can build from source themselves.
