### ISSUE TITLE
UpdateVcfSequenceDictionary should handle stdin and stdout gracefully

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#507]
Currently it will blow up trying to build the writer:
```
Exception in thread "main" java.lang.IllegalArgumentException: Must specify file or stream output type.
    at htsjdk.variant.variantcontext.writer.VariantContextWriterBuilder.build(VariantContextWriterBuilder.java:407)
    at picard.vcf.UpdateVcfSequenceDictionary.doWork(UpdateVcfSequenceDictionary.java:92)
    at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
    at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
    at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
```

**Comment by ronlevine** [comment]
@yfarjoun Can you either give me picard write permission or assign me to this task? It would be much easier if I had write permission, I'd prefer to work in a branch rather than a fork.

**Comment by yfarjoun** [comment]
I'm pretty sure you have right access.

**Comment by ronlevine** [comment]
@yfarjoun I do not have write access. I tried pushing my branch and got the following:
```
remote: Permission to broadinstitute/picard.git denied to ronlevine.
fatal: unable to access 'https://github.com/broadinstitute/picard.git/': The requested URL returned error: 403
```

**Comment by ronlevine** [comment]
@nh13 I can see a use case for stdout but is there one for stdin?

**Comment by nh13** [comment]
Yes, streaming support would be desirable as I don't see any reason it would need to read the input twice.

**Comment by yfarjoun** [comment]
are you using the ssh link?

**Comment by ronlevine** [comment]
I'm not sure what you are referring to by the "ssh link".

I cloned picard
```
https://github.com/broadinstitute/picard.git
```

```
MITAdmins-Air:picard ronlevine$ git remote -v
origin	https://github.com/broadinstitute/picard.git (fetch)
origin	https://github.com/broadinstitute/picard.git (push)
stable	git@github.com:broadinstitute/gsa-stable.git (fetch)
stable	git@github.com:broadinstitute/gsa-stable.git (push)
unstable	git@github.com:broadinstitute/gsa-unstable.git (fetch)
unstable	git@github.com:broadinstitute/gsa-unstable.git (push)
```

**Comment by yfarjoun** [comment]
use the other link to clone: git@github.com:broadinstitute/picard.git

**Comment by ronlevine** [comment]
Cloned `git@github.com:broadinstitute/picard.git`, created a branch, made changes then tried to push them, but was denied

```
MITAdmins-Air:picard ronlevine$ git push -u origin rhl_uvsd_stdin_stdout_507
Enter passphrase for key '/Users/ronlevine/.ssh/id_rsa': 
ERROR: Permission to broadinstitute/picard.git denied to ronlevine.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by yfarjoun** [comment]
try now...

**Comment by ronlevine** [comment]
@yfarjoun  👍

**Comment by ronlevine** [comment]
@nh13 Can you give me an explicit example of a command line using `stdin`? I assume the following is the `stout` case:
`java -jar ./build/libs/picard.jar UpdateVcfSequenceDictionary I=input.vcf SD=sequencDictionay.vcf O=/dev/stdout`

**Comment by nh13** [comment]
Should be simple to make one up using cat or the like.

**Comment by yfarjoun** [comment]
Testing streaming can be tricky when you aren't actually building a
command-line.

You could look at my recent test of MargeBamAlignment as an example of how
to stream into a test.

let me know if that doesn't help.

**Comment by ronlevine** [comment]
@yfarjoun I grabbed the following lines of code and substituted `InputVCFfIle.vcf`
```
        FileInputStream stream = new FileInputStream(InputVCFfIle.vcf);
        final Field fdField = FileDescriptor.class.getDeclaredField("fd");
        fdField.setAccessible(true);
        final File inputStream = new File("/dev/fd/" + fdField.getInt(stream.getFD()));
```
`VCFFileReader` successfully reads the header during it's construction but it's  iterator is unable to read the rest of the file.

**Comment by yfarjoun** [comment]
That probably means that it will not work in streaming..is the file being
opened again (for extracting the dictionary for example)?

That's the part that needs fixing.

**Comment by ronlevine** [comment]
Exactly. HTSJDK's `TribbleIndexedFeatureReader.readHeader`, which is used by the `VCFFileReader ` ctor closes it. For streaming, it can not be closed then opened again. It's done that same way for the sequence dictionary. And, there is a file type check for the sequence dictionary, which will fail for this approach since the file name would be /dev/fd/*number*.

**Comment by yfarjoun** [comment]
yeah...it might be harder to fix...there are several issues. fix what you
can, and leave the rest in a new issue, perhaps.

**Comment by ronlevine** [comment]
That's the plan. Handling stdout is trivial. I think the stdout issues such as having the option to not close the stream after reading the header and determining the file type by examining the first line  of the file instead of by file extension should be done in HTSJDK.

**Comment by yfarjoun** [comment]
I agree.

**Comment by ronlevine** [comment]
There is an existing HTSJDK issue, [Add InputStream support to VCFFileReader](https://github.com/samtools/htsjdk/issues/723).

**Comment by sooheelee** [comment]
Listen, I may be off base here but can I ask why we don't have a separate centralizing I/O actor, like BWA does? Given the larger file sizes now, would this type of feature make sense? If not, why not?

**Comment by ronlevine** [comment]
Does it handle input streams? It would have to decode that stream type on the fly. https://github.com/samtools/htsjdk/pull/837 is handling the input stream. Can you point me to the BWA I/O actor?

**Comment by sooheelee** [comment]
Someplace in <https://github.com/lh3/bwa>. Sorry I can't be more specific.

**Comment by mjhipp** [comment]
Adding a comment that HTSJDK has tried to add this functionality (https://github.com/samtools/htsjdk/pull/1245) but there are issues with the reader that still persist (#1776)
