### ISSUE TITLE
UnsupportedOperationException from LiftoverVcf

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/picard#598]
I tried to run a basic LiftoverVcf command and got this exception:

Exception in thread "main" java.lang.UnsupportedOperationException
at java.util.Collections$UnmodifiableMap.put(Collections.java:1457)
at htsjdk.variant.variantcontext.VariantContextBuilder.attribute(VariantContextBuilder.java:212)
at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:249)
at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)

I put in a PR to HTSJDK to fix the issue; however, I'm opening this to make you guys aware of the problem, and also to see if either a) you want to do a workaround, or b) the HTSJDK version could get updated whenever they accept the PR.

Essentially picard's code is calling VariantContextBuilder.attributes() in LiftoverVcf line 246 and passing an modifiable map.  The next lines then call VariantContextBuilder.attribute(), which tries to modify this map.  I put in a pull request to HTSJDK to change VariantContextBuilder to prevent this:

https://github.com/samtools/htsjdk/pull/661

I dont know what the timing of HTSJDK updates are, but it would be easy to work around it here too w/ something like:

builder.attributes(new HashMap<>(ctx.getAttributes()));

Thanks.

**Comment by vdauwera** [comment]
@bbimber It looks like part of your PR to htsjdk was redundant with something already in there. In light of that, and considering Picard has already taken an updated htsjdk since then, does this issue still apply or can it be closed?

**Comment by bbimber** [comment]
yes, that's fine.  thanks for the followup.
