### ISSUE TITLE
CollectIlluminaLaneMetrics does not handle read structures with molecular indexes

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#688]
The read structure `75T8B75T` works but `8M67B75T` does not.  The error I get is:
```
Exception in thread "main" picard.PicardException: Don't have both phasing and prephasing values for tile
	at picard.illumina.parser.TileMetricsUtil.getTilePhasingValues(TileMetricsUtil.java:116)
	at picard.illumina.parser.TileMetricsUtil.parseTileMetrics(TileMetricsUtil.java:95)
	at picard.illumina.CollectIlluminaLaneMetrics$IlluminaLaneMetricsCollector.readLaneTiles(CollectIlluminaLaneMetrics.java:110)
	at picard.illumina.CollectIlluminaLaneMetrics$IlluminaLaneMetricsCollector.collectLaneMetrics(CollectIlluminaLaneMetrics.java:123)
	at picard.illumina.CollectIlluminaLaneMetrics.doWork(CollectIlluminaLaneMetrics.java:91)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:208)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
```

**Comment by nh13** [comment]
@yfarjoun assigning this to you since I want to ask if you have seen this in your production environment, given you demultiplex and collect metrics using Picard.

**Comment by nh13** [comment]
This also doesn't work with skips: `1S74T8B75T`

**Comment by yfarjoun** [comment]
We are aware that it doesn't work with molecular barcodes, but we do not
have the priority to fix it...

Would you like to contribute a fix?

Y

**Comment by nh13** [comment]
An obvious hack is to convert the skip and molecular barcode segments to a template segment (hint: that's my current workaround).  I may contribute a fix if it becomes a major issue going forward for me (it's not).  It's good to have this documented as a bug so that if other folks have the same problem they know they aren't the only ones.

**Comment by vdauwera** [comment]
@nh13 @yfarjoun Should this have been closed when #697 went in?

**Comment by yfarjoun** [comment]
not quite. this workaround doesn't resolve the underlying fundamental
problem...

**Comment by nh13** [comment]
it doesn't handle skips and barcodes when present in both the index and in-line in the reads
