### ISSUE TITLE
FastqToSam: sporadic error 'Input paired fastq files must be the same length'

### ISSUE THREAD

**Issue by dinvlad** [broadinstitute/picard#711]
Hi team,

I'm running FastqToSam from Picard 2.8.0, where the files are read from/written to named pipes:
```
FastqToSam FASTQ=/tmp/tmp.LBalFH FASTQ2=/tmp/tmp.dNceeH O=/tmp/tmp.iPganf SM=sample
```
Prior to that, I open each input pipe in a background process using a while loop in a Bash script (otherwise, in the beginning Picard seems to read some information and then re-open them, leading to termination of inputs that are being piped). I also open the output pipe as a regular background process (without a loop).

Around 80% of the time this technique works correctly. But other times it fails, even if run with the same exact inputs, right before the second part of the job (when it's supposed to combine temporary files into the output).
```
INFO    2016-12-14 05:43:33     FastqToSam      Processed    35,000,000 records.  Elapsed time: 00:02:14s.  Time for last 1,000,000:    3s.  Last read position: */*
[Wed Dec 14 05:43:35 GMT 2016] picard.sam.FastqToSam done. Elapsed time: 2.31 minutes.
Runtime.totalMemory()=2884108288
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: Input paired fastq files must be the same length
        at picard.sam.FastqToSam.doPaired(FastqToSam.java:354)
        at picard.sam.FastqToSam.makeItSo(FastqToSam.java:309)
        at picard.sam.FastqToSam.doWork(FastqToSam.java:282)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:208)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
```

I wonder if this issue is due to a race condition in how Picard and/or Samtools access the input files, and if it's related to #149.

Is there perhaps a workaround that does not require random access to these files?

Thank you

**Comment by dinvlad** [comment]
It seems like the issue was due to the fact that there was only one writer for each input pipe, so whenever the writer (a remote copy process in my case) finished its output, the pipe would automatically close and the next `FastqReader.readline()` would return null, even though there might still be some buffered input left. I had to create a dummy `exec 3>$pipe &` to circumvent that.

As long as we are able to keep the files open, Picard code seems to be robust in that it reads one record at a time for each input, until an actual EOF is reached.
