### ISSUE TITLE
FilterSamReads: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by YingYa** [broadinstitute/picard#719]
How to estimate the memory use (-Xmx?G) when using FilterSamReads? I always get the errors:

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.regex.Pattern$Start.<init>(Pattern.java:3450)
        at java.util.regex.Pattern.compile(Pattern.java:1716)
        at java.util.regex.Pattern.<init>(Pattern.java:1351)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at java.lang.String.split(String.java:2380)
        at java.lang.String.split(String.java:2422)
        at htsjdk.samtools.filter.ReadNameFilter.<init>(ReadNameFilter.java:58)
        at picard.sam.FilterSamReads.doWork(FilterSamReads.java:233)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:208)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)

**Comment by vdauwera** [comment]
Please post usage questions in the GATK forum as instructed in the "getting started" doc. Github Issues are reserved for discussions about the code and confirmed bug reports. Thank you.
