### ISSUE TITLE
CollectRnaSeqMetrics Null Pointer Exception when RIBOSOMAL_INTERVALS are not given 

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#728]
If the`RIBOSOMAL_INTERVALS` option is not given and `RRNA_FRAGMENT_PERCENTAGE=0`, then [this if statement is always true](https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java#L168).  This leads to the following NPE:

```
Exception in thread "main" java.lang.NullPointerException
	at picard.analysis.directed.RnaSeqMetricsCollector$PerUnitRnaSeqMetricsCollector.acceptRecord(RnaSeqMetricsCollector.java:171)
	at picard.analysis.directed.RnaSeqMetricsCollector$PerUnitRnaSeqMetricsCollector.acceptRecord(RnaSeqMetricsCollector.java:98)
	at picard.metrics.MultiLevelCollector$AllReadsDistributor.acceptRecord(MultiLevelCollector.java:192)
	at picard.metrics.MultiLevelCollector.acceptRecord(MultiLevelCollector.java:315)
	at picard.analysis.CollectRnaSeqMetrics.acceptRead(CollectRnaSeqMetrics.java:164)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:138)
	at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:77)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
```

A simple fix would be to not allow `RRNA_FRAGMENT_PERCENTAGE=0` if `RIBOSOMAL_INTERVALS=null`.

**Comment by ronlevine** [comment]
Do you have the input files? I was unable to reproduce the NP. The code is interpreting input SAM file read as a null.
