### ISSUE TITLE
GenotypeConcordance is not aware of spanning deletions

### ISSUE THREAD

**Issue by fleharty** [broadinstitute/picard#742]
## Bug Report

This is a bug report.
GenotypeConcordance does not properly handle the star allele which represents a spanning deletion.

### Affected tool(s)

GenotypeConcordance

### Affected version(s)

- [x] Latest public release version
The star allele is a relatively new invention, so all versions of GenotypeConcordance are affected.

### Description 

If a star allele is in the callset VCF, then it is likely that the following exception will be thrown.

java -jar $PICARD GenotypeConcordance TRUTH_VCF=exampleTruth.vcf CALL_VCF=exampleCallset.vcf  TRUTH_SAMPLE=/dev/stdin CALL_SAMPLE=CHMI_CHMI3_WGS2 O=genotypeConcodranceLCRchrX OUTPUT_VCF=true
[Wed Feb 01 15:26:08 EST 2017] picard.vcf.GenotypeConcordance TRUTH_VCF=exampleTruth.vcf CALL_VCF=exampleCallset.vcf OUTPUT=genotypeConcodranceLCRchrX OUTPUT_VCF=true TRUTH_SAMPLE=/dev/stdin CALL_SAMPLE=CHMI_CHMI3_WGS2    INTERSECT_INTERVALS=true MIN_GQ=0 MIN_DP=0 OUTPUT_ALL_ROWS=false USE_VCF_INDEX=false MISSING_SITES_HOM_REF=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Feb 01 15:26:08 EST 2017] Executing as fleharty@gsa4.broadinstitute.org on Linux 2.6.18-371.el5 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0-b132; Picard version: 00f21fa
INFO	2017-02-01 15:26:10	GenotypeConcordance	Starting iteration over variants.
[Wed Feb 01 15:26:10 EST 2017] picard.vcf.GenotypeConcordance done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=2182086656
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Unexpected base in allele bases '*ATAT'
	at htsjdk.variant.variantcontext.Allele.<init>(Allele.java:162)
	at htsjdk.variant.variantcontext.Allele.create(Allele.java:234)
	at htsjdk.variant.variantcontext.Allele.create(Allele.java:355)
	at picard.vcf.GenotypeConcordance$Alleles.asList(GenotypeConcordance.java:641)
	at picard.vcf.GenotypeConcordance.writeVcfTuple(GenotypeConcordance.java:431)
	at picard.vcf.GenotypeConcordance.lambda$doWork$39(GenotypeConcordance.java:333)
	at picard.vcf.GenotypeConcordance$$Lambda$8/2129442232.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at picard.vcf.GenotypeConcordance.doWork(GenotypeConcordance.java:333)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at edu.mit.broad.picard.cmdline.PicardPrivateCommandLine.main(PicardPrivateCommandLine.java:24)

#### Steps to reproduce

Running the following command on the contents of the zipped file provided here will reproduce the error.

[example.zip](https://github.com/broadinstitute/picard/files/746061/example.zip)

java -jar $PICARD GenotypeConcordance TRUTH_VCF=exampleTruth.vcf CALL_VCF=exampleCallset.vcf  TRUTH_SAMPLE=/dev/stdin CALL_SAMPLE=CHMI_CHMI3_WGS2 O=genotypeConcodranceLCRchrX OUTPUT_VCF=true

#### Expected behavior

GenotypeConcordance should handle spanning deletions without throwing an exception.

#### Actual behavior

Throws an exception since the tool isn't aware of how to correctly process the "*" allele.

**Comment by ronlevine** [comment]
The callset VCF with the `*` allele does not have the upstream deletion. so it's impossible to interpret it. So, it should be ignored.

**Comment by fleharty** [comment]
This issue appears to have been done for quite some time, closing.
