### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by Akado2009** [broadinstitute/picard#750]
Greetings!

### Affected tool(s)
Picard

### Affected version(s)
1.123

### Description 
This errors occurs when I execute picard on small bam files using machine with 2Gb RAM. This doesnt happen when I use 4Gb instead.
```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at htsjdk.samtools.BinaryTagCodec.readTags(BinaryTagCodec.java:282)
	at htsjdk.samtools.BAMRecord.decodeAttributes(BAMRecord.java:308)
	at htsjdk.samtools.BAMRecord.getAttribute(BAMRecord.java:288)
	at htsjdk.samtools.SAMRecord.isValid(SAMRecord.java:1594)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:642)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:628)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:598)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:514)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:488)
	at picard.sam.SortSam.doWork(SortSam.java:74)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:185)
	at picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:125)
	at picard.sam.SortSam.main(SortSam.java:61)
```

#### Steps to reproduce
Here is the command:
```
picard.sam.SortSam INPUT=/output/polysolver_test1/nv.complete.chr6region.R0k6.bam OUTPUT=/output/polysolver_test1/nv.complete.chr6region.R0k6.csorted.bam SORT_ORDER=coordinate TMP_DIR=[/tmp]    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
```

Think it works on every bam file, since our bam is 15 Mb.

King regards, akado2009.

**Comment by vdauwera** [comment]
That's an old version, please try again with the latest. If the problem persists, please post in the GATK forum here: http://gatkforums.broadinstitute.org/gatk

The github Issues are for developer questions and problems only. Thank you.

**Comment by huguesfontenelle** [comment]
Newer versions do not necessarily "fix" this problem.
However, capping the memory for the java program will. Use `-Xmx4g` (or some other limit).
Eg.:
```
picard SamToFastq \
  -Xmx4g \
  I=input.bam \
  F=out_unmapped_R1.fastq \
  F2=out_unmapped_R2.fastq \
  VALIDATION_STRINGENCY=SILENT
```
