### ISSUE TITLE
GenotypeConcordance dies if both samples are no call

### ISSUE THREAD

**Issue by apregier** [broadinstitute/picard#768]
### Affected tool(s)
`GenotypeConcordance OUTPUT_VCF=true`

### Affected version(s)
- [x] Latest public release version [2.9.0-1-gf5b9f50-SNAPSHOT]

### Description 
At first I thought I was running into the spanning deletion bug, because the first time I hit it was at a site with a * allele.  But, even after I removed all sites with those alleles, I got the following stacktrace:
```
Exception in thread "main" java.lang.IllegalArgumentException: BUG: Cannot add a no call allele to a variant context [TA*, .] this=[VC Unknown @ chr1:53707-53708 Q584.04 of type=INDEL alleles=[TA*, .] attr={CONC_ST=[EMPTY]} GT=[[call ./. DP 1 AD 1,0],[truth ./. DP 1 AD 1,0]]
        at htsjdk.variant.variantcontext.VariantContext.validateAlleles(VariantContext.java:1344)
        at htsjdk.variant.variantcontext.VariantContext.validate(VariantContext.java:1297)
        at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:401)
        at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:494)
        at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:488)
        at picard.vcf.GenotypeConcordance.writeVcfTuple(GenotypeConcordance.java:454)
        at picard.vcf.GenotypeConcordance.lambda$doWork$0(GenotypeConcordance.java:333)
        at java.util.Optional.ifPresent(Optional.java:159)
        at picard.vcf.GenotypeConcordance.doWork(GenotypeConcordance.java:333)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
```
This only seems to be an issue when writing an output vcf - I was able to get the metrics files when I ran with `OUTPUT_VCF=false`.

#### Steps to reproduce
It should reproduce if you run GenotypeConcordance OUTPUT_VCF=true for any two vcfs where a site has a './.' genotype for both the truth and call samples.

#### Expected behavior
I guess the vcf line should be output in the vcf with CONC_ST matching whatever is counted in the summary metrics.

#### Actual behavior
Command dies with a stack trace

**Comment by meganshand** [comment]
This should be satisfied by #785 which is now merged into master.
