### ISSUE TITLE
ReorderSam error 

### ISSUE THREAD

**Issue by syahr** [broadinstitute/picard#776]
hello picard team,

I'm having an issue when I tried to run ReorderSam tool in picard-2.9.0. 

The syntax:
## java -jar ~/picard-2.9.0/picard.jar ReorderSam I=marked_Duplicates.bam O=reorder_marked_Duplicates.bam R=~/Reference/GRCh38.p7.genome/GRCh38.p7.genome.nochr.fa CREATE_INDEX=TRUE

The output:
picard.sam.ReorderSam done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=1519386624
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: New reference sequence does not contain a matching contig for MT
	at picard.sam.ReorderSam.buildSequenceDictionaryMap(ReorderSam.java:229)
	at picard.sam.ReorderSam.doWork(ReorderSam.java:112)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)

and the end result is nothing has change. There is no new ordered file created. 

What should I do? your helps is kindly appreciated. Thank you.

**Comment by sooheelee** [comment]
You can find answers to Picard tool error in the [GATK forum](http://gatkforums.broadinstitute.org/gatk). Please post your Picard usage questions to the GATK forum going forward. 

I believe the answer to your question can be had within the discussion for [this forum post](http://gatkforums.broadinstitute.org/gatk/discussion/1328/errors-about-contigs-in-bam-or-vcf-files-not-being-properly-ordered-or-sorted). Specifically, for mismatching `@SQ` lines in your file header versus the reference dictionary, you can use the `-U ALLOW_SEQ_DICT_INCOMPATIBILITY` option.
