### ISSUE TITLE
Clarify in documentation that ScatterIntervalsByNs requires index and dictionary

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#802]
# Documentation request
### Tool(s) involved
ScatterIntervalsByNs

### Description 
Tool requires index and dictionary but this is not mentioned in the tool documentation nor the code notes. This should be clarified in the documentation as current tool errors are uninformative. From <https://github.com/broadinstitute/dsde-docs/issues/2000>, here are the errors:

**Lacking index and lacking dictionary**
```
Exception in thread "main" java.lang.NullPointerException
	at picard.util.ScatterIntervalsByNs.segregateReference(ScatterIntervalsByNs.java:141)
	at picard.util.ScatterIntervalsByNs.doWork(ScatterIntervalsByNs.java:107)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
```

**Lacking index but dictionary present**
```
Exception in thread "main" java.lang.UnsupportedOperationException
	at htsjdk.samtools.reference.AbstractFastaSequenceFile.getSequence(AbstractFastaSequenceFile.java:137)
	at htsjdk.samtools.reference.FastaSequenceFile.getSequence(FastaSequenceFile.java:42)
	at picard.util.ScatterIntervalsByNs.segregateReference(ScatterIntervalsByNs.java:142)
	at picard.util.ScatterIntervalsByNs.doWork(ScatterIntervalsByNs.java:107)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
```

**With both index and dictionary present**
No error message

**Comment by sooheelee** [comment]
Let me know if you want me to update the doc.

**Comment by eitanbanks** [comment]
Is this still an issue?  I can have my summer intern take this.

**Comment by sooheelee** [comment]
That would be great @eitanbanks.

**Comment by ben10wald** [comment]
Hi @sooheelee I have addressed this issue in the following PR:
https://github.com/broadinstitute/picard/pull/881
I have also added in proper checks that the dict and Index files exist.
I will merge once tests pass after my rebase, at which point you can close this ticket.

**Comment by sooheelee** [comment]
Thanks Ben. Looks great.
