### ISSUE TITLE
IlluminaBasecallsToSam Fails, trying to figure out why

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#889]
A forum user question for @jacarey on IlluminaBasecallsToSam. The thread is longer than this single post so please click on the link for the full thread. Any insight is much appreciated.

---

Hi

I have same issue when I use illuminaBaseCalls toFastq. 
the command is: 
java -Xmx10g -jar ~/tools/picard-tools-2.1.0/picard.jar IlluminaBasecallsToFastq BASECALLS_DIR=$run_folder/Datantensities/BaseCalls/ LANE=1 RUN_BARCODE=$run_barcode FLOWCELL_BARCODE=$flowcell MACHINE_NAME=$machine READ_STRUCTURE=300T8B8B300T INCLUDE_NON_PF_READS=false COMPRESS_OUTPUTS=true ADAPTERS_TO_CHECK=null NUM_PROCESSORS=4 TMP_DIR=../tmp MULTIPLEX_PARAMS=./nextera_barcodes_demultiplex.txt 

And error:
INFO	2017-07-24 11:57:11	IlluminaBasecallsToFastq	READ STRUCTURE IS 300T8B8B300T
Exception in thread "pool-1-thread-4" ERROR	2017-07-24 11:57:27	IlluminaBasecallsConverter	Failure encountered in worker thread; attempting to shut down remaining worker threads and terminate ...
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at picard.illumina.IlluminaBasecallsConverter$TileReadAggregator.awaitWorkComplete(IlluminaBasecallsConverter.java:711)
	at picard.illumina.IlluminaBasecallsConverter.doTileProcessing(IlluminaBasecallsConverter.java:320)
	at picard.illumina.IlluminaBasecallsToFastq.doWork(IlluminaBasecallsToFastq.java:185)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
picard.PicardException: Read records with barcode null, but this barcode was not expected.  (Is it referenced in the parameters file?)
	at picard.illumina.IlluminaBasecallsConverter$TileProcessingRecord.addRecord(IlluminaBasecallsConverter.java:445)
	at picard.illumina.IlluminaBasecallsConverter$TileReader.process(IlluminaBasecallsConverter.java:562)
	at picard.illumina.IlluminaBasecallsConverter$TileReadAggregator$2.run(IlluminaBasecallsConverter.java:659)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Any thoughts on this?

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/40799#Comment_40799

**Comment by sooheelee** [comment]
Let us know if you need test data from the user.

**Comment by ktibbett** [comment]
@sooheelee, the error message  -- " Read records with barcode null, but this barcode was not expected. (Is it referenced in the parameters file?)" -- suggests that perhaps the run did not have an index on the sequencer but that one was specified in nextera_barcodes_demultiplex.txt.  If it was an unindexed run, the headers BARCODE_1 or BARCODE_2 should not appear in the parameters file.

**Comment by ktibbett** [comment]
If that's not the case, then the next step is for the user to run CheckIlluminaDirectory on the run folder.

**Comment by sooheelee** [comment]
Thanks @ktibbett. I will convey this to the user.
