### ISSUE TITLE
Requested array size exceeds VM limit when using CretaeSequenceDictionary

### ISSUE THREAD

**Issue by Confurious** [broadinstitute/picard#920]
### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
CreateSequenceDictionary

### Affected version(s)
Picard version: 2.8.0-SNAPSHOT

### Description 
[Fri Sep 01 09:42:36 PDT 2017] picard.sam.CreateSequenceDictionary REFERENCE=topplants.fasta OUTPUT=topplants.dict MAX_RECORDS_IN_RAM=500000000    TRUNCATE_NAMES_AT_WHITESPACE=true NUM_SEQUENCES=2147483647 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Fri Sep 01 09:42:36 PDT 2017] Executing as xxxx@sxxxxxl on Linux 2.6.32-696.3.2.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_66-b17; Picard version: 2.8.0-SNAPSHOT
[Fri Sep 01 09:57:54 PDT 2017] picard.sam.CreateSequenceDictionary done. Elapsed time: 15.30 minutes.
Runtime.totalMemory()=32698269696
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:569)
	at java.lang.StringBuffer.append(StringBuffer.java:369)
	at java.io.StringWriter.write(StringWriter.java:94)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
	at java.io.BufferedWriter.write(BufferedWriter.java:230)
	at java.io.Writer.write(Writer.java:157)
	at java.io.Writer.append(Writer.java:227)
	at htsjdk.samtools.SAMTextHeaderCodec.println(SAMTextHeaderCodec.java:424)
	at htsjdk.samtools.SAMTextHeaderCodec.writeSQLine(SAMTextHeaderCodec.java:479)
	at htsjdk.samtools.SAMTextHeaderCodec.encode(SAMTextHeaderCodec.java:379)
	at htsjdk.samtools.SAMTextHeaderCodec.encode(SAMTextHeaderCodec.java:364)
	at htsjdk.samtools.SAMFileWriterImpl.setHeader(SAMFileWriterImpl.java:139)
	at htsjdk.samtools.SAMFileWriterFactory.makeSAMWriter(SAMFileWriterFactory.java:285)
	at picard.sam.CreateSequenceDictionary.doWork(CreateSequenceDictionary.java:140)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:208)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)

I tried to change the paramter MAX_RECORDS_IN_RAM to a larger value but it didn't work out. 
#### Steps to reproduce
Was using the picaard tool on a user generated fasta file around 30G of data, containing about 8 million entires (fragmented genomes)

#### Expected behavior
A prefix.dict should be generated

#### Actual behavior
Reported error as listed above

----

### Tool(s) involved
_Tool name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) involved
_Tool name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by yfarjoun** [comment]
This problem was reported in #432. it was fixed in PR #687 and merged Dec 9, 2016 which is just between 2.8.0 and 2.8.1. so your version "2.8.0-SNAPSHOT" is before the fix. 

Please update to a newer version of picard and report back if it still doesn't work.

**Comment by yfarjoun** [comment]
upon second read, it isn't the exact same problem...but the same PR should fix it as it will avoid holding all the records in memory....in the future if you get a `Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit` error in java, you want to consider increasing the amount of memory you give your VM (by using `java -Xmx16g ...` or similar), though in this case it wouldn't have helped.
