### ISSUE TITLE
Malformed CIGAR - bug report

### ISSUE THREAD

**Issue by yifanwang900801** [broadinstitute/picard#937]
### Affected tool(s)
UmiAwareMarkDuplicatesWithMateCigar and ValidateSamFile

### Affected version(s)
2.12.1

### Description 
Code: ../jdk1.8.0_73/bin/java -Xmx4g -jar ../picard/build/libs/picard.jar ValidateSamFile I=79225.sort.RG.MC.rmnoMC.withRX.rmaml.bam MODE=SUMMARY
Error:
ERROR	2017-09-24 17:41:36	ValidateSamFile	Malformed CIGAR string: 81M2D55M     RX:TGGCGTTACGTG

Code: ../jdk1.8.0_73/bin/java -Xmx4g -jar ../picard.jar UmiAwareMarkDuplicatesWithMateCigar MAX_EDIT_DISTANCE_TO_JOIN=1 UMI_METRICS_FILE=picard.umi.rmdup.txt ALLOW_MISSING_UMIS=False INPUT=79225.sort.RG.MC.rmnoMC.withRX.bam OUTPUT=79225.sort.RG.MC.rmnoMC.withRX.rmaml.bam METRICS_FILE=79225.umirmdup.metrics REMOVE_DUPLICATES=False ASSUME_SORTED=False
Error: [Sun Sep 24 17:46:08 EDT 2017] picard.sam.markduplicates.UmiAwareMarkDuplicatesWithMateCigar done. Elapsed time: 0.10 minutes.
Runtime.totalMemory()=1517813760
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Malformed CIGAR string: 94M41S     RX:GACCGGGGCGCG
	at htsjdk.samtools.TextCigarCodec.decode(TextCigarCodec.java:69)
	at htsjdk.samtools.SAMUtils.getMateCigar(SAMUtils.java:810)
	at htsjdk.samtools.SAMUtils.getMateCigar(SAMUtils.java:826)
	at htsjdk.samtools.SAMUtils.getMateUnclippedStart(SAMUtils.java:866)
	at htsjdk.samtools.SAMRecordDuplicateComparator.getMateCoordinate(SAMRecordDuplicateComparator.java:189)
	at htsjdk.samtools.SAMRecordDuplicateComparator.populateTransientAttributes(SAMRecordDuplicateComparator.java:85)
	at htsjdk.samtools.SAMRecordDuplicateComparator.compare(SAMRecordDuplicateComparator.java:225)
	at htsjdk.samtools.SAMRecordDuplicateComparator.compare(SAMRecordDuplicateComparator.java:43)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:219)
	at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:166)
	at htsjdk.samtools.DuplicateSetIterator.<init>(DuplicateSetIterator.java:99)
	at htsjdk.samtools.DuplicateSetIterator.<init>(DuplicateSetIterator.java:66)
	at picard.sam.markduplicates.UmiAwareMarkDuplicatesWithMateCigar.getDuplicateSetIterator(UmiAwareMarkDuplicatesWithMateCigar.java:107)
	at picard.sam.markduplicates.SimpleMarkDuplicatesWithMateCigar.doWork(SimpleMarkDuplicatesWithMateCigar.java:120)
	at picard.sam.markduplicates.UmiAwareMarkDuplicatesWithMateCigar.doWork(UmiAwareMarkDuplicatesWithMateCigar.java:96)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)

#### Steps to reproduce
I ran gatk print read before running any of the process above using the code below in order to remove the reads with malformed cigar. However, the same error still popped up.
Code:  ../java -Xmx4g -jar ../GenomeAnalysisTK-3.5/GenomeAnalysisTK.jar -T PrintReads -rf BadCigar -R ~/brainsom/technical/reference/hs37d5/hs37d5.fa -I 79225.sort.RG.MC.rmnoMC.withRX.bam -o 79225.sort.RG.MC.rmnoMC.withRX.rmaml.bam

#### Expected behavior
Output the bam file with UMI duplicates removed

#### Actual behavior
Malformed cigar error shows up

**Comment by yfarjoun** [comment]
Hi @yifanwang900801 ,

Could you also post the read that was causing this? the detailed report should tell you what the read-name is, and you should then be able to grep out the record from your bam. it will be much easier to understand what the problem is with the read in hand.

**Comment by yifanwang900801** [comment]
Thank you for the reply!
Here is the first read that ValidateSamFile had problem with: "K00135:151:HHVN2BBXX:1:1116:14864:17051:TACGTG:TGGCGT   163     1       10002   21      84M1D17M33S     =       10149   285     AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTACCCTAACCCTAACCCTCACCCCAACCCTCACCCCAAACCCCCAACCCTA  JJJJJJJJJJJJJJJJJJJJJJJFJFJJJJJJJFJ7AJJJJ<F-AAJFFJJJJ<JJJFJ7F-FJFF-AAAJ-<77-7A<-77FF-<7A-A-<<F-------)))7A-)7)-A-)7)))<-)----)--))A)--  MD:Z:84^A17     NM:i:1  AS:i:94 XS:i:102        MQ:i:21 MC:Z:81M2D55M     RX:TGGCGTTACGTG       RG:Z:79225"

Here is the second read that UmiAwareMarkDuplicatesWithMateCigar  had problem with: "K00135:151:HHVN2BBXX:1:2202:25956:13517:GGCGCG:GACCGG	163	1	10016	28	94M41S	=	10003	79	CCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTACCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCACCCCCCAACCCTCACCCCACCCCCCACACAACCCCTAACCC	JJJFFJJJJJJJJJJJJFJJJJJJJFJFJJFJJJJJJJJF<<AFFFA-<7J<-AAAF---77-7-77FF<F7AFF77-A7F7FAJF<<---FJ-)))7<))7-)7-))7<<)))-7---)A)7-7--7)-)-7--	MD:Z:47A4NM:i:1	AS:i:89	XS:i:85	MQ:i:28	MC:Z:29S92M14S     RX:GACCGGGGCGCG	RG:Z:79225"

I really appreciate your help!

**Comment by yfarjoun** [comment]
from the error message: 

>Exception in thread "main" java.lang.IllegalArgumentException: Malformed CIGAR string: 94M41S RX:GACCGGGGCGCG 

I understand that the separator between the MC and RX tag is a space rather than a tab. This is the problem with the bam File.
