### ISSUE TITLE
Jar file for picard 2.13.1 is incomplete

### ISSUE THREAD

**Issue by mdehollander** [broadinstitute/picard#944]
### Affected tool(s)
Picard

### Affected version(s)
- [x] Latest public release version [2.13.1]
- [ ] Latest development/master branch as of [date of test?]

### Description 
Filesize is much smaller than previous releases. Running it with `java -jar picard.jar` gives an error. @dianekaplan: Think something went wrong when uploading the minor release yesterday

#### Steps to reproduce
```$ java -jar picard.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/broadinstitute/barclay/argparser/CommandLineProgramProperties
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.broadinstitute.barclay.argparser.CommandLineProgramProperties
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more```

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

**Comment by dianekaplan** [comment]
Sorry for the inconvenience!  This is resolved now
