### ISSUE TITLE
Null value

### ISSUE THREAD

**Issue by xexpanderx** [broadinstitute/picard#997]
In documentation for picard version 2.14.1 you can "clear" default values and using "null". For example:

```
NEAR_DISTANCE=Integer         The maximum distance between a read and the nearest probe/bait/amplicon for the read to be
                              considered 'near probe' and included in percent selected.  Default value: 250. This option
                              **can be set to 'null'** to clear the default value.
```

However, when trying set to "null" for NEAR_DISTANCE parameter like this:

`java -Xmx7g -jar /sw/pipelines/bcbio-nextgen/1.0.5/anaconda/share/picard-2.14.1-0/picard.jar CollectHsMetrics USE_JDK_DEFLATER=true USE_JDK_INFLATER=true BAIT_INTERVALS=/projects/wp3/Reference_files/Manifest/Clinical_research_exome/S06588914_Covered_bait_hg19_consensus.txt TARGET_INTERVALS=/projects/wp3/Reference_files/Manifest/Clinical_research_exome/S06588914_Covered_bait_hg19_consensus.txt INPUT=NS12911-ready_2.bam NEAR_DISTANCE=null OUTPUT=test2_HsM.txt VALIDATION_STRINGENCY=LENIENT`

I get this error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Can not set int field picard.analysis.directed.CollectTargetedMetrics.NEAR_DISTANCE to null value
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(UnsafeIntegerFieldAccessorImpl.java:80)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.broadinstitute.barclay.argparser.LegacyCommandLineArgumentParser.parseOption(LegacyCommandLineArgumentParser.java:563)
	at org.broadinstitute.barclay.argparser.LegacyCommandLineArgumentParser.parseArguments(LegacyCommandLineArgumentParser.java:379)
	at picard.cmdline.CommandLineProgram.parseArgs(CommandLineProgram.java:309)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:196)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)

```

Any idea what I am doing wrong? I want to clear that parameter, I dont want any value...

**Comment by yfarjoun** [comment]
interesting. This might be a bug. Given that this is internally an integer, you can give 2147483647 and thus a read will never be considered too far from a probe...is that a reasonable workaround?

**Comment by yfarjoun** [comment]
@cmnbroad what does null do with primitive types in barclay?

**Comment by xexpanderx** [comment]
The problem is that I also want to "clear" following parameters:

MINIMUM_MAPPING_QUALITY 
MINIMUM_BASE_QUALITY 
NEAR_DISTANCE 
COVERAGE_CAP
SAMPLE_SIZE 

Is the same error for those parameters as well when inputting "null".

**Comment by yfarjoun** [comment]
The code hasn't been designed for the usecase of no limits on any of these parameters and you will likely run into runtime problems (memory, time, etc)....what are you trying to do?

**Comment by magicDGS** [comment]
Primitive values in Barclay cannot be required because they aren't nullable, so they can't be "clear" either. I don't know if it makes sense to clear these values, but if so they should be converted to boxed variables.

**Comment by yfarjoun** [comment]
that makes sense. So it would be good if barclay checked this and failed during testing when observing an optional @Argument that points to a primitive type...

**Comment by xexpanderx** [comment]
@yfarjoun I want to compare my results from the results used with version: 1.96. This Picard version did not have those parameters.

So I want to mimic the results from Picard 1.96 using Picard 2.14.1.

**Comment by yfarjoun** [comment]
I see. Looking at the code for version 1.96, it seems to be almost equivalent to running the current version with the following arguments: 

NEAR_DISTANCE = 250 // which is the current default.
MIN_MAPPING_QUALITY = 1 // i.e. MQ=0 was filtered out but nothing else
MIN_BASE_QUALITY=0 // i.e. no filtering on base qualities
COVERAGE_CAP= 2147483647 // no filtering on coverage either
SAMPLE_SIZE = N/A // this is a parameter that pertains to the HET_SENSITIVITY metric which didn't exist in 1.96, so you can leave it as is.

Does this help?

I do not expect the results to match exactly since there could be other, more subtle differences in the implementation, but I think that this is the closest you can get to.

**Comment by xexpanderx** [comment]
Running like this:
`
java -Xmx7g -jar /sw/pipelines/bcbio-nextgen/1.0.5/anaconda/share/picard-2.14.1-0/picard.jar CollectHsMetrics USE_JDK_DEFLATER=true USE_JDK_INFLATER=true BAIT_INTERVALS=/projects/wp3/Reference_files/Manifest/Clinical_research_exome/S06588914_Covered_bait_hg19_consensus.txt TARGET_INTERVALS=/projects/wp3/Reference_files/Manifest/Clinical_research_exome/S06588914_Covered_bait_hg19_consensus.txt INPUT=NS12911-ready_2.bam OUTPUT=test3_HsM.txt VALIDATION_STRINGENCY=LENIENT MINIMUM_MAPPING_QUALITY=1 MINIMUM_BASE_QUALITY=0 COVERAGE_CAP=2147483647`

I get this error:

```
[Wed Nov 22 15:54:50 CET 2017] picard.analysis.directed.CollectHsMetrics done. Elapsed time: 27.08 minutes.
Runtime.totalMemory()=2765094912
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NegativeArraySizeException
	at picard.analysis.directed.TargetMetricsCollector$PerUnitTargetMetricCollector.calculateTargetCoverageMetrics(TargetMetricsCollector.java:634)
	at picard.analysis.directed.TargetMetricsCollector$PerUnitTargetMetricCollector.finish(TargetMetricsCollector.java:626)
	at picard.metrics.MultiLevelCollector$AllReadsDistributor.finish(MultiLevelCollector.java:208)
	at picard.metrics.MultiLevelCollector.finish(MultiLevelCollector.java:324)
	at picard.analysis.directed.CollectTargetedMetrics.doWork(CollectTargetedMetrics.java:153)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)
```

Changing COVERAGE_CAP back to 200 then it works...

**Comment by eitanbanks** [comment]
@cmnbroad I believe this is a real problem.  There doesn't seem to be a way to remove default values from lists in Picard arguments anymore.  We need to fix this ASAP!

**Comment by cmnbroad** [comment]
@eitenbanks As far as I can tell, clearing lists in general seems to work. The issue described here is using null on a primitive type - the  issue you ran into with LiftoverVcf is due to some new list arguments having been added that are initialized to immutable lists. So LiftoverVcf need to be fixed, and we need better error messages, but I don't think there has been a general regression that needs to be fixed. Ping me back if still think there is a bigger issue.

**Comment by eitanbanks** [comment]
@cmnbroad are you saying that it's only a specific set of arguments that need to be changed?  If so, which ones?

**Comment by cmnbroad** [comment]
Right. See https://github.com/broadinstitute/picard/issues/1038.

**Comment by yfarjoun** [comment]
fixed
